### ISSUE TITLE
Requestor lib for batch tasks

### ISSUE THREAD

**Issue by prekucki** [golemfactory/yagna#105]
Provide simple API for different requestor implementations.

```rust

let tasks = vec!["1","2","3","4","5"];
let image_spec = ImageSpec::from_github("prekucki/test-wasi@0.1.0")
  .runtime(WasmRuntime::Wasi(1));

let progress = TaskSession::new("simple wasm app")
  .with_timeout(Duration::from_secs(60))
  .demand(WasmDemand::with_image(image_spec).min_ram_gib(0.5).min_storage_gib(1))
  .tasks(tasks.into_iter().map(|arg| commands! {
     deploy;
     start;
     run("test-wasi", arg)
     stop;
  })
  .run();

tui_progress_monitor(progress).await;

```

TODO:

- [ ] Hide configuration in enviroment variables. 
- [ ] Write simple negotiation
- [ ] Write helpers for `WasmDemand`
- [ ] Write simple scheduler
- [x] Write helpers to build Commands (macro commands!)
- [ ] Wrtie simple tui reporter

**Comment by filipgolem** [comment]
https://github.com/golemfactory/yagna/issues/105

**Comment by filipgolem** [comment]
https://github.com/golemfactory/yagna/pull/163
