### ISSUE TITLE
yagna rc2 (and earlier) didn't exit correctly when Ctrl-C-d from and had to be killed with kill -9

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna#1104]
blue - macos mojave -yagna rc2 (and earlier) didn't exit correctly when Ctrl-C-d from and had to be killed with kill -9

**Comment by maaktweluit** [comment]
I remember this issue was reported earlier, maybe we can find the issue and link them.

**Comment by mateuszsrebrny** [comment]
found a dup: https://github.com/golemfactory/yagna/issues/1023

**Comment by mateuszsrebrny** [comment]
Need data dir @shadeofblue 🙏

**Comment by mateuszsrebrny** [comment]
No data dirs :/
Closing as won't fix for now...

**Comment by shadeofblue** [comment]
experienced this issue again, I have the datadir but would rather not share it here

**Comment by shadeofblue** [comment]
@tworec @mateuszsrebrny please ping me where/whom should I send it to

**Comment by shadeofblue** [comment]
@tworec @mateuszsrebrny any leads here? I'm still actively experiencing this when I allow yagna to run for a longer period of time (possibly through a suspend/revive of my laptop) ...

**Comment by tworec** [comment]
nope, sorry, haven't inspected it yet. This needs to wait a bit more.

**Comment by tworec** [comment]
@shadeofblue is it still an issue for you?

**Comment by mateuszsrebrny** [comment]
@tworec it happened only a couple times a couple patches back.
Let's close it now and reopen when reoccurs
