### ISSUE TITLE
Quotation marks in provider name cause trouble in properties resolver

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna#1142]
Adam Wierzbicki 
Ubuntu 18.04 yagna v0.6.1
Title: Quotation marks in provider name cause trouble in properties resolver

`[2021-03-10T12:23:26Z DEBUG ya_market_resolver::resolver::properties] Error: ParseError { msg: "Error parsing literal: \'\"Grace Hopper aka \\\"Queen of software\\\"\"\'" }`

data dir is attached below.

[yagna.tar.gz](https://github.com/golemfactory/yagna/files/6116313/yagna.tar.gz)

**Comment by biryukovmaxim** [comment]
Hello. I investigated this problem, but have no idea how fix it.

The problem is in this peace of code:


`string_literal<Literal>,
    ws!(delimited!(
        char!('"'),
        do_parse!(val: take_until!("\"") >> (Literal::Str(str::from_utf8(val).unwrap()))),
        char!('"')
    ))`
    
    Howewer I wrote some unit tests that should pass after fix

**Comment by tworec** [comment]
Thanks for your contribution @biryukovmaxim

**Comment by biryukovmaxim** [comment]
> Thanks for your contribution @biryukovmaxim

Actually i solved this issue! Check PR pls
