### ISSUE TITLE
requestor deamon panic after computing(?) provider was shut down

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#1143]
@ederenn Win10+python+3.6.8

```
    [2021-03-10 13:27:28,862 WARNING yapapi.summary] Activity failed on provider '2recs-bikeXphillip-hustler-nodes', reason: (500)
    Reason: Internal Server Error
    HTTP response headers: <CIMultiDictProxy('Content-Length': '297', 'Content-Type': 'application/json', 'Date': 'Wed, 10 Mar 2021 12:27:28 GMT')>
    HTTP response body: {"message":"GSB error: Remote service at `/net/0x39c8979f980f6621e9303b13a79567745fb4446b/exeunit/4929990204054217bd27b202914883b2/Exec` error: Bad request: No service registered under given address '/net/0x39c8979f980f6621e9303b13a79567745fb4446b/exeunit/4929990204054217bd27b202914883b2/Exec'."}

    [2021-03-10 13:33:00,001 INFO yapapi.summary] Received proposals from 47 providers so far
```
[yagna_rCURRENT (3).log](https://github.com/golemfactory/yagna/files/6116321/yagna_rCURRENT.3.log)

**Comment by mateuszsrebrny** [comment]
@maaktweluit has a gut feeling that ExeUnits should have a look first - @mfranciszkiewicz assiginig to you for first look :)

**Comment by cryptobench** [comment]
From what I saw on my daemon it seemed like the requestor was stuck because the daemon was handling all the `terminated`agreements. It kept being spammed over an over, but i'm not sure if that's an error or because it had to terminate 40 times due there being 40 providers.

**Comment by mfranciszkiewicz** [comment]
Caused by 
`2021-03-10T11:29:24Z ERROR ya_sb_router] Error handling messages: Unrecognized message type`

which in turn lead to:
- `[ExeUnit] [2021-03-10 12:29:24.405712 +01:00] INFO [service-bus/bus/src/connection.rs:409] stopped connection to gsb`
- `[ExeUnit] [2021-03-10 12:29:25.418132 +01:00] INFO [exe-unit/src/handlers/local.rs:275] Shutting down: Runtime error: Reporting endpoint is not available: {"batches_done":0,"batches_pending":0,"cmds_done":0,"cmds_pending":0}`

**Comment by tworec** [comment]
It has appeared only on `glen.b1` for the last 7 days
https://yastats.golem.network/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22devnet-beta.1%5C%22%7D%20%7C%3D%5C%22Unrecognized%20message%20type%5C%22%22%7D%5D

![image](https://user-images.githubusercontent.com/12720209/111991641-d25f4d80-8b14-11eb-8f99-35b3bdbc53e9.png)
