### ISSUE TITLE
self_update uses reqwest::blocking

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1152]
Calls to self_update must be wrapped in `tokio::task::spawn_blocking`.

https://docs.rs/reqwest/0.11.2/reqwest/blocking/index.html
> Conversely, the functionality in reqwest::blocking must not be executed within an async runtime, or it will panic when attempting to block. If calling directly from an async function, consider using an async reqwest::Client instead. If the immediate context is only synchronous, but a transitive caller is async, consider changing that caller to use tokio::task::spawn_blocking around the calls that need to block.

**Comment by tworec** [comment]
We are using `0.11.0` and for it documentation does not state that it will panic
https://docs.rs/reqwest/0.11.0/reqwest/blocking/index.html

**Comment by etam** [comment]
because warning was added later: https://github.com/seanmonstar/reqwest/pull/1159
