### ISSUE TITLE
yagna freeze /  unrensponsive

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#1153]
Our self hosted subnet `devnet-beta.1` with `v0.6.1` deployed goes to unresponsive / frozen state from time to time (~once/few days).

Related / Possibly Causing issues:
| state | name | issue(s)|
| -- | --- | -- |
|  FIXED | re-binding is locking GSB | https://github.com/golemfactory/ya-service-bus/pull/15 |
|  NEEDS CHECKING | no file descriptors avail / cannot access DB file / error reading DB file | #1148 and PR #1082 |
|  FIXED | yagna release checker uses blocking HTTP request | #1152 |
|  TRACESS ADDED | Failed to accept invoice from ... reason: (504) Reason: Gateway Timeout - [ ] DB times out (low probability) - [ ] other node unreachable (high probability) - [ ] zkSync operator lags/unreachable (mid probability)  | https://github.com/golemfactory/yagna-triage/issues/84 + #1168 and PR #1158| 
| NOT CRITICAL | activity {} unresponsive after {}s (`got response for unknown request`) | n.a.|
| CLOSED | agreement id for activity not found | #1140 |
| NOT CRITICAL | no local GSB endpoints available | #1107 and https://github.com/golemfactory/ya-service-bus/issues/13 |

**Comment by cryptobench** [comment]
Multiple providers reporting the issue now. Daemon stops or becomes unresponsive and log is filled with database is locked.
![image](https://user-images.githubusercontent.com/33448819/111502481-27324b00-8746-11eb-9d0f-be7a7df41e0d.png)

**Comment by tworec** [comment]
Most important issues was adressed and merged to `release/v0.6`. Will be part of patch release.
