### ISSUE TITLE
Create Activity - increase timeout in SDKs

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1169]
- [ ] yapapi
- [x] yajsapi

**Comment by tworec** [comment]
Requires https://github.com/golemfactory/ya-client/pull/99
and regenerating [`ya-py-aioclient`](https://github.com/golemfactory/ya-py-aioclient)
and [`ya-ts-client`](https://github.com/golemfactory/ya-ts-client)

**Comment by mateuszsrebrny** [comment]
I think this is done @tworec ...

**Comment by filipgolem** [comment]
It's 25 seconds in `yajsapi`.

**Comment by tworec** [comment]
closing in favour of #1162
