### ISSUE TITLE
Yagna periodically freezes on my server

### ISSUE THREAD

**Issue by laa** [golemfactory/yagna#1175]
Yagna periodically freezes on my server and does not respond to any requests unless ```kill -9``` is used. I use 0.6.1 version.
I can attach gdb and provide any information which you need.

**Comment by cryptobench** [comment]
Latest version 0.6.2 should fix this issue. To update just shutdown the daemon and run this command:
`curl -sSf https://join.golem.network/as-provider | bash -`
