### ISSUE TITLE
yagna - SIGINT does not close databases clean

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1194]
Observed on release `0.6.3`

When hitting `C-c` ( or `SIGINT`) i notice the database temp files are still in my data-dir.

When killing `yagna` with `SIGTERM` the databases are closed properly.

Please update `SIGINT` to also close the databases clean-ly like `SIGTERM`

**Comment by maaktweluit** [comment]
Checked the same behaviour on `master`, there it seems all databases are closed properly **except market**

**Comment by nieznanysprawiciel** [comment]
If we didn't touch this topic for so long, that means it probably won't happen.
Closing
