### ISSUE TITLE
Resending issued but not sent invoices

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1200]
- Provider can resend invoices, but Requestor will not accept them after restart, because he doesn't know related Agreements
- Does this belong to "Resilient Daemon" strand? Or is it a "gap" in the Payments implementation?
- Seems like a gap that needs to be closed:, for example
    - On Agent startup use existing APIs to query all unaccepted debitNotes and invoices and decide what to do with them.

**Comment by prekucki** [comment]
duplicate https://github.com/golemfactory/yagna/issues/2822
