### ISSUE TITLE
Broadcast frequency dependent on number of Offers

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1202]
Why:
- Broadcasts are overwhelming the network. We need to minimize the number of them.

What:
- [ ] Compute number of Nodes in network based on Offers in database
- [ ] Adjust mean random broadcast interval based on the computed value

Note: Nodes should adjust their interval, so that the mean frequency of receiving broadcasts in the network remains on a certain (configurable??) level.

**Comment by maaktweluit** [comment]
Since the network is now more stable i think we can postpone this task to after net 2.0.
Then all values surrounding broadcasts should be checked to match local broadcasts.

**Comment by nieznanysprawiciel** [comment]
Closing since we solved the problems with broadcasts mostly. We can reopen this issue if it will be necessary in future
