### ISSUE TITLE
Memory leak in yagna

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1220]
**Why** 
Yagna version: 0.6.3

After running for a long time `yagna service run` can eat 10GB of ram. Probably related to https://github.com/golemfactory/ya-service-bus/issues/20

**What**
 - [ ] investigate what is causing the leak / a
 - [ ] fix the problem(s)

**Comment by nieznanysprawiciel** [comment]
@etam Please check if it is still a problem and reopen if it is

**Comment by etam** [comment]
I think it still needs investigation
![Screenshot_20210616_124043](https://user-images.githubusercontent.com/220752/122205027-13f75e80-cea0-11eb-85a9-c41751705c7c.png)

**Comment by etam** [comment]
I confirm it's resolved.
