### ISSUE TITLE
Bad request: UNIQUE constraint failed pay_invoice.id

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1240]
```│[2021-04-11T21:53:40Z DEBUG ya_service_bus::typed] Call to GetAgreementId failed: Service error: DAO error: Not found: agreement id for activity: bcef3202361a439ab232f350f08849df                                                                                            ┤
│[2021-04-11T21:53:40Z DEBUG ya_service_bus::typed] Call to SendInvoice failed: Service error: External service error: Activity service error: Service error: DAO error: Not found: agreement id for activity: bcef3202361a439ab232f350f08849df                                ┤
│[2021-04-11T21:53:40Z DEBUG ya_service_bus::typed] Call to SendInvoice failed: Bad request: UNIQUE constraint failed: pay_invoice.id, pay_invoice.role
```

[yagna20210411-debug.log.gz](https://github.com/golemfactory/yagna/files/6323883/yagna20210411-debug.log.gz)

found in the logs of https://github.com/golemfactory/yagna-triage/issues/99
related to: https://github.com/golemfactory/yagna/issues/1296

**Comment by maaktweluit** [comment]
@mbenke can you please provide the databases from when you see this error?

**Comment by mbenke** [comment]
@maaktweluit Alas, github does not allow me to upload the logs - they are too big with debug (even compressed). The databases are even worse - 272M compressed with bzip2.  Let's try to arrange some other transfer method.

**Comment by mbenke** [comment]
Access to logs granted as agreed via email

**Comment by cryptobench** [comment]
From a provider but not DEBUG log. I've yet to see it in a DEBUG log from the providers.

[uniqueerror.log](https://github.com/golemfactory/yagna/files/6350107/uniqueerror.log)

**Comment by cryptobench** [comment]
Non-debug log 
[ya-provider_r2021-04-20_13-15-03 (2).log](https://github.com/golemfactory/yagna/files/6375389/ya-provider_r2021-04-20_13-15-03.2.log)

**Comment by cryptobench** [comment]
DEBUG logs 
[yagna_rCURRENT.log.gz](https://github.com/golemfactory/yagna/files/6375395/yagna_rCURRENT.log.gz)
[ya-provider_rCURRENT (1).log.gz](https://github.com/golemfactory/yagna/files/6375396/ya-provider_rCURRENT.1.log.gz)

**Comment by cryptobench** [comment]
DEBUG logs running 0.7.0-rc2 from a provider on Discord. They contain this error.

[0.7.0-rc2.logs.zip](https://github.com/golemfactory/yagna/files/6397218/0.7.0-rc2.logs.zip)

**Comment by tworec** [comment]
Closing this. Work will be continued in #1296
