### ISSUE TITLE
Implement "amend allocation" endpoint

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1244]
*Why:*

* If the user allocated not enough funds for a big task they might realize that in the middle of the task and increase the allocated amount.
* If the allocation was made too big the user might want to lower it so that funds are not blocked and can be user for other allocations at the same time.
* If the task takes long the user might want to extend allocation timeout so that it doesn't get released in the middle of the task.

*What:*

* Implement the missing "amendAllocation" endpoint so that modifying the allocated amount and timeout is possible.
* It shouldn't be possible to set the timeout so that the allocation is already timed-out.
* It shouldn't be possible to lower the allocated amount so that it's lower than the amount already spent.
* Take into account the transaction costs as well.
* Add goth test.

**Comment by prekucki** [comment]
fix #2598
