### ISSUE TITLE
ya runtime sdk

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1253]
owner / leader: @mfranciszkiewicz 

- [x] discuss requirements with other teams
- [x] start designing the service wrapper
- [x] start making "runtime SDK"
- [x] make example wrapped service
- [x] start thinking about required counters / provider changes @jiivan

**Comment by tworec** [comment]
Last point moved to separate issue #1261

**Comment by mfranciszkiewicz** [comment]
Target repository: https://github.com/golemfactory/ya-runtime-sdk

**Comment by jiivan** [comment]
> Target repository: https://github.com/golemfactory/ya-runtime-sdk

LGTM, will give my test suggestion in a separate issue.
