### ISSUE TITLE
[ExeUnit] Warning with offer template (not readable)

### ISSUE THREAD

**Issue by PT400C** [golemfactory/yagna#1282]
Hey,

everytime I would start golem, it eventually prompts me with this message: `[2021-04-28 11:02:16.892165 +02:00] WARN [exe-unit/src/runtime/process.rs:85] Cannot read offer template from runtime; using defaults [/root/.local/lib/yagna/plugins/ya-runtime-wasi]`

Is this anything to worry about?

**Comment by cryptobench** [comment]
Hello! This is a normal message and can be ignored. Nothing to worry about. :-)
