### ISSUE TITLE
Enable retry `accept_invoice`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1297]
Why:
- enable requestor to retry call to `accept_invoice` (it gives 50X on the second call)

What:
- If accept invoice was already processed, provider daemon should return valid GSB response
- If `accept_invoice`  wasn't processed, provider daemon should behave the same

Will fix: https://github.com/golemfactory/yagna/issues/1168

Relates to: https://github.com/golemfactory/yapapi/pull/358

**Comment by nieznanysprawiciel** [comment]
I investigated this together with @maaktweluit and we made a conclusion, that `accept_invoice` call can't fail in case of second call to this GSB endpoint.

**Comment by tworec** [comment]
I need a test to verify this. Can you pls perform one?
