### ISSUE TITLE
Protect `send_debit_note` from 504

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1298]
Why:
- enable provider to survive 504 after `send_debit_note` fails
- We need to sustain Agreements in case 504 issues

What:
- Estimate severity
- Check if the next DebitNote will be handled properly after 504 occures, while calling `send_debit_note`
- Consider changing ya-provider logic, to behave to specially handle 504

Related to #1296

**Comment by maaktweluit** [comment]
We investigated and the `send_debit_note` can be re-send safely.
Also as far as we can see the agreement will not be terminated when this 504 happens.

We do see a an edge case where the accept_debit_note might fail, we made issue #1322 to follow up on this
