### ISSUE TITLE
Enable retry `accept_debit_note`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1299]
**Why** 
Retrying invoices is not going well (being fixed by #1297 )
The similar problem might exist for debit notes.

**What**
- [ ] check if yagna cares about missing debit notes
- [ ] The solution for invoices might be slightly different than for debit notes.

**Comment by maaktweluit** [comment]
We checked the debit notes and it seems they are fine to be skipped.

We made one follow up issue to resolve an edge case #1322
