### ISSUE TITLE
Create separate workflow for SGX tests

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1300]
Why:
- we need to make sure SGX is not broken
- we need faster builds (gain 8-10 minutes per build)

What:
- Extract SGX build from rust workdlow 
- run it only on linux
- Make it required to merge PR

Relates to https://github.com/golemfactory/yagna/pull/1294#discussion_r624514004https://gitlab.lan.golem.network/infrastructure/ya-central-services/merge_requests/1/diffs

**Comment by tworec** [comment]
closing via #1316
