### ISSUE TITLE
GFTP eats all available RAM

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#1317]
I run `yagna` in a docker container, and `blender.py` on a localhost.
Everything works well when I pass correct `YAGNA_API_URL` and `GSB_URL`, but when i forget about `GSB_URL` logs end before first "task sent to provider" and `gftp` consumes all the RAM available.

I made a few attempts to reproduce this without `docker` (e.g. just passing an incorrect `GSB_URL`) and failed.

```
# in a directory with Dockerfile and init.sh described later
curl -L -o yagna.deb https://github.com/golemfactory/yagna/releases/download/v0.6.5/golem-requestor_v0.6.5_amd64.deb
docker build . -t yagna
docker run --name yagna -p 6000:6000 -p 6010:6010 yagna

# other window, after everything started, in yapapi/examples/blender
export YAGNA_APPKEY=$(docker exec -it yagna yagna app-key list | tail -2 | head -1 | head -c59 | tail -c32)

# this hangs and consumes RAM
YAGNA_API_URL=http://localhost:6000 python3 blender.py

# this works
GSB_URL=tcp://127.0.0.1:6010 YAGNA_API_URL=http://localhost:6000 python3 blender.py
```

Dockerfile:
```
FROM debian

ENV YAGNA_API_URL=http://0.0.0.0:6000
ENV GSB_URL=tcp://0.0.0.0:6010

COPY yagna.deb .
COPY init.sh .

RUN chmod +x /usr/bin/* \
    && apt update \
    && yes | apt install -y ./yagna.deb \
    && apt install -y libssl-dev ca-certificates \
    && update-ca-certificates

RUN chmod +x ./init.sh
ENTRYPOINT ./init.sh
```

init.sh:
```
#!/bin/bash

set -m

/usr/bin/yagna service run &

sleep 5

/usr/bin/yagna app-key create requestor
/usr/bin/yagna payment fund --driver zksync
/usr/bin/yagna payment init --sender --driver zksync

fg %1
```

**Comment by mfranciszkiewicz** [comment]
@johny-b I wasn't able to observe `gftp` memory growth in either scenario.

Have you seen this kind of behavior on other machines? It should not matter whether the daemon is running in the container or not, since `gftp` didn't manage to connect to daemon's service bus anyway

**Comment by johny-b** [comment]
@mfranciszkiewicz I haven't seen, but @Wiezzel and @pnowosie had seen the same effect in a similar scenario (they other have `yagna` in a container, but tried to connect to it from other container).

I would guess that container is irrelevant, as you say, but what matters is:
* no running `yagna` on the machine where `yapapi` is executed
* correct `YAGNA_API_URL`, so nothing dies before `gtfp` is used

**Comment by mfranciszkiewicz** [comment]
@johny-b I followed the instructions to the letter and haven't seen any mem increase for gftp (`0.6.5 6317bb3d 2021-05-06 build #141`). gftpi's behavior was the same as observed previously with the following logs printed each second:

```
... trying to connect to: /tmp/yagna.sock
... routing error: Connecting GSB at `/tmp/yagna.sock` failure: Connection refused (os error 111)
```

where gftp is started in server mode (`$ gftp server`) and tries to connect to service bus in a loop.

Since I'm not able to reproduce this, I'm going to test gftp from within a container.

**Comment by johny-b** [comment]
@mfranciszkiewicz I upgraded `gftp` to same version and now the problem disappeared.
I had:
```
$ gftp --version
gftp 0.6.4 (4fc72117 2021-04-15 build #135)
```

And on this old version I had the same repeating 2 lines of error output, but those logs were definitely **not** printed only once per second:
```
jbetley@JB-Precision-3530:~/yapapi/examples/blender$ time RUST_LOG=DEBUG YAGNA_API_URL=http://localhost:6000 python3 blender.py > log 2>&1
^C
real	0m23.378s
user	0m8.264s
sys	0m7.352s 
jbetley@JB-Precision-3530:~/yapapi/examples/blender$ grep 'os error 111' log | wc -l
618620
```

@wiezzel, @pnowosie please confirm problem ends with newer `gftp`.

**Comment by Wiezzel** [comment]
I confirm that the problem does not occur with gftp version `0.6.5`
