### ISSUE TITLE
upgrade the main README

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#1323]
**Why**
- There are some good comments on discord ( #yagna ) regarding the README.

**What**
https://github.com/golemfactory/yagna#readme

- [x] use @scx1332 commens ( https://discord.com/channels/687954211702439971/688012160462618669/843439609983008768 )
- [x] use @johny-b comments

**Comment by scx1332** [comment]
Add links to provider and runtime - SDK readme

**Comment by tworec** [comment]
Closing via https://github.com/golemfactory/yagna/commit/56ffc4ced39945f6897c46460eec6f1ea13508be
