### ISSUE TITLE
Regularly VACUUM databases

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#1337]
Why: Databases seem to grow indefinitely
What:
- Regularly run VACUUM on all databases
- golemsp `vacuum` command, when yagna doesn't start

**Comment by jiivan** [comment]
It just happened on checker. `market.db` grew so large that cleaner was unable to finish and blocked all market DAO.
Running `PRAGMA wal_checkpoint(2);` and `VACUUM` fixed the issue.

**Comment by mateuszsrebrny** [comment]
should this happen automatically for every yagna daemon or only on our side in our checkers?

**Comment by jiivan** [comment]
@mateuszsrebrny first time it was reported on user's machine. It should be done for every daemon.

**Comment by jiivan** [comment]
#1452 Greatly reduced the DB problem. We could still add vacuum command for `golemsp`, but first lets verify on our long running daemons whether growing DB size is still an issue.
