### ISSUE TITLE
golemsp changes presets on start

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#1342]
What I do:
1. Change something in `.local/share/ya-provider/presets.json`
2. Run `golemsp` (`golemsp run --payment-network rinkeby --subnet ttt` to be exact)
3. Agree to a proposed `Price GLM per hour`
4. Open `.local/share/ya-provider/presets.json` and notice the contents changed

Currently I know that:
* if I rename a preset (change `name` and nothing else, updating `active`) I will see two presets, both old and new
* if I remove wasmtime it will be back

This looks like a bug to me.

**Comment by mateuszsrebrny** [comment]
bump, this might be important for the box

**Comment by evik42** [comment]
Created an umbrella issue to check and fix all preset related bugs. https://github.com/golemfactory/yagna/issues/2475
