### ISSUE TITLE
Handle docker entrypoints in VM

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1350]
Why:
- Developer wants to use docker entrypoint in his images

**Comment by mateuszsrebrny** [comment]
Consider task: https://github.com/golemfactory/ya-runtime-vm/issues/93

**Comment by mateuszsrebrny** [comment]
Next release -> after miner one (v0.8)

**Comment by mfranciszkiewicz** [comment]
Entrypoint support is implemented as stated in https://github.com/golemfactory/ya-runtime-vm/issues/3

Entrypoints are not executed by `init` though, this needs to be implemented and tested
