### ISSUE TITLE
Allow to add app-key manually instead of generating it

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1353]
Why:
- It is easier to set already generated app-key instead of acquiring it from yagna daemon (especially in case of running yagna inside docker container)

What:
- User can add his own app-key to `yagna app-key create` command
- If that's difficult, add another command

**Comment by tworec** [comment]
Implementing it will struggle with UX, because the app-key should have a proper format (length and contents).

Related to https://github.com/golemfactory/yagna/issues/1534
One approach to set up docker container with yagna is to prepare `yagna.db` file with pre-configured `id` and `app-key`.

**Comment by mateuszsrebrny** [comment]
@nieznanysprawiciel from Apps team perspective this https://github.com/golemfactory/yagna/pull/1539 is enough and we could close this issue
