### ISSUE TITLE
Verify if python mutliprocesing library issue still exists

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1354]
Why:
- Developers are confused with description https://handbook.golem.network/troubleshooting/common-issues#multiprocessing-python-library-not-working-on-providers

What:
- Check if issue still exists
- Is this issue related only to python library or to multiprocessing in general?

**Comment by tworec** [comment]
@nieznanysprawiciel pls clarify if golemfactory/yagna-docs#51 is proper issue here

**Comment by mfranciszkiewicz** [comment]
Python multiprocessing library did not work due to a missing shared memory device (`/dev/shm`). 

Fixed via https://github.com/golemfactory/ya-runtime-vm/pull/73

**Comment by shadeofblue** [comment]
> @nieznanysprawiciel pls clarify if [golemfactory/yagna-docs#51](https://github.com/golemfactory/yagna-docs/issues/51) is proper issue here

why would the other issue be related?

**Comment by nieznanysprawiciel** [comment]
> > @nieznanysprawiciel pls clarify if [golemfactory/yagna-docs#51](https://github.com/golemfactory/yagna-docs/issues/51) is proper issue here
> 
> why would the other issue be related?

This issue was linked by accident, before description was edited

**Comment by tworec** [comment]
Fixed via golemfactory/ya-runtime-vm#73
