### ISSUE TITLE
payment C O M P A T I B I L I T Y beta.1 vs beta.2

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1360]
Why:
- according to [compatibility policy](https://handbook.golem.network/see-also/compatibility-policy) we need to be backward compatible for two major releases

What:
- We will make payment signature field optional for this release, so according to backwards compatibility policy we can remove the optional flag after 2 releases ( beta.4 or 0.8.0 )

**Comment by tworec** [comment]
related to https://github.com/golemfactory/golem-internal/issues/282

**Comment by mateuszsrebrny** [comment]
@jiivan when it is fixed it should be tested on a provider testing session.
v0.7.0 provider should verify payment from a v0.6.x requestor

**Comment by mateuszsrebrny** [comment]
@ederenn we also want to run v0.7.0 requestors trying to run stuff on devnet-beta.1 and verify the payments afterwards

**Comment by maaktweluit** [comment]
Resolved by #1370
