### ISSUE TITLE
Insufficient Funds Error

### ISSUE THREAD

**Issue by DeveloperInProgress** [golemfactory/yagna#1371]
I am running a requestor on mainnet with zksync driver. I have about 45 GLMs balance but the following error shows up:
`ya_payment.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Content-Length': '51', 'Content-Type': 'application/json', 'Date': 'Sat, 29 May 2021 17:53:45 GMT')>
HTTP response body: {"message":"Insufficient funds to make allocation"}
`

How do I troubleshoot this error?

**Comment by nieznanysprawiciel** [comment]
We suspect that there's a problem with unreleased allocation and funds are reserved. You can check if it is the case by running `golemsp payment status` and check `reserved` column.

We have this issue already in our backlog:
https://github.com/golemfactory/yagna/issues/1752
https://github.com/golemfactory/yagna/issues/1246
