### ISSUE TITLE
ExeUnit Supervisor expects `task_package` property even if it won't be used by service

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1379]
Why:
- Due to this bug services can't run

**Comment by mfranciszkiewicz** [comment]
`task_package` is not required. This change was introduced in https://github.com/golemfactory/yagna/pull/1315

**Comment by Wiezzel** [comment]
I was running yagna `v0.6.5`. I will verify if this bug has been indeed fixed in a newer release.

**Comment by tworec** [comment]
🤦
