### ISSUE TITLE
monitor zksync forwarder @ rinkeby 1/h :  No zkSync payments

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1382]
## Why:
- if rinkeby forwarder is down it might mean mainnet forwarder is also in trouble
- as a faithful golem developer when I see payments not going through when I run my tests I might loose trust in Golem - we would like to avoid this loss :) 

## What:
- increase monitoring of rinkeby zkSync forwarder

---

Name: Mateusz
OS+lang+version (if applicable): win js (and py)
Title: No zkSync payments, they are scheduled, but nothing else is happening

```
[2021-06-01T12:17:41.221+0200 DEBUG ya_zksync_driver::driver] schedule_payment: SchedulePayment { amount: BigDecimal("0.02909432571600000"), sender: "0xa500c54e83f69e1c91c6a8c815f8d48336183a48", recipient: "0x31b6ab7808f5d0b847344303457117f022735078", platform: "zksync-rinkeby-tglm", due_date: 2021-06-01T10:17:39.781799512Z }
```

[yajsapi-2021-06-01_11-59-20.log](https://github.com/golemfactory/yagna/files/6576109/yajsapi-2021-06-01_11-59-20.log)
[data-20210601-1222.zip](https://github.com/golemfactory/yagna/files/6576110/data-20210601-1222.zip)

**Comment by etam** [comment]
https://github.com/golemfactory/yagna-testnet-scripts/blob/master/ansible/envs/production/beta.1/host_vars/devnet_beta_1_office_checker.yml

devnet_beta_1_office_checker is running every hour, testing our office providers and it's using the rinkeby forwarder.
