### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#1393]
Link PRs which are addressing VPN feature

**Comment by mfranciszkiewicz** [comment]
All VPN branches are named `mf/vpn`

- yagna https://github.com/golemfactory/yagna/tree/mf/vpn
- https://github.com/golemfactory/ya-runtime-vm/pull/78
- https://github.com/golemfactory/ya-client/pull/98

Basic VPN support introduced for demo purposes:
- https://github.com/golemfactory/yapapi/pull/444
- https://github.com/golemfactory/ya-py-aioclient/pull/17
