### ISSUE TITLE
Deploy command shouldn't download image from scratch if it was already partially downloaded

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1398]
Why:
- Task can timeout multiple times if image download lasts too long

Related to:
https://github.com/golemfactory/yagna/issues/1376

**Comment by tworec** [comment]
@nieznanysprawiciel pls decide if we're targeting with this for beta.2.patch.2

**Comment by nieznanysprawiciel** [comment]
> beta.2.patch.2

We are

**Comment by mfranciszkiewicz** [comment]
Resolved via #1412
