### ISSUE TITLE
Bad gas estimates for erc20

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1404]
Name: Gert-Jan
Title: ERC20 transaction at 12 GWEI while [gasnow.org](http://gasnow.org) shows 20-30

Proposed solution:
- use gasnow.org rapid when its < 50 GWEI
- use gasnow.org standard when rapid > 50

**Comment by maaktweluit** [comment]
the impact is low because not many users are using the erc20 driver.

the severity is major because when user use it they could wait hours IF the gas price increases right after making the transaction

**Comment by maaktweluit** [comment]
After some internal discussion we changed the severity to minor..

no loss in functionality, just a delay

**Comment by nieznanysprawiciel** [comment]
Because erc20 driver is backup driver, we don't want to spend time on this
