### ISSUE TITLE
Custom counters - analyze changes necessary in all modules

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1415]
Why:
- we need to know what changes are needed

What:
- Analyze full counters path, from Service developer that defines new counters, through ExeUnit Supervisor, which has to query them from Service and expose, to Provider that wants to set prices
- Analyze changes in:
    - Provider
    - Supervisor
    - Runtime API
    - Service SDK
- How does Service owner sets prices for counters?
- How Service developer exposes counters, so that Provider knows what to set?

Warning: New counters will break some Grafana plots

**Comment by mfranciszkiewicz** [comment]
Runtime usage counters are:
- non-decreasing and represent an accumulated value of a certain metric
- specified in the "exeunits.json" file manually or with the help of a new runtime command:
  `runtime-config` (TBD)

Runtime API:
- protocol extension: `RuntimeEvent` message, containing a new `AggregateCounter` message type
  or: `Counter` sub-message containing a subset of counter type messages
- server API extension: interface to publish `RuntimeEvent` messafes
- client API extension: interface to attach a `RuntimeEvent` message listener

ExeUnit:
- custom counters are read via a new `runtime-config` command of the runtime binary,
  which prints out a "exeunits.json" file entry template
- MetricsService: injected with counters from the `runtime-config` command output
- MetricsService: agreement usage vector is validated against the extended metric set
- MetricsService: provides a `RuntimeEvent` counter message type handler, attached
  by the supervisor to the Runtime API client

Runtime SDK:
- EventEmitter: API to publish RuntimeEvents
- Runtime: default implementation for the `runtime-config` command handler
- DOCS: `RuntimeEvent` publishing and the usage counter section

Provider:
- review changes in #1365
- update the preset editor to support runtime usage counters


golemsp:
- comply to changes made to Provider's preset editor
