### ISSUE TITLE
Update wording sent transaction

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1420]
Name: Etam
Title: "Send transaction" is not the best wording
```
    INFO  ya_erc20_driver::erc20::wallet] Send transaction. hash=0x...
```

    I think it should be "Sending transaction" (if it's printed before) or "Sent transaction" (if it's printed after).

**Comment by maaktweluit** [comment]
I think it should be `Transaction sent! 0x...`

**Comment by prekucki** [comment]
old driver issue
