### ISSUE TITLE
Sync meeting about result of custom counters analysis

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1424]
Why:
- we need to inform whole team about results of analysis

What:
discuss results of: https://github.com/golemfactory/yagna/issues/1415

**Comment by mfranciszkiewicz** [comment]
- Provider and the resulting `golemsp` changes will be based on https://github.com/golemfactory/yagna/pull/1365
- ExeUnit and Runtime API modifications are described here: https://github.com/golemfactory/yagna/issues/1415#issuecomment-869484986
