### ISSUE TITLE
Investigate what is causing network overwhelming

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1441]
What:
- Investigate central NET traffic

**Comment by cryptobench** [comment]
FYI: We had an increase of 200 providers online **more** this week compared to last week. Not sure if it's correlated or not.

**Comment by maaktweluit** [comment]
This issue was investigated and created:
- https://github.com/golemfactory/yagna/issues/1443
- https://github.com/golemfactory/yagna/issues/1462
