### ISSUE TITLE
Choose testing scenarios to implement

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1461]
what
- use scenario workshop output https://www.notion.so/golemnetwork/Board-with-test-scenarios-c1c74a2ae0d44d58b98926e0b362a484
- add core team tag on notion for chosen scenarios

why
- use it

**Comment by maaktweluit** [comment]
ask @mateuszsrebrny for the link and please update the description

**Comment by mfranciszkiewicz** [comment]
Issues have been chosen and marked on notion.
