### ISSUE TITLE
"Called service `/local/identity/Get` is unavailable" error spam

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1471]
Version v0.7.2-rc1
Yapapi 0.6.1+29cf04d1fa47d1b95cb3527a541eb81fcff5b7f7

Logs are spammed with:
```
[2021-07-01T13:11:13.985+0200 WARNING yapapi.summary] Worker for provider 'witek.b2' failed; reason: (-32000, 'Called service `/local/identity/Get` is unavailable', {'jsonrpc': '2.0', 'id': 7586763597016759828, 'error': {'code': -32000, 'message': 'Called service `/local/identity/Get` is unavailable'}})
```

Task does not seem to finish, i hit ctrl + c after 2 minutes ( maybe a bit fast, sorry! )

[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/6747696/yagna_rCURRENT.log)
[blender-yapapi-2021-07-01_13.09.42.log](https://github.com/golemfactory/yagna-triage/files/6747701/blender-yapapi-2021-07-01_13.09.42.log)

**Comment by mfranciszkiewicz** [comment]
Identified problems:
- `[2021-07-01T12:13:22.515+0200 ERROR ya_service_bus::connection] protocol error Connection reset by peer (os error 54)`
- `[2021-07-01T13:09:49.760+0200 ERROR actix_server::accept] Error accepting connection: Too many open files (os error 24)`

**Comment by maaktweluit** [comment]
bummer! i should have ran `lsof -p` will reproduce the issue and check :)

**Comment by nieznanysprawiciel** [comment]
Part of this is related and will be fixed with issue: https://github.com/golemfactory/yagna-triage/issues/129
The only thing we can do here is to improve error message in gftp
