### ISSUE TITLE
Goth: Requestors abandoning tasks

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1506]
[source](https://www.notion.so/golemnetwork/Requestors-abandoning-tasks-misbehaving-problems-80af23ae32c1459487781200c410908e)

- *Description / steps: Requestors start tasks and ctrl-c. New Requestors are trying to compute something, but network is busy. (Note: There can be many states of Agreement from perspective of Provider, in which Requestors can abandon task)*
- *Expected behavior: Requestors are able to compute, but after longer time. Provider's are expected to break Agreements in reasonable time*
- Gothability: **high effort, medium risk**

Proposal: TBD

**Comment by mfranciszkiewicz** [comment]
blocked by #1530
