### ISSUE TITLE
goth UX: reduce the number of tracebacks in logs

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1530]
Improve internal error propagation to reduce the number of tracebacks in logs (e.g. when trying to manually handle errors).

Consult with the goth team whether it's already WIP

**Comment by zakaprov** [comment]
This is in progress here: https://github.com/golemfactory/goth/issues/517

**Comment by tworec** [comment]
Closing as a duplicate of the above.
