### ISSUE TITLE
Declarative yagna config meeting

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1534]
Apps team request: Declarative yagna config ( ID + app-key )

- discuss security dangers
- decide on the approach
  - config file
  - db modifications
  - db preset (db file with pre-defined state)

**Comment by tworec** [comment]
It is needed by #1531

**Comment by nieznanysprawiciel** [comment]
We don't need this meeting anymore, since problem is solved by: https://github.com/golemfactory/yagna/pull/1539
