### ISSUE TITLE
Return a proper (cmd not implemented) message for `yagna id drop`

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1535]
Currently yagna id drop method is not implemented and return and error. 

**Acceptance Criteria:**
- Add a more user friendly error message for yagna id drop - example "This method is not yet implemented".

**Additional Information:**
- Task for implementing yagna id drop: https://github.com/golemfactory/yagna/issues/455

**Comment by jiivan** [comment]
It's a duplicate of #455

**Comment by evik42** [comment]
@jiivan this issue is about returning a more user friendly error message without implementing the logic.
#455 is about actually implementing `yagna id drop`.

**Comment by pwalski** [comment]
Moving to maintenance because message `Error: Bad request: endpoint address not found` on `id drop` of existing address is a bug.

**Comment by jalas167** [comment]
closing as yagna id drop is already implemented in https://github.com/golemfactory/yagna/issues/455
