### ISSUE TITLE
Difference in gftp --version between 0.7.3 released as .deb and .tar.gz

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/yagna#1553]
I've downloaded `golem-provider_v0.7.3_amd64.deb` and `golem-requestor-linux-v0.7.3.tar.gz` on 2021-08-03 (around 3:30 pm) from https://github.com/golemfactory/yagna/releases.
```bash
$ 0.7.3-provider-deb/gftp --version
gftp 0.2.3 (10116c7 2021-07-28 build #164)
$ 0.7.3-requestor-tgz/gftp --version
gftp 0.7.3 (10116c7d 2021-07-28 build #164)
```

**Comment by azawlocki** [comment]
Comment from @mfranciszkiewicz:

> One of them is a deb, which has no access to the git binary while building on GA,
> hence is unable to read the release tag. The version comes from gftp's Cargo.toml
> (golemfactory/build-deb-action is an isolated action)

**Comment by maaktweluit** [comment]
I also see there is a difference in the SHA printed in the version string:

`10116c7` in the first
`10116c7d` in the second

**Comment by evik42** [comment]
The binaries are the same (although the deb version has one less character in the git hash) but the version is different because of the comment above (deb does not get the version from git tag).
