### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1590]
Old issue: golemfactory/yagna#1935

Name: GJ
yagna version: v0.8.0-rc5
OS+lang+version (if applicable): mac python
Title: too many open files
!!! attach `blender-yapapi.log`, zipped data-dir !!!

```
    [2021-09-09T13:33:30.137+0200 WARNING yapapi.summary] Worker for provider 'erar02' failed; reason: (-32000, 'Called service `/local/identity/Get` is unavailable', {'jsonrpc': '2.0', 'id': 1342121372627685990, 'error': {'code': -32000, 'message': 'Called service `/local/identity/Get` is unavailable'}})
```

Attached are the logs and `lsof -p` output for yagna / gftp / blender(yapapi) 

[blender-yapapi-2021-09-09_13.29.19.log](https://github.com/golemfactory/yagna/files/7137333/blender-yapapi-2021-09-09_13.29.19.log)
[yagna_rCURRENT (7).log](https://github.com/golemfactory/yagna/files/7137334/yagna_rCURRENT.7.log)
[gftp.txt](https://github.com/golemfactory/yagna/files/7137335/gftp.txt)
[yagna.txt](https://github.com/golemfactory/yagna/files/7137336/yagna.txt)
[yapapi.txt](https://github.com/golemfactory/yagna/files/7137337/yapapi.txt)

**Comment by nieznanysprawiciel** [comment]
@mfranciszkiewicz suggests to increase files limits for the process on startup

**Comment by mateuszsrebrny** [comment]
@nieznanysprawiciel do we have a plan to address this in beta.3 timeframe?

**Comment by nieznanysprawiciel** [comment]
No we are not. I removed the label

**Comment by nieznanysprawiciel** [comment]
The same problem as: https://github.com/golemfactory/yagna/issues/1935
Closing
