### ISSUE TITLE
VPN - investigate and fix the cause of long connection times

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1597]
why
- we want fast connections in VPN

what
- use the ssh example from yapapi to investigate what component takes up most time on connection.
- confirm the problem still exists on hybrid net
  - if so: create new issue to fix it
  - if not: mark as "wont do"

**Comment by jiivan** [comment]
```
$ for i in {1..10}; do /usr/bin/time -f '%e' sshpass -p 'Dqjv7q7I' ssh -o ProxyCommand='websocat asyncstdio: ws://127.0.0.1:12502/net-api/v1/net/4bdb83c86ce04b068c4402555d3e7d9b/tcp/192.168.0.2/22 --binary -H=Authorization:"Bearer 8720cdfeb4ce4f499fc8f81b6b18ea81"' root@737e10c9205547b79a29f7ebbef135e8 'echo "ZZZ" > /dev/null'; done
1.02
1.02
1.08
1.16
1.24
1.03
1.04
1.13
1.09
1.09
```

**Comment by jiivan** [comment]
Using branch before #1802
```
$ for i in {1..10}; do /usr/bin/time -f '%e' sshpass -p 'kkYvFGnS' ssh -o ProxyCommand='websocat asyncstdio: ws://127.0.0.1:12502/net-api/v1/net/4e36f8065a8d4d3db0485d83eb4acf07/tcp/192.168.0.3/22 --binary -H=Authorization:"Bearer 8720cdfeb4ce4f499fc8f81b6b18ea81"' root@d9f1bda063cb4461807ccf646559fc53 'echo "ZZZ" > /dev/null'; done
1.15
1.25
1.20
1.09
1.02
1.10
1.01
1.21
1.16
1.26
```

**Comment by wkargul** [comment]
There is no longer long connection times issue. There is no human perceptible difference when using either ssh via Golem network or standard VPN (both for central and hybrid net). Calling `$ for i in {1..10}; do /usr/bin/time -f '%e' [...]` gives times between 1 to 1.5 second. Issue can be closed.
