### ISSUE TITLE
Make zksync driver more resilient to error responses

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1603]
Found by https://github.com/golemfactory/yagna-triage/issues/137

Every call we make to the zksync provider RPC (using zksync driver) can fail. Make sure they are all re-tried properly.

Think about:
- HTTP errors: e.g. Gateway timeout ( 504 / 520 )
- JSON-rpc errors
- ... ?

**Comment by nieznanysprawiciel** [comment]
Not important enough. Closing
