### ISSUE TITLE
Update installer or ya-provider to have proper default EXE_UNIT_PATH

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1636]
why:
- default directory has changed where provider is looking for runtimes

what:
- adjust installer ( f.i. create a symlink )

**Comment by nieznanysprawiciel** [comment]
Blocked
Ask @prekucki why he needs relative directories in `ya-provider`

**Comment by maaktweluit** [comment]
reqc made the change to make yagna more portable, this was needed for windows thorg
