### ISSUE TITLE
REST and GSB APIs for listing agreements

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1658]
Why:
- Request from Box team
    - This information will be displayed to users
- Other potential usages (in the future)
    - It will make Reloading Agent state after restart possible
    - Node retrospection (tools that would check content and state of yagna daemon)

What:
- [ ] yagna REST
- [ ] yagna GSB
- [ ] Agreements are listed only for identity that created them
- [ ] Ability to filter by `app_session_id`, date and state
- [ ] We need ability to list all Agreements (not only active)
- [ ] Update `ya-client`
    - [ ] openapi spec
    - [ ] rust client implementation

**Comment by Wiezzel** [comment]
@nieznanysprawiciel What is the status of this?

**Comment by nieznanysprawiciel** [comment]
Postponed due to higher priority things (for example basic authentication runtime). If anything in terms of priority changed, let us know
