### ISSUE TITLE
Filter Provider earnings by payment driver and/or network

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1660]
Why:
- Request from Box team
- provider wants to display total earnings ( from date )

What:
- [x] Consider what API would be useful on each level (yagna REST, yagna GSB, yagna CLI, golemsp)
- [x] add optional `--payment-network` and `--payment-driver` arguments

**Comment by wkargul** [comment]
In case of consideration regarding what API is useful on which level:
- golemsp - the main issue here is how to represent the output of filtering for the user. As this is request from Box team it does not make sense to modify `golemsp` as this is the additional layer on yagna CLI. Therefore modification of yagna CLI makes sense.
- yagna CLI - I implemented code change to allow user querying yagna. The response of yagna may be fetched in json format what is expected by the Box team.
- yagna GSB - yagna CLI uses yagna GSB as per my best understanding.
- yagna REST - this allows to query yagna via REST API so this provides the second option for fetching required data (next to CLI).

yagna CLI:
- You are now able to use command: `yagna payment status` with `--driver`, `--network` and `--last` options. In example: `yagna payment status --driver erc20 --network polygon --last 1week --json` -> so you receive json with filtered data. **"amount"** (first line of json) reflect the total amount on the account, this is the amount of your funds (not affected by filtering with --last option!)

yagna REST:
- You are now able to send requests via REST API. For more details please check ya-client [specification](https://github.com/golemfactory/ya-client/blob/master/specs/payment-api.yaml)
- Please approve [PR ](https://github.com/golemfactory/ya-client/pull/116)on ya-client and make sure that Cargo.toml under yagna reflect the correct dependency to the right version ya-client.

Please let me know if you need any clarification.
