### ISSUE TITLE
yagna hangs on ctrl-c after computer is sleeping

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1680]
Why:
 - Daemon should work reliably after suspend
 - Operator might get frustrated if he won't be able to close yagna gracefuly 

What:
 - Verify whether running time is a factor
 - Locate a cause of failure to resume after suspension

Reproduction:
- Suspend computer after yagna running for few days
- hit `ctrl-c`

Yagna won't close, you need to hit `kill -9`

**Comment by tworec** [comment]
Replicated again at today's testing session.

Bump

**Comment by nieznanysprawiciel** [comment]
This topic doesn't seem to be so big problem at this moment. Closing
