### ISSUE TITLE
Goth failure of 17.11.2021 "Battle of Arcole"

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#1685]
Why:
 - We want to have a stable master
 
What:
 - Investigate & fix

Failed run url: https://github.com/golemfactory/yagna/actions/runs/1469830848

**Comment by mfranciszkiewicz** [comment]
These tests were run on a previous release branch `release/v0.8`, which does not contain recent fixes from `master` and `release/v0.9`
