### ISSUE TITLE
Hybrid NET

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1690]
**Why:**
- We want to enable p2p communication between nodes
- Current central NET solution suffers from performance/scaling issues

**What:**

_**Milestones**_:
- [x] https://github.com/golemfactory/yagna/issues/2099
- [x] https://github.com/golemfactory/yagna/issues/2119
- [x] https://github.com/golemfactory/yagna/issues/2126
- [x] https://github.com/golemfactory/yagna/issues/2120
- [x] https://github.com/golemfactory/yagna/issues/2121
- [x] https://github.com/golemfactory/yagna/issues/2122

**Prepare Release**
- [ ] ...

**Next quarters ideas:**
- [ ] https://github.com/golemfactory/ya-relay/issues/10
- [ ] https://github.com/golemfactory/yagna/issues/1859
- [ ] https://github.com/golemfactory/ya-relay/issues/32
- [ ] https://github.com/golemfactory/ya-relay/issues/41
- [x] https://github.com/golemfactory/yagna/issues/1882

**Archive tasks:**

MVP:
 - [x] https://github.com/golemfactory/ya-relay/issues/13
 - [x] https://github.com/golemfactory/ya-relay/issues/15
 - [x] https://github.com/golemfactory/ya-relay/issues/14
 - [x] https://github.com/golemfactory/yagna/issues/1615
 - [x] https://github.com/golemfactory/ya-relay/issues/64

Testing:
 - [x] https://github.com/golemfactory/ya-relay/issues/40
 - [x] https://github.com/golemfactory/golem-internal/issues/346
 - [x] #1699
 - [x] https://github.com/golemfactory/yagna/issues/1646
 - [x] golemfactory/yagna-testnet-scripts#154
 - [x] #1711
 - [x] ...

Fixes:
- [x] #1812
- [x] #1806
- [x] #1807
- [x] https://github.com/golemfactory/ya-relay/issues/74
- [x] #1817
- [x] Many fixes.. (I don't want to paste all tasks here)

~NET can limit bandwidth:~
 - ~[ ] https://github.com/golemfactory/ya-relay/issues/55~
 - ~[ ] https://github.com/golemfactory/ya-relay/issues/56~

**Comment by jalas167** [comment]
goal completed, release in November
