### ISSUE TITLE
golemsp ignores exeunit-name property in the presets file?

### ISSUE THREAD

**Issue by pnowosie** [golemfactory/yagna#1701]
What:
- investigate whether `name` and `exeunit-name` can differ

Let's say I configure castom exe-unit runtime.
I added preset entry in `~/.local/share/ya-provider/presets.json` file as follows:
```json
{
      "name": "erigon",
      "exeunit-name": "ya-runtime-erigon",
...
```
⚠️ Note: __`name` & `exeunit-name` differs.__

Then I created a desriptor file `~/.local/lib/yagna/plugins/ya-runtime-erigon.json`
```json
[
  {
    "name": "ya-runtime-erigon",
    "version": "0.1.0",
 ...
```

Running `golemsp run --payment-network rinkeby --subnet ttt` fails with the information that `ya-runtime-erigon` is missing from the presets file. Opening the presets file after the failure one can discover additional entry like this:
```json
{
      "name": "ya-runtime-erigon",
      "exeunit-name": "ya-runtime-erigon",
...
```

**Comment by evik42** [comment]
Created an umbrella issue to check and fix all preset related bugs. https://github.com/golemfactory/yagna/issues/2475
