### ISSUE TITLE
ExeUnit: pass extra flags from runtime descriptor to binary

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1702]
**What:**

Users can add custom flags / arguments in a runtime descriptor, which will be passed down from the Provider Agent, through ExeUnit, to the Runtime binary.

**Why:**

A single Runtime binary can support multiple operating modes that could be selected via a custom flag or argument.

Currently, the Provider passes down all extra flags and arguments set in a descriptor, but that feature is not implemented in ExeUnit.

**Use case:**

Erigon runtime. Currently the expected behaviour (multiple operating modes) cannot be implemented properly.

**Comment by pnowosie** [comment]
Is it much work to get runtime name (and it's default configuration file path) from the descriptor file `name` property?
Runtime name (& config file path) right now are get from the cargo project name which might be very different from the actual runtime file's name and causes confusion.

I guess the above extra flags that we want to pass from exe-unit to the runtime will be obtained from the runtime's descriptor file. Shall we also fix the name & config file path?

**Comment by mfranciszkiewicz** [comment]
@pnowosie 
> Is it much work to get runtime name (and it's default configuration file path) from the descriptor file `name` property? Runtime name (& config file path) right now are get from the cargo project name which might be very different from the actual runtime file's name and causes confusion.

The descriptor file is interpreted by the Provider Agent in order to:

1. Advertise the execution environment on the market.
2. Manage hardware resource caps for each environment.
3. Pass the proper runtime binary path and arguments to ExeUnit.

We don't want to introduce coupling between the provider-only descriptor file and the runtime binary, these extra arguments should be enough to differentiate the runtime operating mode.

> I guess the above extra flags that we want to pass from exe-unit to the runtime will be obtained from the runtime's descriptor file. 

That's right, but these arguments are generic. They need to be interpreted by the runtime implementation.

> Shall we also fix the name & config file path?

The config file path may become configurable in the SDK, i.e. will not be fixed at the project name, set at build time. It's still possible to store all configuration variants in a single file. I'm assuming that the goal is to have 2 separate configuration files?
