### ISSUE TITLE
Custom CA bundled into yagna

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1714]
Why:
- users have issues with yagna not finding the system CA bundle

What:
- Distribute yagna with a custom CA bundle (e.g. borrow the bundle from the firefox repository) - TBD
- check whether the miner branch contains the code for including a custom bundle and copy it

**Comment by mfranciszkiewicz** [comment]
The certificate issue was fixed in https://github.com/golemfactory/yagna/pull/1944
