### ISSUE TITLE
[feature] add available hardware to golemsp's VM status

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna#1718]
currently, `golemsp status` reports only `valid` for a VM

could it, additionally, report the available hardware resources?

e.g. 

```
VM    valid
   cpu_threads: 3
   mem_gib: 2.55
   storage_gib: 128.43
```

or, more human-readably:

```
VM    valid
   CPU: 3 threads
   Memory: 2.55 GB
   Storage: 128.43 GB
```

**Comment by cryptobench** [comment]
I support this. 👍

**Comment by nieznanysprawiciel** [comment]
`ya-provider profile list` can do this

**Comment by cryptobench** [comment]
> `ya-provider profile list` can do this

I think `golemsp status` should do this itself. If the purpose of ya-provider profile list was to improve the UX by outputting it in a more human way, then it totally defeats that purpose by:

1) Being behind the `ya-provider` command which is not clearly documented anywhere for the average user
2) You have to run a whole other command which is tiring.

**Comment by shadeofblue** [comment]
> > `ya-provider profile list` can do this
>     2. You have to run a whole other command which is tiring.

maybe not even _tiring_ ... just you have to _know_ there's another command you need to use... why would we want it if we're providing a user with `golemsp` exactly because we don't want them to be overwhelmed with the multitude of options that yagna offers ... 

and again, this _is_ a basic piece of information imvho

**Comment by nieznanysprawiciel** [comment]
I'm open to extend `golemsp status`.
But I want to avoid situation, in which we have everything available in `ya-provider`, but we must forward every command through `golemsp`. Maybe at some point we need to document `ya-provider`.

@jiivan What do you think?

**Comment by jiivan** [comment]
**golemsp** is meant to be a shortcut for the most common provider use-case. Anything custom should be handled by interacting directly with **ya-provider** or **yagna**.

IMHO ideally operator should be able to kick-start his provider node with golemsp and then tweak it by ya-provider/yagna. `golemsp status` is structured as a very concise status message composed of one-liners. I would like it to stay this way. Otherwise the situation will naturally drift to copying whole demon/agent provider functionality in golemsp.

Finally I think that **ya-provider** deserves to be documented.

**Comment by shadeofblue** [comment]
> **golemsp** is meant to be a shortcut for the most common provider use-case. Anything custom should be handled by interacting directly with **ya-provider** or **yagna**.
> 
> IMHO ideally operator should be able to kick-start his provider node with golemsp and then tweak it by ya-provider/yagna. `golemsp status` is structured as a very concise status message composed of one-liners. I would like it to stay this way. Otherwise the situation will naturally drift to copying whole demon/agent provider functionality in golemsp.
> 
> Finally I think that **ya-provider** deserves to be documented.

okay, in that case, please commit to and prepare appropriate user-facing documentation re: `ya-provider` and make sure it's presented on par with the current one featuring `golemsp`, otherwise users are left in the dark ...

**Comment by jiivan** [comment]
@shadeofblue , sure: https://github.com/golemfactory/yagna-docs/issues/82

**Comment by nieznanysprawiciel** [comment]
> @shadeofblue , sure: [golemfactory/yagna-docs#82](https://github.com/golemfactory/yagna-docs/issues/82)

Please decide if new task is enough to close this issue, or do we need something more?

**Comment by nieznanysprawiciel** [comment]
Decided to improve documentation. Closing
