### ISSUE TITLE
yagna payment status should display MATIC/ETH

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1743]
Why:
- Requestor user has to pay for gas and would like to see available balance

What:
- Display MATIC/ETH balance in `yagna payment status`

Payment API, opposed to payment drivers, does not know about MATIC / ETH

resolved by: https://github.com/golemfactory/yagna/pull/1939

**Comment by marian160** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.
