### ISSUE TITLE
fix rinkeby faucet

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1764]
why:
- rinkeby faucet is not giving out funds
- users want to test yagna

what:
- investigate why it stopped working
- implement a fix so this happens less often

**Comment by nieznanysprawiciel** [comment]
Related PR: https://github.com/golemfactory/yagna/issues/1754

**Comment by nieznanysprawiciel** [comment]
We will pick up this task, if the problems will occur regularly

**Comment by tworec** [comment]
> For now i have made a patch to increase the gas by 20% of the original estimate, will make a PR for that shortly.

Related PR: https://github.com/golemfactory/locals-faucetserver/pull/1
