### ISSUE TITLE
Resuming services: ya-exe-unit

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1778]
Context: https://github.com/golemfactory/yagna/issues/1692#issuecomment-984107713

Because ExeUnit or Runtime suspension / restoration may take a substantial amount
of disk space or time, it's recommended to separate it from the (graceful)
process shutdown; i.e., while terminating the process, no state is persisted
to disk. This behavior is also undesirable when an Agreement needs to be
terminated.

The suspension may be triggered in following ways:

a. REST yagna endpoint for suspending the ExeUnit (provider API)
b. sending to and handling a `USR1` or `USR2` signal by the ExeUnit
  (not compatible with Windows)
c. extending `ya-runtime-api` with an interface to control the ExeUnit

Tasks:

- bind and implement a GSB handler for **entering a new `Suspended` state**
  - await current command termination (with a short timeout)
    - terminated command state is reset; the command will be run again after resuming
  - pause the following:
    - next command execution
    - output streaming
    - VPN communication
    - internal usage counter updates (optional)
  - set the state to `(Ready, Some(Suspended))`
  - in background, the ExeUnit snapshots its state:
    - counter values
    - `ExeScript`s
    - command execution state (outputs, return code)
    - VPN state (e.g. node neighborhood)
  - when snapshot serialization is complete, ExeUnit waits for runtime
    process termination
  - set the state to `(Suspended, None)`
  - shutdown ExeUnit

- automatically restore ExeUnit state from the snapshot, if found in the working
  directory; command execution is resumed if some batch wasn't completed

- rule of thumb: runtime process dies second (when the runtime shuts down)

**Comment by nieznanysprawiciel** [comment]
Not planned
