### ISSUE TITLE
Resuming services: ya-runtime-api

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1779]
Context: https://github.com/golemfactory/yagna/issues/1692#issuecomment-984107713

- `RuntimeService::suspend` functtion
  - Client: triggers runtime suspension; called by ExeUnit
  - Server: implemented by the runtime; it's expected to snapshot
    its state and halt the process. The call may be facilitated by
    `ya-runtime-sdk`

- new: `Suspend` protobuf message
  Used by the `suspend` RPC call.

**Comment by nieznanysprawiciel** [comment]
Not planned
