### ISSUE TITLE
`yagna version check` says there's a new version when there's not

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#1781]
I installed `yagna` from a `.deb`: https://github.com/golemfactory/yagna/releases/download/v0.9.1/golem-requestor_v0.9.1_amd64.deb

```
$ yagna -V
yagna 0.9.1 (1887661 2021-12-20 build #189)
$ yagna version check
New Yagna Version 0.9.1 'v0.9.1 Human Solidarity' released 2021-12-20 is available! Update via `curl -sSf https://join.golem.network/as-provider | bash -`
$ yagna version show 
New Yagna Version 0.9.1 'v0.9.1 Human Solidarity' released 2021-12-20 is available! Update via `curl -sSf https://join.golem.network/as-provider | bash -`
```

I think this should say just something like "you have the latest `yagna`, that's cool".

Also few additional things, I'm not sure if worth additional issues:
1. I think `yagna version show` doesn't do what `yagna version help` says it does, i.e. doesn't show the current `Yagna` version.
2. I have a `requestor` yagna and yet it recommends updating via `.../as-provider...` (I'm pretty sure this was already reported?)
3. What is the purpose of passing either `datadir` or `gsb-url` to `yagna version`?

**Comment by pwalski** [comment]
Got:
```
PS C:\Users\przemek> yagna -V
yagna 0.12.0 (37060503 2022-12-02 build #251)
PS C:\Users\przemek> yagna version show
Your Yagna is up to date: Version 0.12.0 'v0.12.0 Marble Castle' released 2022-12-02
PS C:\Users\przemek> yagna version check
Your Yagna is up to date: Version 0.12.0 'v0.12.0 Marble Castle' released 2022-12-02
```
Closing
