### ISSUE TITLE
Invalid yagna binaries used in hybrid net integration test

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1785]
What:
- the integration test suite does not always use the binaries built from a branch

Why:
- the integration test suite should run against the modified code

E.g. 
`[2021-12-29T14:05:39.689+0000 INFO  ya_provider::provider_agent] Starting ya-provider. Version: 0.2.0 (1887661 2021-12-20 build #189).` is used instead of a build from 2021-12-29

[Workflow run](https://github.com/golemfactory/yagna/actions/runs/1634185104)
[Related pull request](https://github.com/golemfactory/yagna/pull/1769)

**Comment by maaktweluit** [comment]
this is odd, we are using the same "download artefact" github action plugin as the normal build..

would recommend to check this step as first part of the investigation

**Comment by jalas167** [comment]
old issue
