### ISSUE TITLE
Database is locked (2022-01-22 edition)

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1800]
I've had "Database is locked" error again.
[logs.zip](https://github.com/golemfactory/yagna/files/7925233/logs.zip)

yagna: 0.9.2
yapapi: 0.8.0

**Comment by maaktweluit** [comment]
previous edition: https://github.com/golemfactory/yagna/issues/1391

**Comment by evik42** [comment]
Closing this, please open a new issue if the problem returns on 0.12.0 or later version.
