### ISSUE TITLE
Check if golem CLI fully supports `goerli`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1803]
Why:
- We want to allow users using `goerli` as this is layer 1 of `mumbai` ( see discusion [here](https://github.com/golemfactory/yagna-triage/issues/171) )

What:
- Test all golemsp commands
- Test `yagna payment`
- Test `ya-provider`

**Comment by evik42** [comment]
We will use rinkeby for the foreseeable future (4-6 months) and migrate to mumbai as faucet is not functional on goerli atm.
