### ISSUE TITLE
Bad request: endpoint address not found in ya_payment

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1808]
yagna 0.9.2

Everything related to ya_payment fails with "Bad request: endpoint address not found".

Steps to reproduce: I have no idea.

logs: [yagna_r2022-01-30_00-04-02.log.zip](https://github.com/golemfactory/yagna/files/7969941/yagna_r2022-01-30_00-04-02.log.zip)

**Comment by etam** [comment]
Here's another one: 
[yagna_r2022-02-03_00-23-00.log.gz](https://github.com/golemfactory/yagna/files/8016092/yagna_r2022-02-03_00-23-00.log.gz)
the first error appears at 2022-02-03T11:36:37

**Comment by etam** [comment]
Loose idea to check: In this case requestor's yagna is started just before running computation and closed some time after it's finished. When running computations repeatedly it's started, stopped, started, stopped and so on. Is it possible that provider doesn't notice that requestor was restarted and tries to reuse a connection, that isn't working?

**Comment by jiivan** [comment]
Same error on market
```
  | [2022-03-29T10:33:17.107+0200 WARN  ya_provider::market::provider_market] Failed to terminate agreement [6c5c7b64171abda4a3d227ca997b427f568447084f8c536dc12783b7a7ce52fe]. Error: HTTP error requesting POST http://0.0.0.0:16665/market-api/v1/agreements/6c5c7b64171abda4a3d227ca997b427f568447084f8c536dc12783b7a7ce52fe/terminate: 500 Internal Server Error; msg: 'Protocol error while terminating: Terminate Agreement [P-6c5c7b64171abda4a3d227ca997b427f568447084f8c536dc12783b7a7ce52fe] GSB error: Remote service at `/net/0x89ef977db64a2597ba57e3eb4b717d3baaebaec3/market/protocol/mk1/negotiation/requestor/agreement/AgreementTerminated` error: Bad request: endpoint address not found..'. Retry after 3708.32753661s
```
