### ISSUE TITLE
"new release" notification despite running the latest official release

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna#1819]
```
[2022-02-04T09:07:16.164+0100 WARN  ya_version::notifier] New Yagna Version 0.9.2 'v0.9.2 Gentle Sun' released 2022-01-10 is available! Update via `curl -sSf https://join.golem.network/as-provider | bash -`

^C[2022-02-04T08:27:24Z INFO  golemsp::service] Got ctrl+c. Bye!
```
[ ... ]

```
$ yagna --version
yagna 0.9.2 (d4a24786 2022-01-10 build #191)
```

**Comment by johny-b** [comment]
Looks like this might be related to #1781

**Comment by shadeofblue** [comment]
more observations: when running `yagna 0.9.2 (d4a24786 2022-01-10 build #191)`, I'm now getting:

```
[2022-02-24T10:24:58.688+0100 WARN  ya_version::notifier] New Yagna Version 0.10.0-rc5 'v0.10.0-rc5 #196' released 2022-02-10 is available! Update via `curl -sSf https://join.golem.network/as-provider | bash -`
```

question 1:

* why it is reporting an RC?

question 2:

* why is it reporting this particular RC? and not the newest one (rc10) - or one in between?

**Comment by wkargul** [comment]
Hi @shadeofblue 

The linked PR should solve the issue. Please check my comment there for a bit more information.

Answer 1:
- Every new release information was fetched from github and put into local data base. yagna was comparing versions to the latest input in db. That's way yagna was reading every new release. Now it is filtered to skip reading "%rc%" versions as well as stop fetching versions without tag `latest` on github.

Answer 2:
- To be honest, I was not able to reproduce this situation. At my end it was always taking the latest RC. As we no longer fetch rc to yagna db I would not worry about it.  On other hand, if there is something what triggers faulty versions comparison it might cause issues in the future. But as far as I checked I see no bugs anymore. What is your opinion about it, @shadeofblue ?
