### ISSUE TITLE
NET - Flexbuffer Read Error when running blender

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1849]
`[2022-02-21T14:25:37.207+0100 ERROR ya_activity::error] Activity API server error: GSB error: Bad content: Flexbuffer Read Error: InvalidRootWidth
`
This is an error response which wasn't properly deserialized.

It happens from time to time when running blender on hybrid devnet.
Sometimes the same error is related to DebitNotes sending

Edit: full log in comment

**Comment by mfranciszkiewicz** [comment]
This is an error response which wasn't properly deserialized
