### ISSUE TITLE
NET - Ping check failure after reconnect

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#1863]
Scenario is identical to #1812

Reproduction:

Setup 2 yagna nodes (Provider, Requestor)
Ctrl-C Requestor node
Wait until server will remove session with Requestor
Start Requestor

**Comment by jiivan** [comment]
Confirmed with ya-relay 6adba03 (main) & yagna 43dc2a07 (release/v0.10)

**Comment by mfranciszkiewicz** [comment]
This issue can no longer be observed
