### ISSUE TITLE
Outbound network - support certificates and certificate chains

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1873]
- [ ] #2093

- [x]  Keystore dir monitoring (the implementation in yagna does not trigger on changes inside a directory)

- [ ]  Distribution/setup of Golem CA cert (+ intermediate cert(s)) in a release build or through https://join.golem.network/as-provider script - will be done within:  #1874
- [ ] #2134

What:
- implement X.509 certificate and certificate chain support in the keystore
  - verify cert expiration dates
- use the public signed key within the certificate to verify the signatures of payload manifests

Why:
- the keystore is public-key based and 
  - there are no expiration dates for the keys
  - it's not possible to create a key chain
- GolemFactory can issue certificates for third-party developers in the future

**Comment by pwalski** [comment]
Created [PR](https://github.com/golemfactory/golem-architecture/pull/54) on golem-architecture.
