### ISSUE TITLE
Outbound network - providers include `inet` capability in their offer

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1875]
What:
- providers supporting the outbound network feature add an `inet` capability to their offers
- **Edit**: providers need to declare that they support payload manifests by setting 
the `golem.srv.caps.payload-manifest` property to `true`

Why:
- requestors can filter providers supporting outbound network

**Comment by pwalski** [comment]
Offers already include `inet` capability which as far as I understand comes from runtime [`golem.runtime.capabilities` property](            "golem.runtime.capabilities": ["inet", "vpn"])

**Comment by pwalski** [comment]
Should the property `golem.srv.caps.payload-manifest` also be part of demand and get verified by provider's negotiator? 
Possibly builtin manifest negotiator somewhere here https://github.com/pwalski/yagna/blob/master/agent/provider/src/market/negotiator/builtin/manifest.rs#L28 
?

**Comment by pwalski** [comment]
^ no, because there will be manifest field already.

Additionally:
- Add new runtime capability `manifest_support`.
- Conditionally enable `golem.srv.caps.payload-manifest` based on offer preset created with usage of exe-unit (enable if `golem.runtime.capabilities` includes `manifest_support`)
- Remove `experimental` from payload related properties

**Comment by pwalski** [comment]
Offer created for VM runtime:
```
[2022-07-08T11:15:28.352+0200 DEBUG ya_provider::market::provider_market] Offer created: {
  "properties": {
    "golem.activity.caps.transfer.protocol": [
      "http",
      "https",
      "gftp"
    ],
    "golem.com.payment.debit-notes.accept-timeout?": 240,
    "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
    "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
    "golem.com.pricing.model": "linear",
    "golem.com.pricing.model.linear.coeffs": [
      6.944444444444445e-6,
      1.388888888888889e-6,
      0.0
    ],
    "golem.com.scheme": "payu",
    "golem.com.scheme.payu.debit-note.interval-sec?": 120,
    "golem.com.scheme.payu.payment-timeout-sec?": 120,
    "golem.com.usage.vector": [
      "golem.usage.cpu_sec",
      "golem.usage.duration_sec"
    ],
    "golem.inf.cpu.architecture": "x86_64",
    "golem.inf.cpu.brand": "Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz",
    "golem.inf.cpu.capabilities": [
      "sse3",
      "pclmulqdq",
      "dtes64",
      "monitor",
      "dscpl",
      "vmx",
      "smx",
      "eist",
      "tm2",
      "ssse3",
      "fma",
      "cmpxchg16b",
      "pdcm",
      "pcid",
      "sse41",
      "sse42",
      "x2apic",
      "movbe",
      "popcnt",
      "tsc_deadline",
      "aesni",
      "xsave",
      "osxsave",
      "avx",
      "f16c",
      "rdrand",
      "fpu",
      "vme",
      "de",
      "pse",
      "tsc",
      "msr",
      "pae",
      "mce",
      "cx8",
      "apic",
      "sep",
      "mtrr",
      "pge",
      "mca",
      "cmov",
      "pat",
      "pse36",
      "clfsh",
      "ds",
      "acpi",
      "mmx",
      "fxsr",
      "sse",
      "sse2",
      "ss",
      "htt",
      "tm",
      "pbe",
      "fsgsbase",
      "adjust_msr",
      "bmi1",
      "hle",
      "avx2",
      "smep",
      "bmi2",
      "rep_movsb_stosb",
      "invpcid",
      "rtm",
      "deprecate_fpu_cs_ds",
      "rdseed",
      "adx",
      "smap",
      "processor_trace"
    ],
    "golem.inf.cpu.cores": 2,
    "golem.inf.cpu.model": "Stepping 4 Family 6 Model 109",
    "golem.inf.cpu.threads": 3,
    "golem.inf.cpu.vendor": "GenuineIntel",
    "golem.inf.mem.gib": 6.0,
    "golem.inf.storage.gib": 30.0,
    "golem.node.debug.subnet": "devnet-beta",
    "golem.node.id.name": "pwalski_provider",
    "golem.node.net.is_public": true,
    "golem.runtime.capabilities": [
      "inet",
      "vpn",
      "manifest_support"
    ],
    "golem.runtime.name": "vm",
    "golem.runtime.version": "0.2.12",
    "golem.srv.caps.multi-activity": true,
    "golem.srv.caps.payload-manifest": true
  },
  "constraints": "(&\n  (golem.srv.comp.expiration>1657271728350)\n  (golem.node.debug.subnet=devnet-beta)\n)"
}
```
Offer created for Wasm runtime:
```
[2022-07-08T11:15:28.384+0200 DEBUG ya_provider::market::provider_market] Offer created: {
  "properties": {
    "golem.activity.caps.transfer.protocol": [
      "https",
      "gftp",
      "http"
    ],
    "golem.com.payment.debit-notes.accept-timeout?": 240,
    "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
    "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
    "golem.com.pricing.model": "linear",
    "golem.com.pricing.model.linear.coeffs": [
      1.388888888888889e-6,
      6.944444444444445e-6,
      0.0
    ],
    "golem.com.scheme": "payu",
    "golem.com.scheme.payu.debit-note.interval-sec?": 120,
    "golem.com.scheme.payu.payment-timeout-sec?": 120,
    "golem.com.usage.vector": [
      "golem.usage.duration_sec",
      "golem.usage.cpu_sec"
    ],
    "golem.inf.cpu.architecture": "x86_64",
    "golem.inf.cpu.cores": 2,
    "golem.inf.cpu.threads": 3,
    "golem.inf.mem.gib": 6.0,
    "golem.inf.storage.gib": 30.0,
    "golem.node.debug.subnet": "devnet-beta",
    "golem.node.id.name": "pwalski_provider",
    "golem.node.net.is_public": true,
    "golem.runtime.name": "wasmtime",
    "golem.runtime.version": "0.3.0",
    "golem.runtime.wasm.wasi.version@v": "0.9.0",
    "golem.srv.caps.multi-activity": true,
    "golem.srv.caps.payload-manifest": false
  },
  "constraints": "(&\n  (golem.srv.comp.expiration>1657271728383)\n  (golem.node.debug.subnet=devnet-beta)\n)"
}
```

Should I change previously changed property `"golem.node.net.is_public": true,` to `is-public`? (next to it there can be property `*.geo.country_code`)

**Comment by pwalski** [comment]
^ all new properties I added recently will be kebab-case.

**Comment by cryptobench** [comment]
> Offer created for VM runtime:
> 
> ```
> [2022-07-08T11:15:28.352+0200 DEBUG ya_provider::market::provider_market] Offer created: {
>   "properties": {
>     "golem.activity.caps.transfer.protocol": [
>       "http",
>       "https",
>       "gftp"
>     ],
>     "golem.com.payment.debit-notes.accept-timeout?": 240,
>     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
>     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
>     "golem.com.pricing.model": "linear",
>     "golem.com.pricing.model.linear.coeffs": [
>       6.944444444444445e-6,
>       1.388888888888889e-6,
>       0.0
>     ],
>     "golem.com.scheme": "payu",
>     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
>     "golem.com.scheme.payu.payment-timeout-sec?": 120,
>     "golem.com.usage.vector": [
>       "golem.usage.cpu_sec",
>       "golem.usage.duration_sec"
>     ],
>     "golem.inf.cpu.architecture": "x86_64",
>     "golem.inf.cpu.brand": "Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz",
>     "golem.inf.cpu.capabilities": [
>       "sse3",
>       "pclmulqdq",
>       "dtes64",
>       "monitor",
>       "dscpl",
>       "vmx",
>       "smx",
>       "eist",
>       "tm2",
>       "ssse3",
>       "fma",
>       "cmpxchg16b",
>       "pdcm",
>       "pcid",
>       "sse41",
>       "sse42",
>       "x2apic",
>       "movbe",
>       "popcnt",
>       "tsc_deadline",
>       "aesni",
>       "xsave",
>       "osxsave",
>       "avx",
>       "f16c",
>       "rdrand",
>       "fpu",
>       "vme",
>       "de",
>       "pse",
>       "tsc",
>       "msr",
>       "pae",
>       "mce",
>       "cx8",
>       "apic",
>       "sep",
>       "mtrr",
>       "pge",
>       "mca",
>       "cmov",
>       "pat",
>       "pse36",
>       "clfsh",
>       "ds",
>       "acpi",
>       "mmx",
>       "fxsr",
>       "sse",
>       "sse2",
>       "ss",
>       "htt",
>       "tm",
>       "pbe",
>       "fsgsbase",
>       "adjust_msr",
>       "bmi1",
>       "hle",
>       "avx2",
>       "smep",
>       "bmi2",
>       "rep_movsb_stosb",
>       "invpcid",
>       "rtm",
>       "deprecate_fpu_cs_ds",
>       "rdseed",
>       "adx",
>       "smap",
>       "processor_trace"
>     ],
>     "golem.inf.cpu.cores": 2,
>     "golem.inf.cpu.model": "Stepping 4 Family 6 Model 109",
>     "golem.inf.cpu.threads": 3,
>     "golem.inf.cpu.vendor": "GenuineIntel",
>     "golem.inf.mem.gib": 6.0,
>     "golem.inf.storage.gib": 30.0,
>     "golem.node.debug.subnet": "devnet-beta",
>     "golem.node.id.name": "pwalski_provider",
>     "golem.node.net.is_public": true,
>     "golem.runtime.capabilities": [
>       "inet",
>       "vpn",
>       "manifest_support"
>     ],
>     "golem.runtime.name": "vm",
>     "golem.runtime.version": "0.2.12",
>     "golem.srv.caps.multi-activity": true,
>     "golem.srv.caps.payload-manifest": true
>   },
>   "constraints": "(&\n  (golem.srv.comp.expiration>1657271728350)\n  (golem.node.debug.subnet=devnet-beta)\n)"
> }
> ```
> 
> Offer created for Wasm runtime:
> 
> ```
> [2022-07-08T11:15:28.384+0200 DEBUG ya_provider::market::provider_market] Offer created: {
>   "properties": {
>     "golem.activity.caps.transfer.protocol": [
>       "https",
>       "gftp",
>       "http"
>     ],
>     "golem.com.payment.debit-notes.accept-timeout?": 240,
>     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
>     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0x73023bb0b90cfb3242bb0940b54abaf1249444fc",
>     "golem.com.pricing.model": "linear",
>     "golem.com.pricing.model.linear.coeffs": [
>       1.388888888888889e-6,
>       6.944444444444445e-6,
>       0.0
>     ],
>     "golem.com.scheme": "payu",
>     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
>     "golem.com.scheme.payu.payment-timeout-sec?": 120,
>     "golem.com.usage.vector": [
>       "golem.usage.duration_sec",
>       "golem.usage.cpu_sec"
>     ],
>     "golem.inf.cpu.architecture": "x86_64",
>     "golem.inf.cpu.cores": 2,
>     "golem.inf.cpu.threads": 3,
>     "golem.inf.mem.gib": 6.0,
>     "golem.inf.storage.gib": 30.0,
>     "golem.node.debug.subnet": "devnet-beta",
>     "golem.node.id.name": "pwalski_provider",
>     "golem.node.net.is_public": true,
>     "golem.runtime.name": "wasmtime",
>     "golem.runtime.version": "0.3.0",
>     "golem.runtime.wasm.wasi.version@v": "0.9.0",
>     "golem.srv.caps.multi-activity": true,
>     "golem.srv.caps.payload-manifest": false
>   },
>   "constraints": "(&\n  (golem.srv.comp.expiration>1657271728383)\n  (golem.node.debug.subnet=devnet-beta)\n)"
> }
> ```
> 
> Should I change previously changed property `"golem.node.net.is_public": true,` to `is-public`? (next to it there can be property `*.geo.country_code`)

country code in the offers would be highly appreciated!
