### ISSUE TITLE
NET - hybrid network state inspection API + CLI

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1884]
What:
- implement a common code-base for hybrid network state inspection
  - store the following local information:
    - socket type (e.g. UDP) and address
    - peer ID
    - network visibility (public address, NAT type)
  - store the following relay server information:
    - address
    - peer ID
    - last seen timestamp
  - gather the following per-session statistics (including relay):
    - remote peer ID 
    - remote peer socket type (e.g. UDP) and address
    - last message (last seen) timestamp
    - session state (e.g. Initiating, Active, Closing)
      - session duration of Active sessions
    - session connection method (p2p, relayed)
      - relay ID
    - bandwidth usage (analogous to relay server bandwidth usage)
  - gather the following broadcast statistics:
    - count of:
      - received per type
      - sent per type
  - expose the information on:
    - local node
    - relay server
    - global stats
      - session list
      - global bandwidth usage
    - per session stats
    - broadcasts
- design and implement a RESTful api for reading exposed information
- design and implement a CLI for displaying exposed information

Why:
Both users and developers need an insight into the network state of their node in the Golem network

**Comment by nieznanysprawiciel** [comment]
This task is outdated. Parts of functionalities are already implemented. Other parts will be done, when we will see need
