### ISSUE TITLE
Refactor ResponseTable

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1905]
From https://github.com/golemfactory/yagna/pull/1723#issuecomment-1073820750 (it requires #1723 to be merged)

I suggest a further refactoring, to change `ResponseTable` in `core/serv-api/src/lib.rs` from
```rust
pub struct ResponseTable {
    pub columns: Vec<String>,
    pub values: Vec<serde_json::Value>,
}
```
to
```rust
pub struct ResponseTable<T: serde::Serialize>(Vec<T>);
```
or something like that.

**Comment by nieznanysprawiciel** [comment]
We will do this as part of other task

**Comment by etam** [comment]
:cry:
