### ISSUE TITLE
NET - Create yapapi task for measuring performance

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1909]
Why:
- We need measurements

What:
- Task shouldn't compute anything, we want only transfers and pings
- [x] Functionality to choose specific Providers https://github.com/golemfactory/yagna/issues/2021
- [x] VPN ping https://github.com/golemfactory/yagna/issues/2004
- [x] GFTP transfer https://github.com/golemfactory/yagna/issues/2005
- [x] VPN transfer https://github.com/golemfactory/yagna/issues/2006
- [x] Add flag `--json` to enable downloading results as json files https://github.com/golemfactory/yagna/issues/2007

**Comment by wkargul** [comment]
Tool is ready -> https://github.com/golemfactory/ya-perf
