### ISSUE TITLE
GSB endpoints for all CLI commands

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1915]
Why:
- Developers have problems interacting with yagna. Using CLI commands for UI is cumbersome (get app-keys, create app-key,
init wallet).

What:
- We should have GSB endpoint for each CLI command
- `golemsp` should use GSB instead of relying on CLI
- Some way to wait for yagna initialization to be finished

**Comment by Atlas16A** [comment]
I think a good endpoint would be a yagna.initialize function with a config option that details things like the appkey to use, pipe channel to send log info to. And an endpoint for calling the current status with options for specific values like current owed glm etc.

**Comment by nieznanysprawiciel** [comment]
I'm closing this task, because using GSB for communication with yagna will not be simpler than using CLI commands and requires some amount of work.
Maybe we will think about other mechanism for IPC
