### ISSUE TITLE
Multiple invoice events

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#1925]
Sometimes `yapapi` is flooded with maaany "invoice events" for the same invoice, e.g.
```
$ grep "Received invoice event: {'invoice_id': '24b6d2a2-7316-461b-bb52-bf96031a8f13'}" blender-yapapi-2022-04-04_13.22.00.log  | wc -l
40712
```

I've seen this twice:
1. 2022-04-01, around 9:10. I don't have `yapapi` log file, but `yagna` files are included. 
* `yagna` version: `0.9.1`.
* `yapapi` version: IDK, probably `master`
2. 2022-04-04, around 13:30, `yagna` database and `yapapi` log files included.
* `yagna` version: `yagna 0.10.0-reputation-2`
* `yapapi` version: `master`

UPDATE:
1. This sometimes happens. I've just run blender few times in a row and it happened 3 out of 9 (every third run? not sure about this).
2. These are all `<class 'ya_payment.models.invoice_settled_event.InvoiceSettledEvent'>`
3. I see this also on yapapi b0.9, not only on master

[yapapi_log.zip](https://github.com/golemfactory/yapapi/files/8410353/yapapi_log.zip)
[yagna-2022-04-04.zip](https://github.com/golemfactory/yapapi/files/8410363/yagna-2022-04-04.zip)
[yagna-2022-04-01.zip](https://github.com/golemfactory/yapapi/files/8410364/yagna-2022-04-01.zip)

**Comment by johny-b** [comment]
Just a reminder - today I've had quite a lot of entries for a single debit note in my log file:
```
$ grep '5368905f-1cc6-4389-b554-800dff5cf4eb' log_1000-iter-2.log | wc -l
201885
```
:)

(as expected, it had a 0-milisecond timestamp: "timestamp":"2022-06-09T18:20:18Z")

**Comment by etam** [comment]
Here's an example of this happening. Look for 4d1aef67-e5e9-4f5b-9159-3d4502e7d1e0.
[datadir.zip](https://github.com/golemfactory/yagna/files/9054154/datadir.zip)
