### ISSUE TITLE
Extensible `golemsp`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1932]
Why:
- Users are requesting new features in `golemsp`, but it was meant to be simple
- Allow community developers to contribute

What:
- Make `cargo` like extensions system in `golemsp`
- If `golemsp` doesn't know the command, it tries to find binary and forward arguments there

**Comment by jedbrooke** [comment]
Some of the users in the community have made automatic price updater scripts such as [this one](https://github.com/jedbrooke/golem-price-updater/) and [this one](https://gist.github.com/sv3t0sl4v/28f896752edc9e20347ffc6d8cefe74c)

These also seem like they could be candidates for an extensible plugin system for `golemsp`

**Comment by mfranciszkiewicz** [comment]
Instead of extending `golemsp`, we could include that functionality in `yagna`, so that plugins could also be used by requestors

**Comment by mfranciszkiewicz** [comment]
Outcome and initial plans from our internal discussion:
1. `yagna install`-like functionality is **not** planned for now
  We assume that the plugin binaries are resolvable from `PATH` or stored in `~/.local/lib/yagna/plugins`
2. `golemsp` invoked with an unknown sub-command will call `yagna` with the same arguments
  E.g., `golemsp usd status --json` will invoke `yagna usd status --json`
3. `yagna` invoked with an unknown sub-command will try to invoke a `yagna-{subcommand}` binary, including any extra arguments
  E.g. `yagna usd status --json` will invoke `yagna-usd status --json`
4. We need to consider how to support plugins that should be started together with `yagna` (e.g. `ya-aggregator` )

**Comment by nieznanysprawiciel** [comment]
Point 4 is related to price updaters plugins, that @jedbrooke mentioned
