### ISSUE TITLE
Add `yagna payment init --permanent`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1933]
Why:
- Users have to always run `yagna payment init` after starting yagna

What:
- Add `--permanent` flag, which should update `accounts.json` file to init payments automatically on start

**Comment by jiivan** [comment]
IMO full solution would be to add some kind of yagna BIOS i.e. a boot up configuration screen with checkboxes of what should be done during initialization of yagna daemon.

**Comment by nieznanysprawiciel** [comment]
It won't be necessary after: https://github.com/golemfactory/yagna/issues/2116
