### ISSUE TITLE
too many opened files

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna#1935]
Name: Gert-Jan
OS+lang+version (if applicable): MAC-js

```[2021-06-15T12:39:32.636+0200 ERROR actix_server::accept] Error accepting connection: Too many open files (os error 24)
```

[GolemFactory.yagna.zip](https://github.com/golemfactory/yagna-triage/files/6655528/GolemFactory.yagna.zip)

**Comment by nieznanysprawiciel** [comment]
@golemfactory/devops team will monitor open file descriptors after doing task: https://github.com/golemfactory/golem-internal/issues/393

**Comment by smitty-codes** [comment]
Seeing the same open files issue on MacOS 12.4 as well.

**Comment by nieznanysprawiciel** [comment]
Closing in favor of: https://github.com/golemfactory/yagna-triage/issues/232
