### ISSUE TITLE
 "using driver erc20 is not recommended" would be more readable, it's not

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna#1947]
Name: janek
Finding: I guess "using driver erc20 is not recommended" would be more readable, it's not obvious what is "this driver".
    
    ```
    :~/test_yapapi/yapapi {b0.8} $ yagna payment fund --network mainnet
    Using this driver is not recommended. Consider using the Polygon driver instead.
    
    Your mainnet ethereum address is 0x0d75a6bf59b522ce9c148ecf42ab05a6fb97ca7b.
    To be able to use mainnet Ethereum driver please send some GLM tokens and ETH for gas to this address.
    ```

**Comment by jalas167** [comment]
as per 0.15 rc7:

[2024-01-26T16:40:04.256+0100 ERROR ya_payment::cli] Network mainnet does not support automatic funding. Consider using one of the following: [Goerli, Holesky]
Failed
