### ISSUE TITLE
[ERROR golemsp] parsing ya-provider preset list

### ISSUE THREAD

**Issue by EvilSeeQu-sys** [golemfactory/yagna#1963]
One of our user reported that this happens once per ~month, fresh install clear the problem.

[2022-04-21T12:18:37Z ERROR golemsp] parsing ya-provider preset list

    Caused by:
        EOF while parsing a value at line 1 column 0

According to Darek : 
Overall it's about empty file presets.json that is incorect json file. Situation like this should never happen while normal use. If this happens we need to handle that. The special situation is when file is empty, in that case we can treat is as non-existing file.

**Comment by evik42** [comment]
Created an umbrella issue to check and fix all preset related bugs. https://github.com/golemfactory/yagna/issues/2475
