### ISSUE TITLE
[ya-provider] Don't allow preset without a price

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#1972]
Why: It's possible to add preset without any price information, but it subsequently fails when ya-provider tries to create offers and calls `get_prices()`.
```
May 04 15:19:20 raspberrypi4-64 golemsp[1782]: Error: Unsupported coefficients [{}] in preset lhouse [lhouse]
May 04 15:19:20 raspberrypi4-64 golemsp[1719]: [2022-05-04T15:19:20Z ERROR golemsp::service] child provider exited too early: Ok(ExitStatus(unix_wait_status(256)))
```

What; Most probably adding validation to `agent/provider/src/cli/preset.rs::validate_preset` should fix the problem for non-interactive preset creation. Also adding `validita_preset()` invocation in `agent/provider/src/cli/preset.rs::create_interactive()` should solve this for interactive creation process.

Internal discussion: https://discord.com/channels/687954211702439971/707188925030203422/971432587606237334

**Comment by nieznanysprawiciel** [comment]
Related problem that should be solved together with this: https://github.com/golemfactory/yagna/issues/1963

**Comment by nieznanysprawiciel** [comment]
Another presets problem, that should be solved together:
https://github.com/golemfactory/yagna/issues/1701

**Comment by evik42** [comment]
Created an umbrella issue to check and fix all preset related bugs. [#2475](https://github.com/golemfactory/yagna/issues/2475)
