### ISSUE TITLE
Vague error message when creating an app-key

### ISSUE THREAD

**Issue by rezahsnz** [golemfactory/yagna#1984]
`$ yagna app-key create requestor`

When I run the following command to create an app-key, this error is shown which seems pretty uninformative.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: 500, message: "DAO error: UNIQUE constraint failed: app_key.name" }', /home/runner/work/yagna/yagna/core/identity/src/cli/appkey.rs:70:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

I'd rather prefer a simple message like "Hey requestor, the `requestor` app-key already exists".

Context:
Just updated yagna to 0.10.0 and did not delete the .yagna directory created during previous versions, so I think something goes wrong down the road.

**Comment by MrDarthShoe** [comment]
Fixed by https://github.com/golemfactory/yagna/pull/2152.
Now when you try to add already existing app-key name, it's ID will be returned
