### ISSUE TITLE
Switch from `rinkeby` to `sepolia`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1990]
Why:
- rinkeby will be deprecated

What:
- [ ] Add `sepolia` option to `golemsp` and `payment` module
- [ ] Print deprecation message when user explicitly tries to use `rinkeby`
- [ ] `golemsp` testnet group should contain `sepolia` instead of `rinkeby`
- [ ] Setup faucet (Check if code in our repository will work for sepolia)
- [ ] Deploy contracts on testnet

**Comment by nieznanysprawiciel** [comment]
This task depends on @golemfactory/devops team

**Comment by nieznanysprawiciel** [comment]
It seems `sepolia` won't be our main migration target

**Comment by approxit** [comment]
@nieznanysprawiciel If not `sepolia`, which one will be chosen (assuming that `rinkeby` will still be shut down in Q2-Q3 2023)?
