### ISSUE TITLE
Check `ya-exe-unit` for the cause of defragmented  yapapi `stdout` command attribute

### ISSUE THREAD

**Issue by wkargul** [golemfactory/yagna#2035]
As described [here](https://github.com/golemfactory/yagna/issues/2019):
> When executing stdout command in yapapi sometimes it is not passing full stdout as a result.

Examination of `yapapi` did not result with any findings therefore further analysis of `ya-exe-unit` is required.

**Comment by mateuszsrebrny** [comment]
Seems there is nothing wrong on exeunit side, maybe on VM side

**Comment by evik42** [comment]
I am looking into this, after some quick tests `cyclic_buffer` is suspicious.
