### ISSUE TITLE
Outbound network traffic

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2058]
Implementation polishing:
- [x] https://github.com/golemfactory/yagna/issues/1873
- [x] https://github.com/golemfactory/yagna/issues/1875
- [x] golemfactory/yagna#2082
- [x] golemfactory/yagna#2077
- [x] golemfactory/yagna#2087
- ~~[ ] golemfactory/yagna#2137~~
- [x] https://github.com/golemfactory/yagna/issues/2134
  - ~~[ ] #2154 - additional cmdline feature~~
- [x] #2142
- ~~[ ] https://github.com/golemfactory/yagna/issues/2093 (Optional)~~
- ~~[ ] https://github.com/golemfactory/golem-architecture/issues/55~~
- ~~[ ] (Proposed) Prepare GAP-12 as summary of the proposed implementation (https://github.com/golemfactory/golem-architecture/pull/36)~~

Preparing release:
- [x] https://github.com/golemfactory/yapapi/issues/965
- ~~[ ] https://github.com/golemfactory/yagna/issues/1874~~
- [x] golemfactory/yagna#2105
- [x] https://github.com/golemfactory/yagna/issues/2206
- [x] golemfactory/yagna#2088 

Usage examples:
- [x] golemfactory/yagna#2103
- [x] golemfactory/golem-internal#477

**Comment by stranger80** [comment]
Note that there is a placeholder GAP-12 for "Outbound network traffic" - it would be useful for outside observers to have this GAP written (https://github.com/golemfactory/golem-architecture/pull/36)
  - Is there any existing notes, diagrams, articles which can be compiled into GAP-12?  
  - GAP-12 is dependent on GAP-5 (Payload manifest)
  - GAP-12 should mention:
    - new 'capability' enums proposed ('inet'? 'manifest-support'?) tobeincluded (and later added in https://github.com/golemfactory/golem-architecture/blob/master/standards/0-commons/golem/runtime.md)
    - summarize how the outbound network traffic support will be implemented, 
      - presumably as an enhancement to the VM runtime, which will allow tunneling of the network traffic from the VM to the internet via Provider's network interface?
      - the "outbound network router" module will allow control of the outgoing traffic, ie. will only allow a specific set of target addresses <- SECURITY FEATURE		
    - X.509 certificate and certificate chain support for manifest validation (for payload manifests received by Provider in Demands) <- SECURITY FEATURE
      - as indicated in https://github.com/golemfactory/yagna/issues/1873 
    - X.509 certificate revocation handling
    - Allowed domain whitelisting on Provider side - how this will be implemented on Provider side, how a user will be able to configure this?
