### ISSUE TITLE
NET - performance diagnostic

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2068]
- [x] Isolated client - saturate example (https://github.com/golemfactory/ya-relay/issues/180)
  - [x] localhost relay
  - [x] public relay (ping ~30ms)
  - [x] local network (ping ~5ms to router)
- [x] Isolated GSB
  - [x] #2070
  - ~[ ] replace `ya-client` with something to measure performance (test path between GFTP and `ya-client`)~
- [x] #2072
- [x] Wireshark analysis (https://github.com/golemfactory/ya-relay/issues/185)
  - [x] Is low performance result of small number of packets or re-transmissions?
  - [x] Investigate packet loss (packets flood or ip fragmentation)

~- [ ] Use Linux tools to introduce packets loss~

**Comment by mfranciszkiewicz** [comment]
Dropping "use linux tools to introduce packet loss" due to the observable significant packet loss in current communication (https://github.com/golemfactory/ya-relay/issues/185)
