### ISSUE TITLE
Yagna Requestor - Add Global task price settings

### ISSUE THREAD

**Issue by Atlas16A** [golemfactory/yagna#2074]
Simply put this would work in a similar way as how providers set their prices in the cli.
A requestor would input these settings to:
Have them override prices set within task scripts
Have them override prices set within task scripts that go over the requestors settings
Have them act as defaults if a task script does not provide price limits.

This would help requestors set their own price limits without having to edit task script files. It would also help developers who want to share their task scripts as they wont have to add it as a run variable for users.

**Comment by Atlas16A** [comment]
> Actually I didn't think over that stealing funds part -- if they can trick you to use a completely different market strategy, why wouldn't they be able to sneak in a way to change the budget? Or otherwise send funds from your wallet? If they can get you to run scripts on your PC, they can easily get what they want, regardless of the budget or not. It's not hard to run a command from a script.

I've asked on the discord before and apparently task scripts can not directly interact with yagna outside the yapapi and yajsapi api's. Hence why my example doesn't directly manipulate yagna, only useds the currently available market functions to be malicious, but the fact that you can be malicious with just the current api capabilities is a bad thing for requestors.

**Comment by wkargul** [comment]
Hi @Atlas16A and @figurestudios,

Thank you both for your commitment, we appreciate your activity here!
@Atlas16A can you please clarify if there is still some issue with your case? What kind of solution do you propose? Did you try to get through API's documentation?

**Comment by stranger80** [comment]
Hi @Atlas16A,

As @wkargul noted, your voice here is appreciated. As far as I can see, you may have an idea for a feature (probably on`yagna` daemon level). 

We have a process to summarize and evaluate feature proposals (Golem Amendment Proposal - GAP, specified here: [GAP Process](https://github.com/golemfactory/golem-architecture/blob/master/gaps/gap-1_gap_process/gap-1_gap_process.md)) - would you consider putting your idea in a GAP proposal, which requires to consider various aspect of a proposed feature. That way we can get a better understanding of your concept, and put it through a discussion.

Please let us know if you like to follow that route, and if any assistance from our side is required.

**Comment by Atlas16A** [comment]
Yea sure, @stranger80 ill get to work on it probably tomorrow before night shift starts.
