### ISSUE TITLE
GFTP browser support

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2079]
Why:
- Browser should be able to transfer files to Provider Node

What:
- Yagna REST + WS API approach:
  - [x] #2364
  - [x] https://github.com/golemfactory/yagna/issues/2365
- [Dropped] GSB WS support approach:
  - ~[ ] https://github.com/golemfactory/ya-service-bus/issues/46~
  - ~[ ] https://github.com/golemfactory/yagna/issues/2268~
  - ~[ ] #2314~

**Comment by pwalski** [comment]
Updated script
[jsftp.zip](https://github.com/golemfactory/yagna/files/10344288/jsftp.zip)

**Comment by pwalski** [comment]
Closing because subtasks are done.
