### ISSUE TITLE
Automatically export YAGNA_APPKEY

### ISSUE THREAD

**Issue by nzmel** [golemfactory/yagna#2085]
I wrote a small script to automatically export the first APPKEY to $YAGNA_APPKEY. 
I would like to see something like this automatically happen for Yagna for a better user experience. 

Here is my script

``` 
YAGNA_APPKEY=yagna app-key list | awk '{print $4}' | tail -n 3 | head -n 1
echo $YAGNA_APPKEY
export YAGNA_APPKEY
exit
```

**Comment by mfranciszkiewicz** [comment]
@nzmel Unfortunately we cannot export an environment variable from `yagna` to the parent shell. What could be done instead is either:
- a new command, which would print out the command to execute
    ```bash
    $ yagna app-key env
    export YAGNA_APPKEY=0xaabbcc..00
    ```
    which would reduce the necessary steps to
    ```bash
    $ eval $(yagna app-key env)
    $ echo $YAGNA_APPKEY
    0xaabbcc..00
    ```
- spawning a sub-shell with a new command, e.g. `yagna env`

    ```bash
    $ yagna env
    (yagna-env) $ echo $YAGNA_APPKEY
    0xaabbcc..00
    ```

**Comment by mateuszsrebrny** [comment]
closing, please let us know if you need anything else
