### ISSUE TITLE
(test feature) Meet performance goals

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#2094]
- [ ]  https://github.com/golemfactory/ya-relay/issues/145
- [ ]  https://github.com/golemfactory/ya-relay/issues/186
- [ ] https://github.com/golemfactory/ya-relay/issues/187
- [ ] https://github.com/golemfactory/ya-relay/issues/188
- [ ] https://github.com/golemfactory/ya-relay/issues/189
- [ ] https://github.com/golemfactory/ya-relay/issues/190
- [ ] https://github.com/golemfactory/ya-relay/issues/191
- [ ] https://github.com/golemfactory/ya-relay/issues/192
- [ ] https://github.com/golemfactory/ya-relay/issues/193
- [ ] https://github.com/golemfactory/ya-relay/issues/194
- [ ] .. optimization tasks
- [ ] . performance goals task

**Comment by nieznanysprawiciel** [comment]
This was only test issue
