### ISSUE TITLE
Benchmark downloading 4GB video

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2103]
- [x] implement the benchmark
- [x] measure baseline not only with localhost (% of bandwidth)
- [ ] commit as an yapapi example (check with SDK)

**Comment by MrDarthShoe** [comment]
## Environment description

### OS

Ubuntu 22.04.1 LTS

### Hardware
CPU: 12th Gen Intel® Core™ i7-12800H × 20
Memory: 16GiB

### Binaries
yagna: built locally on 04a06f09 commit from master branch
other: got from `curl -ksSf https://join.golem.network/as-provider | YA_INSTALLER_CORE=pre-rel-v0.11.0-rc5 YA_INSTALLER_VM=pre-rel-v0.2.12-rc3 bash -`

**Comment by MrDarthShoe** [comment]
## Downloading file from localhost

### Size of file
4 GB- 4294651876 B

### Benchmarks
| local wget (s) |  Golem (s) |
|---|---|
|  5 | 171  |
| 5  |  155 |
|  4 | 237  |
| 4  |  193 |
|  5 |  190 |
| 5  |  154 |
|  6 |  345 |
|  8 |   163|
| 8  |  201 |
|  8 |  185 |

### Results
On average local wget took around 5.8 s to download file which is ~706 MB/s
On average Golem took around 199.4 s to download file which is ~20 MB/s

Golem uses only 2.8% of bandwidth

**Comment by MrDarthShoe** [comment]
## Downloading file from http://speedtest.tele2.net/#http

### Size of file
1 GB- 4294651876 B

### Benchmarks
| local wget (s) |  Golem (s) |
|---|---|
|  35 | 44  |
| 32  |  44 |
|  31 | 47  |
| 32  |  44 |
|  31 |  42 |
| 32  |  45 |
|  32|  42 |
|  31 |   65|
| 32  |  44 |
|  31 |  44 |

### Results
On average local wget took around 31.9 s to download file which is ~32 MB/s
On average Golem took around 46.1 s to download file which is ~22 MB/s

Golem uses only 68.8% of bandwidth

**Comment by mateuszsrebrny** [comment]
Moving to observed and @nieznanysprawiciel is to negotiate with @stranger80

**Comment by mateuszsrebrny** [comment]
Waiting for testnet certificates and Blue's approval afterwards
