### ISSUE TITLE
Analyze spam lightweight drone tasks checker results

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2114]

**Comment by mfranciszkiewicz** [comment]
The task consists of 75 sub-tasks, 1 minute each.

All task executions were successful. The two timestamps (UTC) correspond to a new demand subscription and the last invoice received.

- `2022-07-31 01:45:03` - `2022-07-31 01:48:20` computed by 46 nodes
- `2022-07-31 09:45:05` - `2022-07-31 09:48:04` computed by 54 nodes
- `2022-07-31 17:45:06` - `2022-07-31 17:48:07` computed by 54 nodes
- `2022-08-01 01:45:11` - `2022-08-01 02:04:47` computed by 55 nodes
- `2022-08-01 09:46:06` - `2022-08-01 09:49:38` computed by 66 nodes
