### ISSUE TITLE
`yagna payment fund` calls `yagna payment init`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2118]
Why:
- We want to simplify user onboarding process and minimize number of commands he needs to execute
- `yagna payment init` call is not clear, why it is necessary

What:
- `yagna payment fund` should execute `payment init`, if it wasn't called by the user manually

**Comment by MrDarthShoe** [comment]
It seems that `payment init` is not necessary for `payment fund`.
