### ISSUE TITLE
Network scaling up to 1k Nodes

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2121]
- [ ] https://github.com/golemfactory/ya-relay/issues/183
- [ ] https://github.com/golemfactory/yagna/issues/2048
- [ ] #2076
- [ ] Heavy GFTP transfers can cause timeouts on other GSB calls
- [ ] https://github.com/golemfactory/ya-relay/issues/38
- [ ] ...

**Comment by jalas167** [comment]
above taks not needed as we already scale. therefore will not do them as part of HN  goal.
