### ISSUE TITLE
Check potential vpnscp bottlenecks

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2131]
- [x] VM network interface (virtio net)
- [x] Double serialization in GSB (flexbuffers and protobuf) - https://github.com/golemfactory/yagna/pull/2089
- [x] Estimate if `ya-relay-stack` update could improve performance (only Requestor-Provider)
- [x] #2210
- [x] #2212
- [ ] #2225

Last resort:
- [ ] ~Compare smoltcp to system network interface (tun)~
- [ ] ~`ya-runtime-vm` uring thread (forward.c)~

**Comment by mfranciszkiewicz** [comment]
#### Estimate if `ya-relay-stack` update could improve performance (only Requestor-Provider)

Daemon's VPN endpoint implementation could benefit from the optimizations introduced to `ya-relay-stack` over the course of previous months. Additionally, it's an opportunity to cut down the maintenance cost of a separate stack implementation

**Comment by mateuszsrebrny** [comment]
continuing in #2225
