### ISSUE TITLE
Benchmark relayed transfers

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2132]
Why:
- We want to know performance of transfers between Nodes using relayed connections

What: 
- Setup benchmarker checker that uses only `ya-relay-server` to forward packets (select nodes w/o p2p - requires only configuration; run multiple times )
- Collect results and include in comment in this task

**Comment by jalas167** [comment]
S

**Comment by nieznanysprawiciel** [comment]
Done in: https://github.com/golemfactory/yagna/issues/2246
