### ISSUE TITLE
Restore `keystore` cmdline args

### ISSUE THREAD

**Issue by pwalski** [golemfactory/yagna#2134]
What:
Reintroduce commands to list add and remove certificates.

Why:
Requestors may issue own certificates which means Providers will need an easy way to manage them.

To determine:
- What should be the output of certificates list
- How to store certificates. Right now we have a monitored directory. Any certificate file copied there will be loaded to the store. PEM certificates can be merged together into one file. In order to support commands for managing certificates it would be better to have some constistent naming and to keep one certificate in one file. Fortunately `openssl` already supports so called `hash dirs` https://www.openssl.org/docs/manmaster/man3/X509_LOOKUP_hash_dir.html Yagna will maintain content of this directory, and `openssl` will lookup for new certificates on demand. Openssl already has a feature called `rehash` which automatically creates symlinks for certificates. Unfortunately it is not provided by rust `openssl`, and also it would be better to just rename files. To decide is whether we want to use `rehash` or implement it (it is fairly simple).

**Comment by pwalski** [comment]
Yagna's `PROVIDER_CERT_DIR` will be a hash dir in a sense openssl understands it:

> The directory should contain one certificate or CRL per file in PEM format, with a filename of the form hash.N for a certificate, or hash.rN for a CRL. The hash is the value returned by the [X509_NAME_hash_ex(3)](https://www.openssl.org/docs/manmaster/man3/X509_NAME_hash_ex.html) function applied to the subject name for certificates or issuer name for CRLs. [..] The .N or .rN suffix is a sequence number that starts at zero, and is incremented consecutively for each certificate or CRL with the same hash value. Gaps in the sequence numbers are not supported

On startup cert dir will be 'rehashed'. 

Rehashing means that every non expired cert / CRL will be renamed to match `hash.N` pattern. Expired certs will be deleted (why keep them? the only problem might happen in case of an accidental startup of provider with date set forward...). Non cert / CRL files will be left untouched (if openssl can read hash_dir having them inside).

On keystore list action certificates cert dir files will be visited to display their data, let say: 
hash.N (as cert id), subject, issuer, issue date, expiration date

On keystore add action given cert file will be copied to hash dir and then hash dir will be `rehashed`.

On keystore delete action file with given cert id will be deleted (cert id == hash.N which is a filename in hash dir). Then directory will be `rehashed` to avoid numeration gaps.

On cert dir content modification the directory will be rehashed.

---

Optional:
Implement displaying certificates as a tree, and cascade deleting when root or intermediate certificate gets deleted.

**Comment by pwalski** [comment]
I needed to make some decisions regarding the way certificate files are handled.

Here are [sample certs](https://github.com/golemfactory/yagna/files/9289925/sample_certs.zip) I am using in following steps describing this behaviour (there is no need of repeating them, I will need to automate it in #2142 in anyway - in case of repeating them do it in dir with provider `.env` file):

1. Command `cargo run -p ya-provider -- keystore add ca.cert.pem intermediate.cert.pem requestor.cert.der requestor.cert.pem`
Will add only `ca.cert.pem  intermediate.cert.pem  requestor.cert.der` to `~/.local/share/ya-provider/cert_dir` - files `requestor.cert.pem` and `requestor.cert.der` are duplicates.

2. Certificates can be listed using `cargo run -p ya-provider -- keystore list`

3. Command `cargo run -p ya-provider -- keystore add ca-chain.cert.pem` will not add anything because this chain contains certificates added in previous step.

4. Command `cargo run -p ya-provider -- keystore remove 06cc4a83db8d12cfa9951fac56d1b29d c39d050d95c961175fe407251b5f257b` will leave `cert_dir` with `ca.cert.pem` only.

5. Running again `cargo run -p ya-provider -- keystore add ca-chain.cert.pem ` will add `ca-chain.cert.c39d050d95c961175fe407251b5f257b.pem` to `cert_dir` because the file will get splitted into individual files for each cert.

6. Run:
`cargo run -p ya-provider -- keystore remove 7051865d7dbd7585798633cf2292be2c c39d050d95c961175fe407251b5f257b`
and then
`cargo run -p ya-provider -- keystore add ca-chain.cert.pem `
Directory `cert_dir` should contain only `ca-chain.cert.pem`
Run `cargo run -p ya-provider -- keystore remove c39d050d95c961175fe407251b5f257b`
Now directory `cert_dir` should contain only `ca-chain.cert.7051865d7dbd7585798633cf2292be2c.pem` because original `ca-chain.cert.pem` got splitted during removing and one of the certs has been ignored (removed).

7. Run `cp ca-chain.cert.pem ~/.local/share/ya-provider/cert_dir`
and then
`cargo run -p ya-provider -- keystore list`
Two certificates should be displayed, because 
a)  the `cert_dir` is only source of certificates so copying there manually works 
b) we ignore duplicated certificates (openssl storage behaves in a same way).

**Comment by nieznanysprawiciel** [comment]
https://github.com/golemfactory/yagna/issues/2134#issuecomment-1209285291
This comment is great description, worth being either in readme or as doc comment to `KeystoreManager`
