### ISSUE TITLE
Goth test rejecting certificate

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2137]
What:
- Test should validate if Provider rejects tasks with certificate that was signed by unknown party
- Additional possibilities
  - No certificate
  - Revoked certificate (if finished, but rather not)

**Comment by pwalski** [comment]
Here are tests for invalid certificate https://github.com/golemfactory/yagna/blob/master/agent/provider/tests/manifest_negotiator.rs#L81
This one covers a case where keystore is empty https://github.com/golemfactory/yagna/blob/master/utils/manifest-utils/tests/certificate_validation.rs#L35
On gitlab you can find a `testnet_certs` project I used to generate/store certificates which were deployed on testnet host

**Comment by MrDarthShoe** [comment]
There are already tests which check that on lower level
