### ISSUE TITLE
Validity column in `keystore list` output

### ISSUE THREAD

**Issue by pwalski** [golemfactory/yagna#2154]
What:
A `keystore list` output column describing certificate status with possible values:

- Ok
- Expired
- Unverified (Invalid?) - this one indicates it cannot be validated because certificate signing listed certificate is unreachable (is not loaded into keystore)

Why:
Intermediate certificates are sometimes chained together with their root CA certs. We allow to delete inidividual certificates, not a whole chains, so it is easy to delete e.g. root CA and leave store with invalid Intermediate CA. We should at least display its state.

**Comment by evik42** [comment]
We already have something similar (expiration date).
