### ISSUE TITLE
Prepare relay "heavy load" test script

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2158]
Write scripts to stress the network with multiple simultaneous:

- [x] simulate a lot connections (target 50k), ~limit new connections per second~
- [x] make lots of get_node & get_neighbourhood & ping calls
- [x] produce csv with the results so that we can see pretty chart in googlesheets
- [x] configurable proportions of requests
- [x] separate connection tests and request tests
- [x] testing variables:
    - [x] rate limit
    - [x] # of connections.

**Comment by mateuszsrebrny** [comment]
M
