### ISSUE TITLE
Parameterized DNS resolver

### ISSUE THREAD

**Issue by pwalski** [golemfactory/yagna#2159]
What:
Parameterize the way IP addresses are resolved.
By default Google DNSs are used. Tokio has default presets for Goolge, Cloudflare, and Quad9.
https://github.com/golemfactory/yagna/blob/db89db8fca4ef83083e0456690d84bef6a7f6d2b/utils/networking/src/resolver.rs#L95
We could provide this as an `exe-unit` parameter (or `yagna` if it is more widely used) which would allow to select one of presets and also to directly list nameservers.

Why:
Default nameservers might be unreachable from Provider network.

**Comment by nieznanysprawiciel** [comment]
Probably won't be done in the nearest future
