### ISSUE TITLE
Flexbuffer error in ExeUnit

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2170]
It happens when running `ya-perf` (happens on `glen` and `witek`)
```
[2022-08-16T17:55:49.273+0200 WARN  ya_exe_unit] Batch e2f2690be5ad44e7ae2b29e4758eb377 execution interrupted: Local service error: Transfer error: GSB error: Bad content: Flexbuffer Read Error: InvalidRootWidth
```

Need to investingate if this is happening on specific nodes only

**Comment by etam** [comment]
I confirm it happens on my requestor with other providers.

**Comment by shadeofblue** [comment]
happened to me just today on `glen`

**Comment by etam** [comment]
According to [my sources](https://yastats.golem.network/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Loki%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bjob%3D%5C%22hybrid%5C%22,service%3D%5C%22yagna%5C%22%7D%20%7C%3D%20%5C%22InvalidRootWidth%5C%22%22%7D%5D) your claim is wrong. I see 4 other providers here: `fbwk2t2.h`, `michal.h`, `65h5jn2.h`, `1nxt4s2.h`

**Comment by etam** [comment]
update: @nieznanysprawiciel was right that now it's only `witek.h`.

Query [`{job="public", hostname!="witek.h"} |= "InvalidRootWidth"`](https://yastats.golem.network/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Loki%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bjob%3D%5C%22public%5C%22,%20hostname!%3D%5C%22witek.h%5C%22%7D%20%7C%3D%20%5C%22InvalidRootWidth%5C%22%22%7D%5D) gives no results

**Comment by kamirr** [comment]
Seen once locally when I had mismatched versions of yagna and the VM.

**Comment by wkargul** [comment]
etam has checked `witek.h` and this is the result of listing versions of particular components:

```
golem-dev@nieznanysprawiciel-imapp:~/public$ ls -lah plugins/
total 28K
drwxrwxr-x 2 golem-dev golem-dev 4,0K gru  5 11:03 .
drwxrwxr-x 6 golem-dev golem-dev 4,0K sty 11 12:59 ..
lrwxrwxrwx 1 golem-dev golem-dev   70 gru  5 11:03 exe-unit -> /home/golem-dev/releases/golem-provider-linux-v0.12.0/plugins/exe-unit
lrwxrwxrwx 1 golem-dev golem-dev   65 gru  5 11:03 ya-runtime-vm -> /home/golem-dev/releases/ya-runtime-vm-linux-v0.3.0/ya-runtime-vm
lrwxrwxrwx 1 golem-dev golem-dev   70 gru  5 11:03 ya-runtime-vm.json -> /home/golem-dev/releases/ya-runtime-vm-linux-v0.3.0/ya-runtime-vm.json
lrwxrwxrwx 1 golem-dev golem-dev   69 gru  5 11:03 ya-runtime-wasi -> /home/golem-dev/releases/ya-runtime-wasi-linux-v0.2.2/ya-runtime-wasi
lrwxrwxrwx 1 golem-dev golem-dev   74 gru  5 11:03 ya-runtime-wasi.json -> /home/golem-dev/releases/ya-runtime-wasi-linux-v0.2.2/ya-runtime-wasi.json
```

it means the setup is as it should be so we have to investigate it further. I can confirm that I have mainly seen this issue on `witek.h` and `glen.h`
