### ISSUE TITLE
Handbook page for hybrid community release

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#2179]
- [x] Installation instruction
- [x] Port forwarding instruction and yagna configuration. 
- [x] Remember to run on proper _subnet_

**Comment by wkargul** [comment]
This is still under review in Notion as other team should also take a look on that.

**Comment by mateuszsrebrny** [comment]
@ArekCybulski ping :)

**Comment by ArekCybulski** [comment]
For me it is ok. 
I handed over the case to Piotr G from Marketing to check this text.
