### ISSUE TITLE
Exporting locked account as unlocked silently exports locked account

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2184]
When trying to export previously locked account, yagna exports locked account but doesn't inform user about it.

**Comment by golmek** [comment]
@MrDarthShoe - Do You remember if export was succesful. I am trying to comprehend was what a root problem in this scenario.

**Comment by jalas167** [comment]
yagna id unlock - unlocks access for local yagna instance, while if there is a password set, the exported key will be still password protected. When it is restored to another instance, it will be locked (and require the password to unlock).
