### ISSUE TITLE
Zksync moved from rinkeby to goerli

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2188]
Zksync stopped working with yagna

**Comment by mateuszsrebrny** [comment]
@EvilSeeQu-sys is to talk with Reqc

**Comment by nieznanysprawiciel** [comment]
This task depends mainly on @golemfactory/devops team

**Comment by mfranciszkiewicz** [comment]
pinging @jiivan

**Comment by jiivan** [comment]
Please elaborate what should be done besides updating driver & network pair in golemsp & implementing https://github.com/golemfactory/yagna/issues/1740 (but adjusted to the Goerli move)?

**Comment by golmek** [comment]
TODO: @nieznanysprawiciel  & @golmek , talk with @jiivan to clarify the issue

**Comment by nieznanysprawiciel** [comment]
ZkSync will be removed
