### ISSUE TITLE
Goth integration tests (nightly) fail

### ISSUE THREAD

**Issue by wkargul** [golemfactory/yagna#2201]
Goth tests failing again:
[goth-logs_release-v0.11.zip](https://github.com/golemfactory/yagna/files/9504093/goth-logs_release-v0.11.zip)
[goth-logs_release-v0.11 (1).zip](https://github.com/golemfactory/yagna/files/9504109/goth-logs_release-v0.11.1.zip)

What:
- investigate the root cause of failing goth tests

Why:
- nightly tests can't fail

**Comment by pwalski** [comment]
Not relevant after release 0.12
