### ISSUE TITLE
Measure nodes relay forwarding

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2202]
- [ ] decide how to scale the computations to network sizes (target 1k nodes / 5k / 50k)
- [ ] simulate number of Requestor computing tasks
  - [ ] we want to know how many standard requestors will relay survive (reference: current setup on mainnet - 400nodes and 2 blender ARs)

Than:
https://github.com/golemfactory/ya-relay/issues/188

**Comment by kamirr** [comment]
Rewrite of https://github.com/golemfactory/ya-relay/issues/191 made this issue obsolete.
