### ISSUE TITLE
sorted `GET /invoices`

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#2217]
Debit notes (`GET /debit_notes`) are sorted, most recent is first.
Invoices are not sorted, and it would be nice to have such things more consistent.

This is not important for me now, but I think is worth doing one day.

edit (@kamirr):
As I see it, we should:
1. Decide if we want the feature at all
2. Decide whether we just want to sort by date, or provide some querying, like we do when [listing agreements](https://github.com/orgs/golemfactory/projects/30/views/2?filterQuery=assignee%3A%40me&pane=issue&itemId=8066908).
3. Then implement.

**Comment by nieznanysprawiciel** [comment]
related: https://github.com/golemfactory/yagna/issues/3010

**Comment by nieznanysprawiciel** [comment]
Closed in favor of https://github.com/golemfactory/yagna/issues/3010
