### ISSUE TITLE
Revisit all #[allow(clippy::large_enum_variant)] 

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2235]
Relates to https://github.com/golemfactory/yagna/issues/2138

After https://github.com/golemfactory/yagna/pull/2232 merge, there are couple of clippy-allows:
```rust
#[allow(clippy::large_enum_variant)]
```
All of them should be revisited and possibly fixed manually

**Comment by evik42** [comment]
We can always search for `allow(clippy` and improve the code.
