### ISSUE TITLE
Hybrid net provider stops working even though it's indicating all good.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2241]
[User](https://discord.com/channels/684703559954333727/767706268651094036/1025070231938420888) is experiencing that his node stops receiving tasks out of the blue, and when he uses [List offers made by krunch3r](https://github.com/krunch3r76/gc__listoffers) (https://github.com/krunch3r76/gc__listoffers) , then he suddenly can't find his node even though that **golemsp status** indicates that everything is okay. A restart fixes this issue.

> Back home, I check my node which indicates 'is running' but when I check with gc__listoffers.py I don't see my node... So I stopped my docker golem again then restarted by changing env/h to 0, after restarting my docker I can finally see my node in the list of providers with gc_listoffers.
> 
> I'm waiting to see if any tasks come up.
> I seem to lose the connection with the hybrid-mainnet network while if I run golemsp status everything seems to be OK. Strange, isn't it? 
> 
> Well, after 1 hour of operation I check again if my node is visible in the list of providers but it is not. However golemsp status always indicates that my node is working... I understand better why I don't receive any tasks anymore, but why my node disappears from the providers list remains a mystery...
> 
> Lot of WARN in log always ya_relay_client::dispatch 
> Unable to dispatch response => listener is closed

![rn_image_picker_lib_temp_4aa1d947-c6c8-4584-82c6-4860101527d2](https://user-images.githubusercontent.com/33448819/193258215-94fdf608-e718-4518-a182-b57aac09776c.jpeg)

**Comment by MrDarthShoe** [comment]
Moved to `observed` due to lack of logs & subnet config

**Comment by cryptobench** [comment]
Closing issue as it doesn't seem to persist and just seems to be a misunderstanding from the users POV
