### ISSUE TITLE
Hybrid testnet doesn't run tasks but just sits idle receiving proposals.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2266]
I'm trying to start a task on the testnet hybrid network, but it just collects offers from the providers and nothing else is happening. 
![image](https://user-images.githubusercontent.com/33448819/196662449-0a103268-7a7c-4d3c-8bb4-5575c518c440.png)

I'm using `YA_NET_RELAY_HOST=yacn2a.dev.golem.network:7477 yagna service run` and yapapi 0.9.2 / 0.9.3

If I switch to mainnet and run tasks on `hybrid-mainnet` then I instantly start computing on the providers.

[yagna_rCURRENT.log](https://github.com/golemfactory/yagna/files/9819450/yagna_rCURRENT.log)

**Comment by evik42** [comment]
It is fixed with a recent RC.
