### ISSUE TITLE
ExeUnit descriptor - all paths should be relative to descriptor location

### ISSUE THREAD

**Issue by stranger80** [golemfactory/yagna#227]
The exeunit descriptor indicates paths for exeunit "supervisor" and "runtime"
  - the "supervisor" path is relative to "./exe-unit/work" folder (requires two steps up to point to the starting directory)
  - the "runtime" path is relative to "./exe-unit/work/<guid1>/<guid2>" folder (requires four steps up to point to the starting directory)
  The relative paths should be calculated taking descriptor location as root.

**Comment by tworec** [comment]
@stranger80 can you confirm it is fixed?

**Comment by stranger80** [comment]
Looks good, thank you.
