### ISSUE TITLE
Certificates permissions forward compatibility

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#2271]
- [ ] demands from future versions
- [ ] basic permissions for current version

**Comment by pwalski** [comment]
I guess this feature will require changes in `keystore add` command and introduction of `keystore update` (which will use same certificate "id" as `keystore remove`). Additional argument to these commands will be a list of permissions to added/updated certificate. I do not know where to store the permissions (new or an existing config file).
