### ISSUE TITLE
Offers broadcasting problems

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2274]
Why:
- Users are complaining that their Offers with better resources and lower prices aren't chosen by Requestors

What:
- I suspect, there is problem with Offers propagation. Broadcasts are split into multiple chunks and since they reach other Nodes at the same time, some of them are dropped (This is how broadcasting works, to avoid overloading yagna daemon with Offers)

**Comment by cryptobench** [comment]
But isn't yapapi/yajsapi the client responsible for accepting a offer? I don't think there's any issues with offer propagation or atleast not in this case. Yapapi usually just picks the first offer that comes in if its within budget, I believe

**Comment by nieznanysprawiciel** [comment]
There are different strategies depending on Requestor. On mainnet users should be able to pick up tasks at least sometimes. If it isn't happening than I thing broadcasting can be blamed.

I was observing how many Offers I'm getting and how long it takes. And I think problem grew with the newest version.
But this together with other fixes should solve it

**Comment by cryptobench** [comment]
Will this go into an RC?

**Comment by wkargul** [comment]
@cryptobench yes, it will! Moreover I implemented piece of code for solution on this issue https://github.com/golemfactory/yagna/issues/1956 what also might help

**Comment by cryptobench** [comment]
> @cryptobench yes, it will! Moreover I implemented piece of code for solution on this issue #1956 what also might help

Awesome to hear! Very excited to test it out!
