### ISSUE TITLE
General Missing Features

### ISSUE THREAD

**Issue by prekucki** [golemfactory/yagna#2275]
### Lock/Unlock support

- [ ] UC1. Start yagna with lock identity requires pasword.

**Comment by pwalski** [comment]
When default account is locked yagna 0.12 will be waiting until account will get unlocked with following message printed out:
`Daemon cannot start because default account is locked. Unlock it by running 'yagna id unlock'`

What is your @prekucki expected behaviour?

**Comment by kamirr** [comment]
@prekucki Closing due to no response, if you don't agree with the current behavior please reopen.
