### ISSUE TITLE
Provider is stuck when renegotiating "old" payment

### ISSUE THREAD

**Issue by wkargul** [golemfactory/yagna#2289]
One of our users sent bug report:

```
I had a node i shutdown on the testnet which seems to have not been paid, after booting it back up on a later date the node came back and started negotiating with the network.

after a while i started wondering why it wasn't getting any tasks, so i eventually checked the logs and found that it was renegotiating an old payout that must be days old, the node has now been stuck in this state of renegotiating an old payment for 12 hours.

the problem is that while it is renegotiating payment, it refuses to take new tasks.

Logs from the first two hours of the node being online are included.

Best Regards
SGC
```
Logs:
[ya-provider_r2022-11-03_18-15-37.restart-0000.log](https://github.com/golemfactory/yagna/files/9961640/ya-provider_r2022-11-03_18-15-37.restart-0000.log)
[ya-provider_r2022-11-03_18-15-37.log.gz](https://github.com/golemfactory/yagna/files/9961641/ya-provider_r2022-11-03_18-15-37.log.gz)
[yagna_r2022-11-03_18-23-50.log](https://github.com/golemfactory/yagna/files/9961642/yagna_r2022-11-03_18-23-50.log)
[yagna_r2022-11-03_18-23-40.log.gz](https://github.com/golemfactory/yagna/files/9961643/yagna_r2022-11-03_18-23-40.log.gz)
[yagna_r2022-11-03_18-15-36.log.gz](https://github.com/golemfactory/yagna/files/9961644/yagna_r2022-11-03_18-15-36.log.gz)

**Comment by nieznanysprawiciel** [comment]
Low impact and severity. Closing
