### ISSUE TITLE
Fix toolchain version

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2294]
To avoid sudden CI errors after new rust toolchain release, we want to have fixed version on out CI.
Then if needed, we can bump whole toolchain and fix possible issues.

- [ ] Fix versions on CI workflows
- [ ] Include supported version on readme

**Comment by kamirr** [comment]
Besides `ya-client`, I've also pinned `ya-relay` to 1.64.0 in https://github.com/golemfactory/ya-relay/pull/220 (CI broke).
