### ISSUE TITLE
Plan VPN timestamping

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2298]
This will allow for pinpointing bottlenecks hindering the transmission rate.

Timestamps will be necessary, at the very least, around the following subsystems:
* GSB
* VPN
* VM

Possible issues:
* Collecting this debug data should not impact performance considerably.
* Should be possible to disable.

Open questions:
* Actually attach data to packets, or print to logs and then combine them from partaking machines?
    * IMO the second one: simpler and lower overhead

**Comment by kamirr** [comment]
Prepare a macro for tracing packets. Its API should be as follows:
```rust
packet_trace!("location-name", {
    // block of code returning AsRef<[u8]>
    // this data must correspond to the payload of packet being processed
});
```
Alongside it a new non-default feature (`trace-packets`) shall be introduced. Unless its enabled, the macro above must become an empty block. Otherwise, a parseable output consisting of:
1. Location
2. SHA of data

Should be logged to a `packet-trace` log target, under the `TRACE` category. This data will need to be post-processed, considering that logs will be produced by both providers and requestors and will need to be then spliced and displayed in a human-readable form. CSV will be easiest to produce and parse.

This macro shall be invoked in:
1. GSB
2. WebSocket
3. Stack[1]

This list is intentionally imprecise -- pick locations empirically to produce the most informative results.

Another thing to consider is clock synchronization. For log splicing we need precise timestamps, with preferred deviation on the order of 1ms. If this is not achievable, I think we can run the tests locally (provider, requestor and relay on one machine) and still get perfectly usable results.

[1]: VPN packets aren't the only thing passing through the stack, but I think we can just drop irrelevant packets in post-processing.

**Comment by evik42** [comment]
We discussed this plan and agreed on the following:
- we do not really care about network latency (between nodes)
- timestamping can be done when a packet enters into a component and exists, we can measure elapsed time locally
- because of the above 2, clock synchronization is not an issue
- we are not sure if logging to a file would affect measurements too much, can be changed easily in the macro at one place later
