### ISSUE TITLE
`ya-provider presets list` fails if preset doesn't exist

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2299]
- Add active preset manually to `presets.json` file, but without adding preset content
- Run `ya-provider presets list`

Provider is unable to read file. You can't deactivate preset, because file is invalid and command will fail.

**Comment by evik42** [comment]
Created an umbrella issue to check and fix all preset related bugs. https://github.com/golemfactory/yagna/issues/2475
