### ISSUE TITLE
REST api mapping activity_id to agreement_id

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2303]
> I have an activity_id. Is there any way to determine the corresponding agreement_id?

**Comment by johny-b** [comment]
Purpose:

General idea: I think one day we'll want to have separate scripts that:
* create activities
* use activities
* (and manage payments as a third part, but that's irrelevant)

--> `activity_id` should be enough to "use the activity", and using the activity might require e.g. knowing `provider_id` or some other agreement details.
