### ISSUE TITLE
[Requestor enchancement] Loading the same wallet onto multiple requestors causes issues with routing

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2352]
I am deploying an architecture that can spin up multiple requestors horizontally via Docker containers, and i'm facing an issue where if I spin up more than 1 requestor with a wallet that's being loaded on container start, then only the first requestor container will receive offers and spin up my service. If I deploy more than 1 requestor container, then the 2 other containers left will just sit and not collect offers from the network for anything between 2-10 minutes and it gets shutdown by a rather generous container healthcheck i've implemented. If i'm lucky enough to have the 2 containers left pick up any offers and create an agreement, then we start seeing errors like the following: 

```
Task exception was never retrieved
future:  exception=ApiException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yapapi/engine.py", line 892, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "/usr/local/lib/python3.8/site-packages/yapapi/rest/market.py", line 164, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "/usr/local/lib/python3.8/site-packages/ya_market/api_client.py", line 205, in __call_api
    raise e
  File "/usr/local/lib/python3.8/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/ya_market/rest.py", line 268, in POST
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/ya_market/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: 
HTTP response body: {"message":"Failed to send response for Proposal [R-acfc7073dc615edab98362f5cbd88ffa397fd17ce32ef84a7422a396e40ae6ed]. Error: Countering Proposal [R-b46630e424286ba61a1cc551a100783fb4ebad12302bc113b8191399e4c7bcd7] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request timed out after 3000 ms.."}


```

```
[2022-12-01T21:02:18.165+0000 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'g505sp2.h' (0x4517b78057c702a3a4393e97d0b9baef5c88ba90)
Task exception was never retrieved
future:  exception=ApiException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yapapi/engine.py", line 892, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "/usr/local/lib/python3.8/site-packages/yapapi/rest/market.py", line 164, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "/usr/local/lib/python3.8/site-packages/ya_market/api_client.py", line 205, in __call_api
    raise e
  File "/usr/local/lib/python3.8/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/ya_market/rest.py", line 268, in POST
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/ya_market/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: 
HTTP response body: {"message":"Failed to send response for Proposal [R-8e67c72ea43c411dd612fa5d6be6457f299a9f69956e6be553e7531ead2dc33d]. Error: Countering Proposal [R-0ba29c417889eba8e33f7f6c6b1c1b07b993b7ebbaac7ac38242b5ca3274b296] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 401.."}
```

Using the same wallet address on all nodes will cause all the nodes to have the same ID on the network, which presumeably is the cause of this issue. The reason for loading the same wallet up on each requestor is to have a service that i can scale horizontally both ways and not having to monitor multiple wallets for funds. 

If I should solve this issue right now, then I would have to let yagna generate a new wallet address for each requestor container, then create some service that monitors funds for each requestor container and top up each one up accordingly to their needs. This quickly gets very complicated and I could even result in loss of funds if the requestor container doesn't properly transfer out the funds when being shut down.

**Comment by evik42** [comment]
There are at least two problems we need to solve:
- Routing
- Payments

Routing can be solved by the requestors having a node id that is not the wallet address. So it can be unique on the network.

Payments are a problem when two wallet tries to send in payments from the same address as they might lose track of the actual nonce. Some transactions would not be accepted by the network for invalid nonce.
This could be solved by having a separate yagna instance (called it Yagna as a service in the diagram) which controls the primary key for the wallet address and creates all payment transactions.
In this setup the requestor would not need to have the private key to the wallet. It would somehow authenticate to the yagna as a service instance and send in payment requests based on the debit notes and invoices it receives. The yagna as a service instance would facilitate creating and managing the transaction on the blockchain and would send back a transaction identifier to the requestor. The requestor could use this id to query the yagna as a service node for transaction status or (if the id is connected to the blockchain) it could query the blockchain directly.

![Image](https://user-images.githubusercontent.com/4715833/207379699-1051c3c9-819c-4ec5-ab8b-ce970dd8f425.jpg)

**Comment by cryptobench** [comment]
didn't notice the response backthen, sorry! But yes, that could be one way to solve the issue.

I just want to report that Maugnobert is facing the same issue with his requestors, so I think i'm not the only requestors expecting to just be able to horizontally scale my requestor containers

<img width="944" alt="image" src="https://user-images.githubusercontent.com/33448819/210176378-e2c6c709-ce7c-4012-bfc0-663b89ccc945.png">

**Comment by cryptobench** [comment]
Bumping this one as #2405 is causing a very troublesome experience when spinning up multiple requestors with different wallets. I can make it work for mainnet (own solution), but I would like to complete my testing using testnet since its free.

**Comment by cryptobench** [comment]
Closing as i'm opening a discussion instead https://github.com/golemfactory/yagna/discussions/3006
