### ISSUE TITLE
[Requestor enchancement] Advertise network speeds and geolocation in the offer templates on the network

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2357]
With the introduction of outbound networking + SocketProxy and in the future inbound networking, I think it's worth considering adding network speeds and geolocation to the offers advertised by providers on the network.

**Why?**

 1 ) If I am to spawn services on a provider that might be pulling a lot of bandwidth, then as a requestor I would like to select the provider machines that I know has the speeds required to meet my demand. We have users in our discord that are providers and have mentioned they have 10 mbit speeds, and in a lot of case this might bottleneck a lot of things because there is a high chance that not only is the user and possibly other family members are using the providers connection at the same time as you would (the requestor). 

2) Right now if I want to spawn services on a provider its a lottery for me in regards to knowing how fast their network speeds are. This can heavily bottleneck my service if its slow and it will be painful to debug for the requestors because either we have to launch some benchmarking service on the provider to confirm (which also == $$$$$) or the requestor might sit and think _"wtf is wrong with my service? It works fine locally but once it starts on golem it doesn't respond or is super slow... this platform sucks I will find something else"_ **OR** third, the requestor will try more providers and on some it works perfectly fine and others it doesn't.... which is even more confusing

We already know that debugging tasks/services running on top of Golem is hard, but not knowing the network speeds of the provider can introduce even more pain points for requestors using our platform. 

It's a vital piece of information now that we're stepping into the dApp territory. Golem was mainly batch processing backthen which meant that only cores, disk and memory were relevant for requestors, but times are changing and now network information needs to be available to provide a satisfiable experience when working with services on Golem.

**Comment by evik42** [comment]
I think this goes hand-in-hand with limiting the bandwidth the provider can use and also pricing based on traffic.

**Comment by cryptobench** [comment]
> I think this goes hand-in-hand with limiting the bandwidth the provider can use and also pricing based on traffic.

Yes, I wouldn't mind having these possibilities too.

**Comment by konradbjk** [comment]
AWS and Azure are limiting the network bandwidth. It makes sense we would do it too. We could potentially add another point on an offer/market strategy, that states the allocated bandwidth. Ay implementation would be better than no implementation (like now). 

It will be buggy because the provider might decide to download a 1TB file out of a sudden, and we will need to be fighting for the bandwidth, though it is already pretty well resolved by torrents. We can try to mimic this.

**Comment by cryptobench** [comment]
This is now more important than ever if Golem is going to get requestors. I was talking with lawyers about GolemGrid and the fact that I cannot decide which location in the world the provider is, gives me big legal obstacles. I want to obey GDPR and not let any personal data leave EU, but without being able to see providers geolocation, then this is a major blocker for commercial usage.

**Comment by cryptobench** [comment]
Closing because i'm moving this to discussion https://github.com/golemfactory/yagna/discussions/3002
