### ISSUE TITLE
[Requestor enchancement] Add some kind of resource utilization monitoring for ExeUnits

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2359]
It would be nice as a requestor spawning services to know the resource utilization on the providers VM running my task.

**Why?**

1) It would allow me to create some autoscaling group based on the service's current utilization
2) It would make it easier to debug if something is running slowly on the provider
3) If you're a middleman service then it makes it easier for the service to present the customers current utilization of the rented product.

**Comment by evik42** [comment]
You can do it with any unix tool that you run in the VM, for example running `vmstat` show this:
```
[2022-12-05T14:38:21.207+0100 INFO yapapi.summary] [Job 1] Task started on provider 'prov', task data: vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 4001132      0  10520    0    0   251     0  624  795  0 19 81  0  0
```

**Comment by cryptobench** [comment]
I have thought about the idea of installing a dependency to the VM that will allow me to do this, but I don't think it's the solution. Software like Docker, Podman, Containerd can already see the containers resource utilization without adding an extra dependency to the container itself. I would expect to be able to do the same with Yagna.

**Comment by evik42** [comment]
In the meantime you can use something inside the VM. The upside is that if you have resource monitoring inside then it would work the same way in vm runtime and also in docker or other containerized environment. This might help in development/testing of the payload.

**Comment by evik42** [comment]
CPU load can be deducted from available usage counters the provider is sending.
Counters might be extended.

**Comment by cryptobench** [comment]
Closing as i'm opening a discussion instead https://github.com/golemfactory/yagna/discussions/3004
