### ISSUE TITLE
Negotiations protocol design

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2368]
We want to have negotiations protocol approved as GAP for whole Outbound v 2.0.
We want to support two Rules:
-  Outbound for All
-  Partners

Protocol should be compatible with KYC Rule.
Protocol should be also extendable for future requirements for Outbound.

**Comment by evik42** [comment]
Modified GAP-25 (Golem Certificate structure) https://docs.google.com/document/d/1oHM_SxwjbAcucCkcP4aeawS3skNdOFgygbdLPmkH9MA/

**Comment by evik42** [comment]
JSON Schema document: https://docs.google.com/document/d/1CMt6EDpAajVkwxow2H9sX9rjkLGniiCe53GsepO4Ej4/edit#

**Comment by evik42** [comment]
Golem certificate structure in JSON: https://github.com/golemfactory/golem-architecture/tree/evik/golem-certificates-json
Work in progress
