### ISSUE TITLE
Prepare demo for "Outbound for all"

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2369]
Scenarios for demo of Milestone 1: "Outbound for all"
1. 
- Setup Provider with "Outbound for all" Rule off  & Outbound feature turned on
- Setup Requestor with no certs
- Setup Task with different domain than inside whitelist
- Expect that task won't be scheduled
2. 
- Setup Provider with "Outbound for all" Rule on  & Outbound feature turned on
- Setup Requestor with no certs
- Setup Task with different domain than inside whitelist
- Expect that task will successfully complete
3. 
- Setup Provider with "Outbound for all" Rule on & Outbound feature turned off
- Setup Requestor with no certs
- Setup Task with different domain than inside whitelist
- Expect that task won't be scheduled

**Comment by nieznanysprawiciel** [comment]
I'm wondering if this could be goth tests?

**Comment by MrDarthShoe** [comment]
> I'm wondering if this could be goth tests?

From what I see- case when task is successful can be written in Goth. I am not sure if we are able to make assertions on errors that negotiations didn't succeed
