### ISSUE TITLE
Yagna 0.12.0 higher memory usage

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#2375]
This started happening after release 0.12.0 (it didn't occur on any earlier RC). Here's an example from one of our machines, but it's the same on all of them.

The green area shows the actual memory used. It's not much in absolute values (if you consider 2G "not much"), but it's a significant change, relative to previous measurements.
![mem1](https://user-images.githubusercontent.com/220752/206409556-c5a93f4f-16e5-4812-9291-f94f81ef6176.png)

The blue line shows the "commited" memory, aka. the "virtual" memory allocated by applications. It's like doing a lot of `malloc`, but not writing anything there.
![mem2](https://user-images.githubusercontent.com/220752/206410144-2a3a4015-f44a-42d6-8482-15168c0fb6f0.png)

It's also interesting, that it always rises to a certain level and then stops.

**Comment by evik42** [comment]
@etam These graphs are from provider nodes?

**Comment by etam** [comment]
Yes. But with requestors I get the same. And I'm sure it's yagna, not ya-provider nor anything else.

**Comment by evik42** [comment]
Overcommitting is not a problem on Linux but will cause problems on other operating systems (like Windows).

**Comment by nieznanysprawiciel** [comment]
This should be fixed by https://github.com/golemfactory/yagna/issues/1985
