### ISSUE TITLE
[Requestor enchancement] Improve reliability of the faucet

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#2405]
The current testnet is on Rinkeby, but that got deprecated 3 months ago in October 2022. It is not possible to explore network activity on the rinkeby etherscan anymore, so as a requestor I cannot see what's happening on the chain in any easy manner.

Next to that is the fact that the faucet is pretty unreliable in general. Most of the funding requests end up returning `deadline has elapsed` and you have to implement some retry logic to keep trying until it **hopefully** goes through.

In this case I thought that the faucet might be out of funds, so I collected some ETH from one of the only rinkeby faucets that are left on the internet and sent the funds to our faucet. To my surprise, the faucet did still not work.

IMO the testnet faucet **has** to be one of our most stable components in our ecosystem, as this is the entrypoint for new requestors which the network is lacking already. 

![image](https://user-images.githubusercontent.com/33448819/211117346-8d2ec806-ffd2-4816-8d9f-bf2f7f95d0b0.png)

**Comment by evik42** [comment]
@scx1332 could you please take a look?
