### ISSUE TITLE
Auto add specific rules for certs during installation [2/2]

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2433]
**User Story:**

As a provider
I want to have default golem certificates & rules set accordingly
So that I don't need to do it manually by myself

**Acceptance Criteria:**

1. Audited payload cert + rule
2. Partner cert + rule

**Testability:**
1. Manual tests
2. Testing session

**Prerequisites**

- https://github.com/golemfactory/yagna/issues/2605
- https://github.com/golemfactory/yagna/issues/2561. (blocked by not having certificates with permissions.)

**Comment by evik42** [comment]
depends on #2561
