### ISSUE TITLE
Partner rule: Implement certificate library

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2443]
Create a lib which:
1. Validates permission tree
2. Validates signatures
3. Extracts needed data from `node.json`

This task is not about switching library in keystore

**Comment by MrDarthShoe** [comment]
It is WIP on https://github.com/golemfactory/golem-certificate repo

**Comment by MrDarthShoe** [comment]
Done in https://github.com/golemfactory/golem-certificate

**Comment by pwalski** [comment]
Done
