### ISSUE TITLE
Encryption design

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2444]
This task is about e2e encryption communication between nodes.

Results:
1. We should know how feature will look like (collect requirements from @nieznanysprawiciel )
2. ~List of implementation tasks for outbound encryption~
3. A document describing:
    * possible solutions
    * feasaibility estimation of each of them
    * list relevant libraries, choose the most suitable one 
    * pros / cons of each solution

**Comment by nieznanysprawiciel** [comment]
Requirements:
- e2e encryption between Nodes
    - Use symmetric encryption
        - To determine symmetric key, either we need to exchange secret encrypted with asymmetric encryption
        - or derive secret from public/private key pair between Nodes
    - Should we change key from time to time?
- Each identity used by yagna Node should be challenged (we need to prove that Node is in possession of private key)
    - But we should use only one symmetric key derived from default identity for whole traffic
    - But think if there are any negative consequences?
- Use existing library for encryption
    - Make sure it is largely used and supported

What should be encrypted:
- Each GSB message, which is using reliable transport
- Broadcasts can be public, so we may require only attaching signatures
    - Note: UDP frame size is limited, so this decreases amount of content we can broadcast in one chunk
    - If it is easier to do full encryption than it is acceptable
- What to do with VPN traffic? Should it be responsibility of networking layer or code in VMs should establish secure transport itself
    - Encrypting whole traffic means that we are encrypting TCP acknowledges (may lower performance)
    - Not encrypting may allow attacks on TCP layer (This means that we should probably encrypt everything)
    - Find out what are existing solutions doing?
    - Maybe we could give user a choice during network creation?

**Comment by kamirr** [comment]
Split into a smaller task: https://github.com/golemfactory/yagna/issues/2540

**Comment by jalas167** [comment]
Implemented in: https://github.com/golemfactory/ya-relay/pull/333
