### ISSUE TITLE
Import rule applies to single cert in chain

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2457]
During `import-cert` feature when adding new rule, it should be applied only to leaf of certificate chain.

Example implementation can be found in deprecated provider permissions.

[OPTIONAL]
add CMD line flag to apply rule for `whole-chain`

Testing:
- modify existing cli tests for "partner rule with import cert"

**Comment by pwalski** [comment]
Clarification:
Term "leaf cert" and `whole-chain` flag makes sense only in case of x509 certificate chains.
Golem certificate is always a "leaf cert".
Feature `import-cert` should be supported for both `rule set outbound partner` and `rule set outbound audited-payload`.
X509 certificates are supported only in case of `audited-payload`.

ToDo/Missing:
- [ ] Add support of `import-cert` for `audited-payload`. There is a task for it https://github.com/golemfactory/yagna/issues/2429 ?
  - [ ] Apply "leaf cert" logic to x509 certificates imported using `rule set outbound audited-payload import-cert`
  - [ ] Add `whole-chain` param to `rule set outbound audited-payload import-cert`.
- [ ] Make impossible to run `rule set outbound partner import-cert` on x509 cert.
- [ ] Make impossible to run `rule set outbound partner cert-id` on x509 cert id.
  - [ ] Make Golem certs and x509 certs distinguishable on `keystore list` output (some `type` column or sth). It needs to be done to make clear why `partner` rule cannot be set on x509. It also needs to be done before Keystore CLI tests https://github.com/golemfactory/yagna/issues/2483

**Comment by pwalski** [comment]
After discussing the task I will:
- Keep the code for applying rule only to leaf X509 certificate so it later will be used in Audited Payload (will be later used in this task https://github.com/golemfactory/yagna/issues/2429)
- Make impossible to run `rule set outbound partner import-cert` on x509 cert (Info message explaining X509 is not supported).
- Make impossible to run `rule set outbound partner cert-id` on x509 cert id (Info message explaining X509 is not supported).
- Add `Type` column for `keystore list` with `Golem` or `X.509` value so it will be clear which `cert-id` can be used in  `rule set outbound partner cert-id`.
