### ISSUE TITLE
Error of relay Server to forward packets

### ISSUE THREAD

**Issue by cmdntd** [golemfactory/yagna#2474]
I have this error:
(Wating for more than 48h, but no task received)
```
node_1  | 2023-02-25T06:41:47.278964275Z [2023-02-25T13:41:47.278+0700 INFO  ya_relay_client::session_manager] All attempts to establish direct session with node [0x4bedd871d3ec1907227ead1adc366e4d5d6b76c5] failed
node_1  | 2023-02-25T06:41:47.279017842Z [2023-02-25T13:41:47.278+0700 INFO  ya_relay_client::session_manager] Using relay Server to forward packets to [0x4bedd871d3ec1907227ead1adc366e4d5d6b76c5] (slot 2043)
```

**Comment by cryptobench** [comment]
@cmdntd This is most likely related to the pricing of your provider. I think the network sits at around 0.008 cpu/h pricing right now, so if you're using the default then your node would be very expensive and thus most likely not get picked up by a requestor. If you can tell me the pricing of your node currently, then we can investigate from there.

Also I suggest you join our Discord at https://chat.golem.network as we sit ready there almost 24/7 including community members that are interested in helping.

**Comment by cmdntd** [comment]
@cryptobench you're right. That is a under price issue.
Now it is ok at 0.006 or 0.005, although it is rather low one.
