### ISSUE TITLE
provider: misinterpretation of cpu_threads in hardware.json

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#2491]
## What?
Determine how to fix and implement.

## Original
Yagna version: 0.12.0

`hardware.json` has only one option for limiting advertised cpu, called `cpu_threads`. According to a comment (https://github.com/golemfactory/yagna/blob/v0.12.0/agent/provider/src/hardware.rs#L63) it should set "Number of CPU logical cores".

Actual result:
There are 2 properties:
- `golem.inf.cpu.threads`, which usually has value "2", because it shows that the CPU has hyperthreading.
- `golem.inf.cpu.cores`, which shows real cores.

(The number of logical cores is `golem.inf.cpu.cores`*`golem.inf.cpu.threads`.)

Bug is here: `cpu_threads` from `hardware.json` overwrites `golem.inf.cpu.threads`.

**Comment by johny-b** [comment]
As a consequence, our rinkeby providers are advertised on the market as having 4/6/8 cores when they have 1 or 2.
I think this might be pretty important, because someone might wonder why supoosed 8 cores are so slow and decide that this is e.g. `yagna` fault.

**Comment by etam** [comment]
Solution proposals:
1. Don't expose threads and cores in properties. Make it one value.
2. Add `cpu_cores` to `hardware.json`.
