### ISSUE TITLE
Specific rejection message when ya-provider's keystore is empty

### ISSUE THREAD

**Issue by pwalski** [golemfactory/yagna#2520]
Problem:
Demands containing signed Manifest are rejected with message `'failed to verify manifest signature: Invalid certificate'` when `ya-provider`'s keystore is empty. 

Todo:
There should be some specific message indicating case when certificate cannot be verified because `ya-provider`'s keystore is empty.

Why:
It will make diagnosing such cases much easier. Such situation might happen because certificates are downloaded by `ya-installer`, so if `ya-provider` is installed in some different way it may end up with empty `cert-dir`.

**Comment by golmek** [comment]
Not critical path
