### ISSUE TITLE
Problem with outbound connection to addresses which returns different IP for each DNS query

### ISSUE THREAD

**Issue by stan7123** [golemfactory/yagna#2539]
I'm encountering problems with connecting to the external whitelisted domain which has multiple IP addresses (accounts.google.com).
It sometimes works correctly, but it usually doesn't. The IP is blocked, and the target IP is changing randomly or rotating. It looks like it depends on what IP is resolved in the end for the domain in VM.

domain_whitelist.json on the provider:
```
...
{
      "domain": "accounts.google.com",
      "match": "strict"
},
...
```

manifest.json:
```
"net": {
      "inet": {
        "out": {
          "protocols": ["https"],
          "urls": [
            "https://files.pythonhosted.org",
            "https://pypi.org",
            "https://accounts.google.com",
            "https://www.googleapis.com",
            "https://oauth2.googleapis.com"           
          ]
        }
      }
    }
```

I'm running more complicated code but the following call is enough to reproduce:
```
curl https://accounts.google.com
```

In the provider's exe-unit logs:
```
...
[2023-04-17T21:33:09.578+0200 DEBUG ya_exe_unit::network::inet] [inet] proxy conn: bind 216.58.208.205:443 (Tcp) and 10.42.42.2:56812
[2023-04-17T21:33:09.578+0200 DEBUG ya_exe_unit::network::inet] [inet] connect to SocketDesc { protocol: Tcp, local: Ip(Endpoint { addr: Ipv4(Address([216, 58, 208, 205])), port: 443 }), remote: Ip(Endpoint { addr: Ipv4(Address([10, 42, 42, 2])), port: 56812 }) }
[2023-04-17T21:33:09.578+0200 DEBUG ya_exe_unit::network::inet] [inet] router: connection error: URL validation error: address not allowed: 216.58.208.205:443 (Tcp)
...
```

**Comment by stan7123** [comment]
https://github.com/golemfactory/yagna/blob/5827a6549d14aa6f2c5cc481e20f08f64fccbc9a/utils/networking/src/resolver.rs#L57

It looks like exe-unit is resolving IPs against Google's DNS. Google is returning different addresses for each request probably as a result of load balancing strategy.

`dig @8.8.8.8 accounts.google.com`

**Comment by evik42** [comment]
Currently `yagna` does one query against a domain and allows all IPs presented in the response.
The usual way of doing this is that a request returns multiple IPs for the same domain and it is up to the client to select one it likes.
Example:
```
$ dig @8.8.8.8 microsoft.com
...
;; ANSWER SECTION:
microsoft.com.		1531	IN	A	20.112.52.29
microsoft.com.		1531	IN	A	20.81.111.85
microsoft.com.		1531	IN	A	20.84.181.62
microsoft.com.		1531	IN	A	20.103.85.33
microsoft.com.		1531	IN	A	20.53.203.50
```

Google does it differently and it replies with a single IP each time which might be different than the one in the previous response. They can do more optimizations (force client load balancing, location based response) but it is not compatible with ip based filtering.

**Comment by nieznanysprawiciel** [comment]
That's a difficult problem to solve and we need to find a proper solution which we don't have now.

**Comment by stan7123** [comment]
I tried other DNS (Vectra) and it seems to return consistent results every time.
`dig @78.88.29.65 accounts.google.com`

The only workaround for now which I found is to set static address in `/etc/hosts` for problematic addresses on the provider host as well as inside VM operating system. Resolver is doing a lookup there first before querying DNS server.

**Comment by evik42** [comment]
One other possible solution to check if ECS (edns-client-subnet) would solve the issue.
Using ECS enabled cloud9 DNS server responds with the same IP address for `accounts.google.com`.
Cloudflare dns does not support ECS because it is privacy focused and does not send client related information to authoritative nameservers.
So the use of ECS might create privacy issues.

**Comment by pwalski** [comment]
Issue will be further investigated in https://github.com/golemfactory/yagna/issues/2553

**Comment by stan7123** [comment]
I want to report that I noticed a similar problem with `huggingface.co` and `cdn-lfs.huggingface.co` domains.
The DNS entries return static 4 addresses for both. But without the workaround (setting static IP in `/etc/hosts` on provider and in VM), I was getting timeouts and occasional successful connections. Please also make sure that the feature of opening all the IPs from the answer section works.

```
dig @8.8.8.8 huggingface.co
...
;; ANSWER SECTION:
huggingface.co.		51	IN	A	108.138.51.21
huggingface.co.		51	IN	A	108.138.51.26
huggingface.co.		51	IN	A	108.138.51.41
huggingface.co.		51	IN	A	108.138.51.8
```

```
dig @8.8.8.8 cdn-lfs.huggingface.co
...
;; ANSWER SECTION:
cdn-lfs.huggingface.co.	28	IN	CNAME	d2243ylfu57tc6.cloudfront.net.
d2243ylfu57tc6.cloudfront.net. 44 IN	A	18.244.102.81
d2243ylfu57tc6.cloudfront.net. 44 IN	A	18.244.102.76
d2243ylfu57tc6.cloudfront.net. 44 IN	A	18.244.102.9
d2243ylfu57tc6.cloudfront.net. 44 IN	A	18.244.102.114
```

**Comment by nieznanysprawiciel** [comment]
Done in: https://github.com/golemfactory/yagna/pull/2819

**Comment by evik42** [comment]
If I am not mistaken this change adds another dns server to query, the one that is running on stable-dns.dev.golem.network.
As the below queries show, it returned a different IP for `accounts google.com` for another request that was fired 7 second after the first.
The test `test_fail_resolver` tests that the dns returns the same address for `accounts.google.com` and tests for 75 seconds while that dns entry has a TTL of 300 seconds so the test most likely succeeds but does not validate anything.

```
$ dig accounts.google.com @stable-dns.dev.golem.network

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> accounts.google.com @stable-dns.dev.golem.network
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46288
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;accounts.google.com.           IN      A

;; ANSWER SECTION:
accounts.google.com.    4       IN      A       74.125.193.84

;; Query time: 50 msec
;; SERVER: 52.49.64.43#53(stable-dns.dev.golem.network) (UDP)
;; WHEN: Tue Oct 10 17:59:41 CEST 2023
;; MSG SIZE  rcvd: 64
```
7 seconds later:
```
$ dig accounts.google.com @stable-dns.dev.golem.network

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> accounts.google.com @stable-dns.dev.golem.network
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26117
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;accounts.google.com.           IN      A

;; ANSWER SECTION:
accounts.google.com.    300     IN      A       172.253.116.84

;; Query time: 79 msec
;; SERVER: 52.49.64.43#53(stable-dns.dev.golem.network) (UDP)
;; WHEN: Tue Oct 10 17:59:48 CEST 2023
;; MSG SIZE  rcvd: 64
```
