### ISSUE TITLE
exe-unit outbound integration testing

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2541]
## Goal
Ensure that outbound actually works on different loading scenarios

## What
Create a task that loads the network according to predefined characterstics
- [x] Troughput (upload at some speed and see if the exe-unit keeps up)
- [x] Many small requests
- [x] Request to many domains
- [x] Sporadically stream as much as possible
- [x] Ensure data integrity by using the `tcpbin.com:4242` echo server
- [x] Run `speedtest-cli` just to see if it passes -- it's a bit of mixed load with pinging multiple servers and then heavy bidirectional IO.

**Comment by pwalski** [comment]
Related to https://github.com/golemfactory/yagna/issues/2545

**Comment by kamirr** [comment]
1) [ ] Outbound fix
    - [ ] https://github.com/golemfactory/yagna/issues/2541
    - [x] swarm pinger + SDK team confirmation (on updated `testnet`)
      - Result: `dapp-experiments/03_apipinger` run on testnet (default 1000 requests with 1s gap):
          ```
          Number of errors: 0
          Number of oks: 1010
          Number of oks under 3s: 1008
          Number of oks under 1s: 1004
          Number of oks under 0.5s: 938
          Number of oks under 0.3s: 650
          Number of oks under 0.2s: 648
          Number of oks under 0.15s: 276
          Number of oks under 0.1s: 0
          ```
          First few requests are always slow - between 05-5s.

**Comment by kamirr** [comment]
As for `Sporadically stream as much as possible`:

I'm writing 1MiB and then sleeping for a minute for 1m, 4 times in total. The issue is that there's a timeout at the beginning right as the second write starts. Investigating whether it's a bug in outbound or the test service `tcpbin.com:4242` drops me (the thing is the connection doesn't close as you'd expect if the server disconnects).
