### ISSUE TITLE
Testing: extended tests in the certificates helper tool

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2542]
Have another person (not author / reviewer) look at the code of the helper tool and try to find new ways to break it.

**Comment by pwalski** [comment]
1. Help requires comments:
```
golem-certificate-cli --help
Usage: golem-certificate-cli <COMMAND>

Commands:
  create-key-pair
  fingerprint
  self-sign-certificate
  sign
  verify
  ui
  help                   Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

1.1 What `fingerprint` do?
```
golem-certificate-cli fingerprint --help
Usage: golem-certificate-cli fingerprint <INPUT_FILE_PATH>

Arguments:
  <INPUT_FILE_PATH>
```
 User will expect it will calculate checksum of given file, but it expects something different:
```
golem-certificate-cli fingerprint README.md
Error: expected value at line 1 column 1
```
?!

**Comment by pwalski** [comment]
2. ` golem-certificate-cli self-sign-certificate golem.cert.not_expired.json golem.key` overwrites file when `golem.cert.not_expired.signed.json` already exists. Also it is not obvious that `golem.cert.not_expired.signed.json` is an output.

**Comment by pwalski** [comment]
3. Some time ago I reported issue with ability to sign expired certificate, and use it issue another certificate
https://github.com/golemfactory/golem-certificate/issues/23

**Comment by pwalski** [comment]
4. `golem-certificate-cli ui` node descriptor sign wizard expects me to select some existing file to overwrite.
It does not allow me to type file name I want it to create.

**Comment by pwalski** [comment]
6. When creating new certificate I placed private key as a pub key and when I went into signing phase it did not let me to `Sign` (which is expected), but it did not let me to `Cancel` (which was not expected). It does not let me out from this view.

![Image](https://github.com/golemfactory/yagna/assets/4924911/533d771c-9d30-4c83-886c-b9819edbf432)

**Comment by pwalski** [comment]
7. Showing error message `Missing signing key or certificate` is just lazy. You know which one is missing. Also it is misleading. Value `None` does not indicate this field value is incorrect

![Image](https://github.com/golemfactory/yagna/assets/4924911/6f26e43b-0a98-464d-93d2-1d7407cd3855)

.

**Comment by pwalski** [comment]
8. Nitpicking. In previous view I did NOT selected `sign certificate` permission. This view allows me to select `self-signed`, and when I try to do so it complains that `Certificate signing is not permitted`. Maybe it should not let me select `self-signed` in such case?

![Image](https://github.com/golemfactory/yagna/assets/4924911/402410ee-edf3-43f0-8af6-75f04dc43ae5)

**Comment by pwalski** [comment]
9. It is an issue with schema in GAP-25 but as a result helper allows to create certificate with fields containing only whitespace, url like `protocol://` and expired validity period valid for 0 seconds.
```
{
  "$schema": "https://golem.network/schemas/v1/certificate.schema.json",
  "certificate": {
    "keyUsage": [
      "signCertificate"
    ],
    "permissions": {
      "outbound": {
        "urls": [
          "protocol://"
        ]
      }
    },
    "publicKey": {
      "algorithm": "EdDSA",
      "key": "ea88cfd72621cc9f1b5f9652e7aaa609f99e56e5a157f434fa2a931c3826bbd4",
      "parameters": {
        "scheme": "Ed25519"
      }
    },
    "subject": {
      "displayName": " ",
      "contact": {
        "email": " "
      }
    },
    "validityPeriod": {
      "notBefore": "2003-06-14T00:00:00Z",
      "notAfter": "2003-06-14T00:00:00Z"
    }
  },
  "signature": {
    "algorithm": {
      "hash": "sha512",
      "encryption": "EdDSA"
    },
    "value": "593ea9241c5a48815d424d7a1aa62a04cdb44dec0c16575fa7e2958973b158692936167520d2bd6192845cafe8b2c0936e08d3325dd94f306f9df4983cffe202",
    "signer": "self"
  }
}
```

**Comment by pwalski** [comment]
10. Helper allows me to edit not after/before fields which are values like this: `2023-06-14 00:00:00 UTC`. It does allow to edit `UTC` part but the only format it accepts is `UTC`, so it always has to be there. 

Maybe `UTC` part of the date value should not be editable? 

GAP defines this field only as a `"format": "date-time"`. Helper UI accepting only `UTC` is an limitation, but it is fine.

**Comment by evik42** [comment]
> 1.1 What `fingerprint` do?
> 
> ```
> golem-certificate-cli fingerprint --help
> Usage: golem-certificate-cli fingerprint <INPUT_FILE_PATH>
> 
> Arguments:
>   <INPUT_FILE_PATH>
> ```
> 
> User will expect it calculates checksum of given file, but it expects something different:
> 
> ```
> golem-certificate-cli fingerprint README.md
> Error: expected value at line 1 column 1
> ```
> 
> ?!

I generates the fingerprint of the signed part of a certificate or node-descriptor. Used it for testing, you can make it hidden as it has not much use for general users.

**Comment by evik42** [comment]
> 5. `golem-certificate-cli ui` panics when it needs to scroll. Happens on tmux and on native terminal. Both on zsh and bash. Works only when window is high enough so scrolling is not necessary.
> 
>  tmux.2023-06-14.21-20-35.mp4

Yeah this happens in the certificate/node-descriptor editor because as of now those cannot scroll and the cursor is out of screen.

**Comment by evik42** [comment]
> 9. It is an issue with schema in GAP-25 but as a result helper allows to create certificate with fields containing only whitespace, url like `protocol://` (which is validated as an URI) and expired validity period valid for 0 seconds.
> 
> ```
> {
>   "$schema": "https://golem.network/schemas/v1/certificate.schema.json",
>   "certificate": {
>     "keyUsage": [
>       "signCertificate"
>     ],
>     "permissions": {
>       "outbound": {
>         "urls": [
>           "protocol://"
>         ]
>       }
>     },
>     "publicKey": {
>       "algorithm": "EdDSA",
>       "key": "ea88cfd72621cc9f1b5f9652e7aaa609f99e56e5a157f434fa2a931c3826bbd4",
>       "parameters": {
>         "scheme": "Ed25519"
>       }
>     },
>     "subject": {
>       "displayName": " ",
>       "contact": {
>         "email": " "
>       }
>     },
>     "validityPeriod": {
>       "notBefore": "2003-06-14T00:00:00Z",
>       "notAfter": "2003-06-14T00:00:00Z"
>     }
>   },
>   "signature": {
>     "algorithm": {
>       "hash": "sha512",
>       "encryption": "EdDSA"
>     },
>     "value": "593ea9241c5a48815d424d7a1aa62a04cdb44dec0c16575fa7e2958973b158692936167520d2bd6192845cafe8b2c0936e08d3325dd94f306f9df4983cffe202",
>     "signer": "self"
>   }
> }
> ```
> 
> Helper should at least trim values to not sign docs with 'empty' fields.

Unfortunately JSON schema cannot define logical connections between properties and the format property is optionally supported. Even x509 spec does not specify that the `notAfter` timestamp would need to be after the `notBefore` timstamp. 

So these rely on common sense of the user.

For protocol, this is exactly the case with manifests, anything that can be parsed into an URL is accepted, the GAP does not restrict the URL format either. When reading up the URLs the validator will ignore unknown protocols, or other malformed urls that it cannot resolve to IPs. (The examples in the GAP even contain path parts which is completely ignored by the IP filtering.)

**Comment by evik42** [comment]
Great findings! I think 5 and 6 are something that should be addressed sooner rather than later. The others are nice to haves.

**Comment by evik42** [comment]
> 6. When creating new certificate I placed private key as a pub key and when I went into signing phase it did not let me to `Sign` (which is expected), but it did not let me to `Cancel` (which was not expected). It does not let me out from this view when its field values are invalid.
> 
> ![Image](https://user-images.githubusercontent.com/4924911/245914632-533d771c-9d30-4c83-886c-b9819edbf432.png)

I think Esc works.

**Comment by pwalski** [comment]
> I think Esc works.

Yes, it does. Still I created an issue for this `Cancel` button problem https://github.com/golemfactory/golem-certificate/issues/27

**Comment by pwalski** [comment]
> Unfortunately JSON schema cannot define logical connections between properties and the format property is optionally supported. Even x509 spec does not specify that the `notAfter` timestamp would need to be after the `notBefore` timstamp.

Yes @evik42 , but there is nothing stopping us from trimming fields when generating/signing new certificate.
It will require some work, but I think we could have a different validation when we verify document and a different one when we generate/sign it.
When verifying document we should check it only against schema.
When signing/generating a new document we could e.g. trim all fields and then let it fail on schema verification because of empty fields. Alternatively we could have some additional validation before checking against schema?

> For protocol, this is exactly the case with manifests, anything that can be parsed into an URL is accepted, the GAP does not restrict the URL format either. When reading up the URLs the validator will ignore unknown protocols, or other malformed urls that it cannot resolve to IPs. (The examples in the GAP even contain path parts which is completely ignored by the IP filtering.)

Same case. Maybe we should pass `protocol://` when we verify document against schema, but maybe we should not allow user to add such URI when creating/signing new certificate in golem-certificate-cli ?
