### ISSUE TITLE
Cherry pick changes for the 0.12.1

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2544]
* [x] outbound fix (https://github.com/golemfactory/yagna/issues/2400)
* [x] memory leak fix (https://github.com/golemfactory/yagna/issues/1985)
* ~[ ] ya-provider clean (TBD)~ Add directly to release branch
* [x] VPN network removal fix (showcase team) (https://github.com/golemfactory/yagna/pull/2538)
* [x] https://github.com/golemfactory/yagna/pull/2549
* [x] [Goth VPN issue](https://github.com/golemfactory/yagna/issues/2387)

Create RC with newest build. Update `testnet` to new version

**Comment by pwalski** [comment]
To fix some `goth` VPN issues when using a latest release we could include also https://github.com/golemfactory/yagna/pull/2548 (Issue https://github.com/golemfactory/yagna/issues/2387)
