### ISSUE TITLE
0.12.1 testing

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2545]
Precondition: get confirmation from showcase and SDK that the fixes work.

* Test each fix (as per #2544) separately
    * [x]  Make scenarios to test each of them.
      * [x] https://github.com/golemfactory/yagna/pull/2549
          Result: Requestor correctly logs:
          ```
          [2023-05-11T23:16:41.739+0200 INFO  ya_payment::service::public] Invoice [545525fd-563f-413c-844f-1affe43fb0d8] for Agreement [f2ff6924b7b53e1877da68bad868114beb8a7cb6771346c39d06f49b84262304] received from node [0x242387c33b96d47d42b1b5de1d71bf581cfd39a1].
          ```

* Have one person go through the normal testing session scenario.
  - [x] Requestor scenario:
    - Result: On yacat got few errors (but it worked):
Activity failed on provider '10hx4r2_5.h'; reason: Command 'Deploy {}' failed on provider; message: 'Local service error: Transfer error: Downloaded VM image is corrupted: calculated hash 95c389eac6062a9bab29e8b1765fca2c3465c974788dced2274fe179 differs from the expected one 055911c811e56da4d75ffc928361a78ed13077933ffa8320fb1ec2db'

Test scenarios:
1) [x] Memory leak
- Setup Node on `testnet` and monitor memory usage for some period of time:
   - Result: Testnet nodes have been up for over a week, and there are no nodes with sockets in `Closed` state (checked on `imapp2020`, `sharkoon378`, `golem2005`). Increased memory usage on `golem2005` is caused by release 0.12.0 instances.
- Run reproduction scenario from: https://github.com/golemfactory/yagna/issues/1985#issuecomment-1460048597
  - Result: On `testnet` nodes `yagna net sockets` prints no sockets in `Closed` state.

2) [x] `ya-provider clean`
  - Result: Tested on `ya-provider` 0.12.1-rc1 installed through installation script. Only old files from `exe-unit` are removed.

3) [x] VPN network removal
  - Unit test included with fix
  - Verification by showcase team
     Result:
       According to [this comment](https://github.com/golemfactory/yagna-triage/issues/242#issuecomment-1508487118) the problem could be reproduced by starting two apps using VPN and killing one of them. If it will not break the other app then it means the issue has been fixed.
I tested it using 2 webapp instances started with dapp-runner.
According to showcase team this scenario is enough for a verification.

4) [x] Goth VPN issue
  - Confirmation from SDK team that they are able to run tests on CI
    - Result: Merged  PR with working tests - https://github.com/golemfactory/yapapi/pull/1127

**Comment by pwalski** [comment]
Related to https://github.com/golemfactory/yagna/issues/2545
