### ISSUE TITLE
check if the newest version of ya-relay-server should be included in 0.12.1 release

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2546]
Go through the changes and see if we need them in 0.12.1?

**Comment by nieznanysprawiciel** [comment]
- https://github.com/golemfactory/ya-relay/pull/221 Offers propagation fixes (doesn't touch ya-relay-server)

**Comment by nieznanysprawiciel** [comment]
Decision:
We should update ya-relay-server first on `testnet` and on `public` networks after release

**Comment by nieznanysprawiciel** [comment]
`ya-relay-server` on `testnet` updated
