### ISSUE TITLE
libP2P spike

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2547]
* Rendezvous discovery should work [DONE]
* Can Nodes behind NAT talk with each other? [IN PROGRESS]
  * via Relay
  * hole punching 
* File transfer using libp2p
* Measure performance?
    * Compare direct usage of libp2p vs gftp
    * ping
    * transfer

As a second step we can prototype integration with yagna. We could do this as an alternative net module which could be chosen by flag (Like it was done for hybrid and central NET).

**Comment by MrDarthShoe** [comment]
Status of spike is documented here: https://docs.google.com/document/d/1zcoiv9X2OsvBspQQxsLHE9PnE32V31sqQ2tamz0IQWU/edit#

**Comment by MrDarthShoe** [comment]
@nieznanysprawiciel  will contact @prekucki  with results and find out how to proceed further
