### ISSUE TITLE
Migrate from Rinkeby to new Testnet (summer 2023)

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2571]
**Context:**
Rinkeby which is used by Golem, will be shutdown for good in mid 2023
Ethereum recommends to consider switching to Sepolia or Goerli.
New transactions are not visible on https://rinkeby.etherscan.io/ which is also not convenient.

**Acceptance Criteria:**
- change defaults - from Rinkeby to newly decided Test Network (see Open Questions)
- Allow making yagna payment fund via newly decided Test Network (see Open Questions)
- Remove Rinkeby from the Yagna

**Prerequisites**
- multifaucet - prepared by seciech (SCX)
- multifaucet- deployed by devops (Darek)
- rekuc decision on new testnet

**Open Questions:**
Which network should we switch to from Rinkeby (at Rekuc):
- Sepolia: has limited use due to lack of services there.
**- Goerli: we have payment driver, however we need to secure source of tokens for tests( after changing consensus mechanism tokens are not easily available). CHOSEN!**
- Mumbai test network on Polygon.

**Additional information:**
- https://blog.ethereum.org/2022/06/21/testnet-deprecation
- https://www.coindesk.com/tech/2022/11/30/the-ethereum-foundation-commences-shutdown-of-ropsten-testnet/

**Comment by golmek** [comment]
CORE: 
- change defaults
- allow making yagna fund via goerli or mumbai (decision on rekuc)

Blocked by:
- multifaucet - prepared by seciech
- multifaucet- deployed by devop[s
- rekuc decision on new testnet

**Comment by golmek** [comment]
Connected to: https://github.com/golemfactory/golem-internal/issues/555

**Comment by golmek** [comment]
TODO @golmek / @jalas167 -> Contact with people from Prerequisites to check their status and ticket numbers

**Comment by golmek** [comment]
TODO @golmek 

- Ask Requc if he will do changes himself

**Comment by golmek** [comment]
Update 07.06.23:

- New Release 0.12.2 changing Rinkeby to Goerli was done by Requc:
   - https://github.com/golemfactory/yagna/actions/runs/5187839168/jobs/9350694298
   - https://github.com/golemfactory/yagna/releases/tag/v0.12.2
- Merge for Review in Core: https://github.com/golemfactory/yagna/pull/2610

**Comment by MrDarthShoe** [comment]
TODO:
- [ ] merge https://github.com/golemfactory/yagna/pull/2610 (fix CI)
- [ ] take changes https://github.com/golemfactory/yagna/pull/2610 and merge it to `master` branch
