### ISSUE TITLE
Testing: Requestor POV

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2573]
https://github.com/golemfactory/yagna/issues/2543
Test exploratively: try to break things via CLI, misbehaving tests, anything.

**Comment by kamirr** [comment]
Status:
- [x] CLI -- couldn't break anything besides things obviously not working with invalid settings for `yagna`.
- [x] Checked all env variables with the same result.

Open question -- should unintuitive errors prompt creation of appropriate issues under the UX goal, or is it out of scope for this task?

**Comment by kamirr** [comment]
Expanded scope, timebox till wednesday June 14th EOD.
