### ISSUE TITLE
Testing: Exe-unit outbound implementation

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2577]
https://github.com/golemfactory/yagna/issues/2543
Test exploratively: try to break things via CLI, misbehaving tests, anything.

**Comment by MrDarthShoe** [comment]
# Malformed manifest
## Setup
Provider with everyone rule set to all
Requestor without signatures just sending manifest

## ✅ scenarios
- different image hash
- not known os

## ❕scenarios
- different outbound address in script (error visible only in exe-unit logs, not propagated to requestor)

##  ❌ scenarios
- changed protocol 
  - example 1
  ```json
      "net": {
        "inet": {
          "out": {
            "protocols": [
              "http"
            ],
            "urls": [
              "https://api.coingecko.com",
              "https://httpbin.org"
            ]
          }
        }
      }
  ```
  And executing script making https request works without rejection
  - example 2
  ```json
      "net": {
        "inet": {
          "out": {
            "protocols": [
              "https"
            ],
            "urls": [
              "http://api.coingecko.com",
              "http://httpbin.org"
            ]
          }
        }
      }
  ```
  And executing script making http request works without rejection
- xx

**Comment by evik42** [comment]
> different outbound address in script (error visible only in exe-unit logs, not propagated to requestor)
considered in Dev UX topic

> regex constraints in "external_api_request" can be easily omitted
The regex should be more specific, responsibility of the auditor of the payload to check this.
(Add this to some kind of documentation about manifest. /maybe in the handbook/)

> manifest version, metadata version, compManifest version are not checked against each other (not sure if they should be)
agreed that does not matter

> protocol field is ignored
seems like it could be removed, but it requires changing GAP

> expiresAt field is not validated
Not defined in gap, not defined in any documentation BUT it is present in examples (GAP, handbook). It is present in the Rust code (deserialized)  but not processed. If the field is not present, rust deserialization and as a result negotiation will fail.
Maybe this field should be added to the GAP.
