### ISSUE TITLE
Failed to init relay server session - timeout

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2581]
```
Failed to init relay server session: Request timed out after 3000s
```

This bug is instance of the same problem as in this issue, but happens on yagna startup, when Node is unlucky
to start on the period of relay overload:
https://github.com/golemfactory/ya-relay/issues/222

**Comment by grisha87** [comment]
This issue appears more frequently in last days. For the end user this looks like the whole network is not a stable solution which is discouraging for new people.
