### ISSUE TITLE
Yagna GPU Runtime Install Command

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2591]
GPU ExeUnit "Installation" script distributed with alongside `ya-runtime-vm-gpu` release package.

**Acceptance Criteria**
- [ ] Prepare installation script which will:
  - [ ] Fail early on `darwin` architecture (MacOS)
  - [x] Show information (high contrast red color) that GPU ExeUnit is highly experimental and it is connected with risks which make it suitable only for advanced users. What is more inform that this script will only download ExeUnit, which requires additional steps to be done on the provider to make it work. Steps will be provided in instruction under the provided link - exact copy to be provided by @golmek 
  - [ ] Ask user to type "I do understand and accept the risk" before proceeding
  - [ ] Downloads and unpacks `ya-runtime-vm-gpu` installation package into following PLUGINS directory:
    ```
    YA_INSTALLER_LIB=${YA_INSTALLER_LIB:-$HOME/.local/lib/yagna}
    PLUGINS=$YA_INSTALLER_LIB/plugins
    ```
    (make sure there is no name collision between `ya-runtime-vm` and `ya-runtime-vm-gpu` descriptor file and runtime dir file)
- [ ] Add installation script  to `ya-runtime-vm-gpu` release alongside VM release package
- [ ] ~~Installation script of runtime with GPU support mentioned in https://handbook.golem.network/provider-tutorials/provider-tutorial (with instruction to be started in similar way as installation script - curl + bash) -~~ Out of scope. @golmek  

**Not in Scope**
-  Not a GPU Installer. After using the command, GPU is not working yet - User still needs to follow instructions.

Additional Information:

- Information showed in Script are related with those which will be shown in README of repo: https://github.com/orgs/golemfactory/projects/30/views/13?pane=issue&itemId=28412375

**Comment by golmek** [comment]
@pwalski Do You think there is a way to add "monitoring". I mean, to easily add option so we can see how many times someone downloaded our new GPU ExeUnit via Script (or not)? That would be useful to have some metric about interest in GPU.

**Comment by golmek** [comment]
@pwalski Such tracking link most likely will need some involvement from Devops to be constructed. Am I right?

**Comment by pwalski** [comment]
@golmek, yes, but it would be better to avoid adding some link which may expire later to release installation script/package, so maybe if at all it should be added to links in handbook only?

**Comment by pwalski** [comment]
> Show information (high contrast red color) that GPU ExeUnit is highly experimental and it is connected with risks which make  it suitable only for advanced users. What is more inform that this script will only download ExeUnit, which requires additional  steps to be done on the provider to make it work. Steps will be provided in instruction under the provided link - exact copy to  be provided by @golmek

Installation script configures runtime descriptor which includes PCI device id.
Probably user should first configure their system and then run installation script. Otherwise they will end up with broken provider setup (`ya-runtime-vm-nvidia` will not start).
For now I just added click yes/no warning confirmation dialog. Will change it to request for typing warning message.

**Comment by golmek** [comment]
WARNING! 

Please be aware that this experimental ExeUnit (vm-nvidia) goal is to provide GPU support to Golem Network. If run successfully it will make your GPU available as a resource on Golem Network via PCI Passthrough. 

It is an experimental feature in its very early stage and consequently comes with NO guarantees. It was tested on a limited number of hosts with Nvidia GPU only. Downloading and installing this ExeUnit (vm-nvidia) is not sufficient to make this experimental feature work. Some changes on host setup itself are required too. High level instruction of such changes and other important information should be available on Github Repository Page: https://github.com/golemfactory/ya-runtime-vm-nvidia. 

As a extremely experimental feature Golem Factory gives NO guarantees regarding its security or that it will even work. There is a chance that Golem Factory will not be able to help you out in case that something does not work or go wrong.

If in doubt please refer to Disclaimer, User Interaction Guidelines and Privacy Policy available at Golem webpage: https://www.golem.network/

I was warned and I fully understand and accept the risks: YES/NO
