### ISSUE TITLE
Integrate Payment Driver (ERC20_NEXT) with yagna - STEP 1

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2673]
Initial integration of Payment Driver with Yagna with supporting current API == **Achieve feature parity.**

What is more, payment driver should include an implementation of the Signer trait from payments lib that uses the signing facilities in yagna to sign the transaction (will require some tweaks in identity). It is necessary for erc20_payment_lib to sign transaction in Yagna 

**Acceptance criteria:**
- [x] New Signer in ERC20_NEXT
  - [x] Payment Driver can sign transaction with key hold in Yagna
- [x] Yagna is able to make payments using new driver
- [x] Create new subtasks when problems are identified
- [x] Propose next steps - ~Notion~ as tasks

**Additional Information**
- connected with: https://github.com/golemfactory/erc20_payment_lib/issues/16
- based on results of: https://github.com/golemfactory/erc20_payment_lib/issues/6

**Comment by scx1332** [comment]
1. Set proper localization for database file related to driver. Driver has one common database for all networks.
2. Decide how to use payment_setup.toml when configuring yagna.
3. Cleanup mess with logging. Right now erc20 library is logging probably excessively.

**Comment by golmek** [comment]
**In progress:**

Currently not working - troubleshooting in progress

**Comment by golmek** [comment]
Refactor needed
