### ISSUE TITLE
Propagate driver events from driver to the agent

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2685]
Yagna already processes new Events. However, we need to include new Events in REST API so it can be processed by SDK in future.

**Acceptance Criteria:**
- [x] Update REST API to include events per invoice/debit note (payable)
- [x] Headers on Endpoint should turn on new Events
- [x] ~In Spec: change to have open list of events~
  - that's the default 
- [x] Document it. What Errors mean (Yagna docs)

**Comment by golmek** [comment]
Do we talk about new status?
