### ISSUE TITLE
[SPIKE] [Timebox] How to monitor AR with new Payment Driver

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2686]
**Why:**
- We want to test driver in real life environment

**Acceptance criteria:**
- Figure out what monitoring do we need to be sure after testing period that driver works correctly?
- Document findings & discuss with team

**Additional Information:**
- next step:  https://github.com/golemfactory/golem-internal/issues/658

**Comment by golmek** [comment]
Timebox: 1MD

**Comment by kamirr** [comment]
Conclusions:
* Add appropriate metrics viewable in grafana (see the current implementation in yagna, grep by `counter!`, `gauge!`).
* Create dashboards in grafana
