### ISSUE TITLE
Add Provider ability to check payments when Requestor uses MultiTransfer/Batches

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2698]
**Context:**
We need to verify if Provider can check payments arrival from Requestor when MultiTransfers of New Payment Driver are used.

It will impact if we can use the same name for a new payment driver or a new one has to be done.

If new one has to be provided, then new version of Yagna will have to support new and old payment driver simultaneously. 
This will increase the effort in development.

**Acceptance Criteria:**
- Perform tests to check the ability of Provider to verify payment arrival when Batches are used.
- Add ability of Provider to verify payments done my MultiTransfers
- Add ability of Provider to verify payments done my Batches (if not working)

**Prerequisite:** 
- https://github.com/golemfactory/yagna/issues/2673

**Comment by kamirr** [comment]
Blocked by https://github.com/golemfactory/yagna/issues/2714

**Comment by golmek** [comment]
Is it still valid? Did we checked that?

**Comment by golmek** [comment]
Non multitransfer -> OK
