### ISSUE TITLE
Enable and check tests on payments-dev

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2721]
Acceptance criteria:
* Enable the same tests on `payments-dev` as on `main`
* Tests must pass

**Comment by kamirr** [comment]
Blocked by:
* https://github.com/golemfactory/gnt2/pull/174

Grisha agreed to work on that, waiting for his input.

**Comment by golmek** [comment]
IN PROGRESS:
- Fix Goth verification of running Yagna (currently parsing logs)
- Relay fix
