### ISSUE TITLE
Fix Payment Driver naming scheme

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2767]
ERC20 + ERC20Legacy (separe branch) -> ERC20next + ERC20(master)

**Comment by kamirr** [comment]
Blocked:
- [ ] all other changes done and new branch for master PR created.

**Comment by golmek** [comment]
**Needed:**
- Patch to Yapapi
- Patch GolemCore
- Patch JS

**Comment by golmek** [comment]
Plan:
1. release dirver
2. migrate AR
3. update :Yapapi, Golem Core, Patch JS

**Comment by kamirr** [comment]
Blocked:
- Goth PR should only be merged after we merge to master -- it'd break goth master for yagna master otherwise
- Yapapi, golem-js and golem-core-python PRs should only be merged some time after the release, when we wish to expose outside requestors to the new payment driver.

**Comment by golmek** [comment]
@golmek Consider moving SDK tickets to other Issue.

**Comment by golmek** [comment]
Goth changes can merged after release

**Comment by golmek** [comment]
Waiting for Sieciech review
