### ISSUE TITLE
Test Session before Release

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2768]
We should make sure that our changes in Yagna won't mess up anything after we will do merge do master branch

**Acceptance Criteria:**
- [x] Prepare test scenarios & discuss it with a team
  - [x] https://www.notion.so/golemnetwork/payments-dev-requestor-testing-1-ef7d1c4b945f4ecebcafbe0a24dc3c25
  - [x] https://www.notion.so/golemnetwork/payments-dev-provider-testing-1-4e10081cafef4df58ec27e94da0254d4
- [ ] Perform team wide test session

**Comment by kamirr** [comment]
Test scenarios must be discussed before this goes back to in-progress.

**Comment by kamirr** [comment]
Blocked, we need:
- [ ] a review PR to master
- [ ] a RC built from HEAD of that branch

**Comment by golmek** [comment]
test scenario - @kamirr + @pociej
