### ISSUE TITLE
Implement all missing statuses

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2784]
# Prerequesites
- https://github.com/golemfactory/erc20_payment_lib/issues/17
- https://github.com/golemfactory/yagna/issues/2734
- [ ] `erc20_payment_lib` is feature-complete re. capability to detect all events we care about

With the above complete, all architectural groundwork for statuses will have been completed. What remains is to fill in the gaps with what we actually care to expose.

# Acceptance Criteria
- [ ] Produce missing statuses in `erc20_payment_lib`. As per the previous discussion, the agreed-upon minimum is: missing gas, missing token, stuck TX, fatal RPC issues, inability to sign a TX.
  - https://github.com/golemfactory/yagna/issues/2828
  - https://github.com/golemfactory/yagna/issues/2829
  - https://github.com/golemfactory/yagna/issues/2830
  - https://github.com/golemfactory/yagna/issues/2831
  - https://github.com/golemfactory/yagna/issues/2832
- [ ] Update ya-client if any new statuses are added. The current implementation coveres everything from the above point.
- [ ] Update `golemsp` and `yagna payment status` to pretty-print them.

**Comment by golmek** [comment]
TODO: split into separate tasks per status

**Comment by golmek** [comment]
Closing this ticket as we splitted this task into multiple one per status
