### ISSUE TITLE
Add CLI onboarding command

### ISSUE THREAD

**Issue by pociej** [golemfactory/yagna#2877]
Acceptance criteria : 
 - [x] syntax should be `yagna payment onboarding` 
 - [x] onboarding url should be setable from both env and cli 
 - [x] it should automatically open onboarding in browser using currect yagna id public_key as `yagnaAddress`

**Comment by golmek** [comment]
Link to duplicate ticket: https://github.com/golemfactory/yagna/issues/2691

**Comment by golmek** [comment]
most likely will be looked again in 2 days time

**Comment by golmek** [comment]
To be consulted with @kamirr
