### ISSUE TITLE
Update Documentation Goerli -> Holesky

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2897]
**Acceptance Criteria:**
- [ ] All Goerli mentions connected with Default Testnet should be changed to Holesky
- [x] Add entry in `docs/` linking to erc20next `readme.md`
- [x] Consider adding a chapter abount payment configuration to golem-docs.

**Comment by kamirr** [comment]
> All Goerli mentions connected with Default Testnet should be changed to Holesky

In `golem-docs` goerli default is only mentioned in the context of SDKs. JS SDK team is migrating to Holesky on their own, how do we manage that?
