### ISSUE TITLE
Outbound connection is fully closed when the sender side of the tcp socket is closed

### ISSUE THREAD

**Issue by evik42** [golemfactory/yagna#2922]
When the sender side of a TCP socket is closed in the VM, the Exe-Unit closes the full connection and this might result in the client not receiving all the data from the remote server.
Exe-Unit should close the sender side of the outbound tcp socket and not fully close the smoltcp socket via abort.

Run the following small utility in a VM and it would sometimes result in partial data received:

```rust
use std::net::{TcpStream, Shutdown};
use std::io::prelude::*;

fn main() {
    let mut buf = [0; 102400];
    let mut stream = TcpStream::connect("norvig.com:80").expect("Couldn't connect to the server...");
    stream.write(b"GET /big.txt HTTP/1.0\r\nHost: norvig.com\r\nConnection: close\r\n\r\n").expect("Couldn't write to the server...");
    stream.shutdown(Shutdown::Write).expect("Couldn't shutdown the write stream...");
    let mut total_bytes_read = 0;
    while let Ok(bytes_read) = stream.read(&mut buf) {
        if bytes_read == 0 {
            break;
        }
        total_bytes_read += bytes_read;
    }
    println!("bytes read: {}/6488879, read {}", total_bytes_read, if total_bytes_read == 6488879 { "FULL" } else { "PARTIAL" });
}
```
The problem is most likely in the [disconnected message handling](https://github.com/golemfactory/yagna/blob/6e6312a7260833aed1113bcedb80520b8cc96757/exe-unit/src/network/inet.rs#L292-L300) which indicates that the sender side is closed. The call to unbind on the proxy results in an `abort` call on the socket which abruptly closes the full socket and does not wait for the close from the remote side.

**Comment by jalas167** [comment]
a simple workaround was implemented at this moment, a proper solution would require the outbound feature redesign
