### ISSUE TITLE
Prohibit concurrent usage of erc20 and erc20next

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2949]
`erc20` and `erc20next` drivers cannot run concurrently as this results in problems regarding nonces.

# Acceptance Criteria
- [x] Error on init account as `send` if account on conflicting driver already is `send`.
- [x] If we do init -- check accepted *unpaid* invoices on conflicting drivers. Fail if any exist.
  - Check token / gas balance as well as total obligation amount -- attach to error.

**Comment by golmek** [comment]
Will be released with 14.1 (Holesky)

Blocks:
- SDK update

**Comment by golmek** [comment]
review session to be done on monday - as Kamil is sick

**Comment by golmek** [comment]
14.1 will be without old payment driver
