### ISSUE TITLE
double payments for the last chunk of work (when invoice is accepted before last debit Note)

### ISSUE THREAD

**Issue by jalas167** [golemfactory/yagna#2970]
In JS examples (using mid-agreement payments), I observe that there are 2 payments done for the last chunk of work. The reason is that SDK received an Invoice before the last debit note. So Yagna calculates the remaining amount to pay first for the invoice and then for the debit note. 
If they are accepted in such order, then Yagna makes 2 payments. 

Yagna should skip accepted debit Notes for an agreement for which the invoice was already processed.

**Comment by scx1332** [comment]
Fixed in https://github.com/golemfactory/yagna/commit/9e29996c9b3b49f16c984578209af570543ae14f
