### ISSUE TITLE
Update SDK with Holesky as a Default Network

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2994]
Update SDK to use Holesky as a Default Network:
- Python (Core +Yapapi)
- JS

should be done after: https://github.com/golemfactory/yagna/issues/3023

**Comment by golmek** [comment]
Python SDK's does not work on Goth - investigation in progress

TO DO:
- talk with Grisha to figure out why tests are done on Goerli instead of Holesky

**Comment by golmek** [comment]
**Status:**
- JS works
- Python Core - In progress
- Yapapi - In progress


**TODO:**
- ask SDK team to move SDK tests on RC

**Comment by golmek** [comment]
Blocked till release

**Comment by golmek** [comment]
Review done by @shadeofblue

**Comment by kamirr** [comment]
blue is ooo until tomorrow

**Comment by golmek** [comment]
Ping @shadeofblue
