### ISSUE TITLE
Invoices returned from the API with odd sorting 

### ISSUE THREAD

**Issue by grisha87** [golemfactory/yagna#3010]
## Steps to reproduce

Example call:

```bash
curl -s --location 'http://localhost:7465/payment-api/v1/invoices?afterTimestamp=2023-12-29T09%3A46%3A32.238787565Z&maxItems=10' \
--header 'Authorization: Bearer ...' | jq '.[].timestamp'
```

## Actual result

The call produces the following timestamps:

```                                 
"2024-01-01T19:38:37.325Z"
"2023-12-29T17:14:41.929Z"
"2024-01-15T14:19:46.913Z"
"2024-01-01T21:26:01.640Z"
"2024-01-15T12:30:07.411Z"
"2024-01-12T11:36:37.117Z"
"2024-01-15T13:59:23.745Z"
"2024-01-02T13:52:38.578Z"
"2024-01-15T13:54:07.374Z"
"2024-01-15T12:27:42.595Z"
```

## Expected result

We're implementing an invoice listing CLI and UI tool. We would like to display the invoices in order from oldest to latest - we assumed such order - most probably ordered by the `timestamp` field.

**Comment by nieznanysprawiciel** [comment]
Labelled as bug since it blocks proper usage of payment api.
There is limit of invoices you can query in one call. If they aren't sorted, than you don't know at which timestamp start new call.
