### ISSUE TITLE
Driver & Network Selection - new mechanism

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3023]
## Context:

Currently configuration of payment platform (driver + network + token) is done by application. It has some benefits, however also introduces important problems:

- When default driver is changed in Yagna, SDK still uses old driver
- When default network is changed in Yagna, SDK still uses old default network
- At least few times a year ETH testnet has smaller or bigger downtime or is overloaded

Consequently, we want to change our approach and get rid off precise specification of payment platform on allocation creation (flow between SDK → API → Yagna requestor). 

### Payment Platform:

Payment Platform consists of 3 values: driver, network, token

We want:

- driver - to have default value of `erc20`  (underneath new payment driver will be hidden - https://github.com/golemfactory/yagna/issues/3019)
- network - to have default value of `holesky` for `tglm` and `polygon` for `glm`
- token → For instance for default values of `erc20` or/and `holesky` it should return `tglm`. For values of `erc20` or/and `polygon` it should return `glm`

### Allocation Creation

SDK will create allocation in following fashion:
---
Example A: default driver, netwrok and token:
Request:

```jsx
{
    "totalAmount": "10",
    "makeDeposit": false
}

```

Alternative Request:

```json
{
    "paymentPlatform": {},
    "totalAmount": "10"
    "makeDeposit": false
}
```

Response:

```jsx
{
    "allocationId": "520008f2-ffb5-427e-b9ec-17173520b78b",
    "address": "0x889ff52ece3d5368051f4f8216650a7843f8926b",
    "paymentPlatform": "erc20-holesky-tglm",
    "totalAmount": "10",
    "spentAmount": "0",
    "remainingAmount": "0",
    "timestamp": "2024-01-19T12:29:35.278Z",
    "timeout": "2034-01-19T15:29:34.535594Z",
    "makeDeposit": false
}

```
---
Example B: default driver on polygon

```jsx
{
    "paymentPlatform": {
        "network": "polygon",  // Optional
    },
    "totalAmount": "10"
    "makeDeposit": false
}
```

Result:

```jsx
{
    "allocationId": "520008f2-ffb5-427e-b9ec-17173520b78b",
    "address": "0x889ff52ece3d5368051f4f8216650a7843f8926b",
    "paymentPlatform": "erc20-polygon-glm",
    "totalAmount": "10",
    "spentAmount": "0",
    "remainingAmount": "0",
    "timestamp": "2024-01-19T12:29:35.278Z",
    "timeout": "2034-01-19T15:29:34.535594Z",
    "makeDeposit": false
}
```
---
Example C: full platform specified 

Request (backward compatible):

```json
{
    "paymentPlatform": "erc20-polygon-glm",
    "totalAmount": "10"
    "makeDeposit": false
}
```

Alternative Request:

```json
{
    "paymentPlatform": {
        "driver": "erc20",            // Optional
	"network": "polygon",    // Optional
	"token": "glm"               // Optional 
    },
    "totalAmount": "10"
    "makeDeposit": false
}
```

Result

```json
{
    "allocationId": "520008f2-ffb5-427e-b9ec-17173520b78b",
    "address": "0x889ff52ece3d5368051f4f8216650a7843f8926b",
    "paymentPlatform": "erc20-polygon-glm",
    "totalAmount": "10",
    "spentAmount": "0",
    "remainingAmount": "0",
    "timestamp": "2024-01-19T12:29:35.278Z",
    "timeout": "2034-01-19T15:29:34.535594Z",
    "makeDeposit": false
}
```
---
Example D: **default driver and network for glm token:**

```json
{
    "paymentPlatform": {
	"token": "glm"           // Optional 
    },
    "totalAmount": "10"
    "makeDeposit": false
}
```

Result:

```json
{
    "allocationId": "520008f2-ffb5-427e-b9ec-17173520b78b",
    "address": "0x889ff52ece3d5368051f4f8216650a7843f8926b",
    "paymentPlatform": "erc20-polygon-glm",
    "totalAmount": "10",
    "spentAmount": "0",
    "remainingAmount": "0",
    "timestamp": "2024-01-19T12:29:35.278Z",
    "timeout": "2034-01-19T15:29:34.535594Z",
    "makeDeposit": false
}
```

## Acceptance Criteria:
- golemjs / actions/ -> release test

## Additional Information:

- Change can be released independently from SDK as it is backward compatible
- Some changes (on allocation creation) introduced in https://github.com/golemfactory/yagna/issues/2639 should be reverted.
- demand decoration - no changes, except the ones introduced here: https://github.com/golemfactory/yagna/issues/3019#issue-2093536703

**Comment by golmek** [comment]
@grisha87 @shadeofblue @nieznanysprawiciel - above ticket is a conclusion of our Friday discussion regarding default network/driver selection on Allocation creation. Please verify it that looks OK from your perspective (SDK - JS + Python)

**Comment by golmek** [comment]
Blocked till feedback is gathered.

**Comment by grisha87** [comment]
To the AC I would add that the pre-release containing the fix should successfully pass the tests on `master` and `beta` for this pipeline:

https://github.com/golemfactory/golem-js/actions/workflows/release.yml

### How to run it:

1. Open the release pipeline
2. Manually trigger the pipeline for `master` branch and put the pre-release information into the dialog
3. Repeat the test for `beta` branch

### Success criteria

* Both test runs finish successfully

**Comment by shadeofblue** [comment]
re: example D -> my expectation would be for yagna to give me the "recommended" platform that will satisfy the requirement that I have given in my request -> so, in other words, my interpretation of the request is: give me the "default" of those platforms that support the `glm` token ... 

or, in yet another set of words, give me the default mainnet platform... 

such as it implemented, it will prevent forwards-compatibility of allowing the SDK to select the default mainnet platform... e.g. if we wanted to switch from `polygon` to some other blockchain or from `erc20` to some other driver...

**Comment by shadeofblue** [comment]
> To the AC I would add that the pre-release containing the fix should successfully pass the tests on `master` and `beta` for this pipeline:
> 
> https://github.com/golemfactory/golem-js/actions/workflows/release.yml
> ### How to run it:
> [cut]
> ### Success criteria
> 
>     * Both test runs finish successfully

uh, it would be good to conduct also tests with other requestor products as JS SDK is very far from the only consumer here ;p

**Comment by scx1332** [comment]
Added pull request
https://github.com/golemfactory/ya-client/pull/156

**Comment by golmek** [comment]
back

**Comment by golmek** [comment]
RC 14 has those changes
