### ISSUE TITLE
New Driver - Multi Account support

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3035]

**Comment by scx1332** [comment]
Yagna and Payment driver should respect that accounts are independent of each other and add a possibility to proceed transactions simultanously for any account. Payment error or problem on one account should not block others.

**Comment by golmek** [comment]
TODO:
- Add/Remove Account during Driver work
- Integration with Yagna

Deadline: This week

**Comment by scx1332** [comment]
* Changes in API
* Changes in runtime
* Changes in event system (for account separation)
* Possibility of starting separate accounts after startup 
*

**Comment by golmek** [comment]
IN PROGRESS:
- adding new account to included in driver

TODO:
- yagna payment driver status
- figure out test approach

**Comment by golmek** [comment]
**IN PROGRESS:**
- driver statuses

**Comment by golmek** [comment]
- Kamil to help with statuses
- possible done till EoW
