### ISSUE TITLE
Service fee is hidden cost not reflected in allocation

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#3142]
Problem:
We allow user to implement any fees model on his contract. But the amount on allocation is set to full deposit amount.
The amount reserved for fees will increase on contract, but it won't be reflected on allocation.
This way we can spend on money from deposit, but allocation will still have money.

**Comment by golmek** [comment]
Spender Fees to be part of Allocation?

**Comment by nieznanysprawiciel** [comment]
> @nieznanysprawiciel To avoid that. Shouldn't Allocation status be monitored by using Contract Get Deposit function: https://github.com/golemfactory/erc20_payment_lib/blob/dev/yatestnet/contracts/contracts/LockPayment.sol#L74

Probably it should. The question is what to do with this status later.
- Should we decrease allocation amount? It would be rather strange from user perspective
- Maybe allocation should have additional field for service fees?

Other problem are race conditions between Invoice/DebitNote acceptance and checking Deposit. It can turn out that we accepted DebitNote, but we can't pay it, because the service fee was paid. We have this problem anyway due to https://github.com/golemfactory/yagna/issues/3141 but I wouldn't like to make it bigger.

Maybe we should check paid fees before each acceptance or after each payment is made??

**Comment by golmek** [comment]
Maybe we should check paid fees before each acceptance -> Like this idea

**Comment by golmek** [comment]
Problem described in this ticket (Yagna potentially spending more than should, and making it impossible to cover Service Fee) is not possible, as currently Deposit consists of two values (Fee, Amount). Amount is used to cover Provider Payments, and it is visible as Allocation on Yagna level.

Other payments models are still possible. For instance % fees are supported in Fee + Amount values.
