### ISSUE TITLE
Allocation creation requires confusing parameters

### ISSUE THREAD

**Issue by grisha87** [golemfactory/yagna#3150]
With the recently introduced changes to `ya-client` the allocation creation can take in two types of parameters in the request body:

```ts
{
  makeDeposit: boolean | undefiend
  deposit: { contract: string, id: string }
}
```

As far as the API specs explain, the `makeDeposit` property is not used. From the end-user perspective this looks like the API would support the following scenario: _Given I specified `deposit` and set `makeDeposit` then doing the call will create the deposit for me_.

I believe that we should deprecate the `makeDeposit` field and remove it in the near future.

**Comment by golmek** [comment]
I agree that it will be confusing as hell. Should be cleared out with Gisha suggestion.

**Comment by kamirr** [comment]
A good first step would be to stop requiring this field in the spec and marking it as deprecated. We can't remove it outright due to backward compat.

**Comment by kamirr** [comment]
reqc will deliver this, detaching from payments UX.
