### ISSUE TITLE
PREPARE SPECS FOR REQC AND OTHER TEAMS!!! URGENT

### ISSUE THREAD

**Issue by scx1332** [golemfactory/yagna#3158]

**Comment by scx1332** [comment]
Create deposit specs in https://github.com/golemfactory/golem-architecture/tree/master/specs

**Comment by golmek** [comment]
To be done - Tomorrow EOD
Wednesday - verification

**Comment by golmek** [comment]
https://github.com/golemfactory/golem-architecture/blob/scx1332/deposits/specs/deposits.md

**Comment by golmek** [comment]
Second round of review to be done by @nieznanysprawiciel

**Comment by golmek** [comment]
DONE

**Comment by golmek** [comment]
TODO: Review by Requc

**Comment by golmek** [comment]
@nieznanysprawiciel will ping requc

**Comment by golmek** [comment]
Requc will check it till EoW
