### ISSUE TITLE
Verify Yagna 0.15 problems

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3161]
problems noticed by Philip

https://discord.com/channels/687954211702439971/707188925030203422/1225893040690954250
https://discord.com/channels/687954211702439971/826799481386434560/1225764189851881502

```
Summary:
6 tasks but 15 agreements - paid for 15 agreements
Release seems unstable? Testnet went down twice since friday, completely unable to start tasks. Offers flows in but communicating back seems to not work (tcp socket closed)
```

**Comment by kamirr** [comment]
Problem with the number of agreements was caused by a misuse of SDK.

**Comment by golmek** [comment]
@kamirr - Do changes in Net introduced in 0.15 had impact on problems with testnet (socket closed)?

**Comment by golmek** [comment]
@kamirr - Is Yagna stuck from Requc was further investigated?

**Comment by kamirr** [comment]
> Do changes in Net introduced in 0.15 had impact on problems with testnet (socket closed)?
Apparently old issue, reqc ordered us not to fix it and also it doesn't prevent yagna from working.
> Is Yagna stuck from Requc was further investigated?
Resolved by some changes in the deployment environment

**Comment by kamirr** [comment]
AR issue verification to be continued in
