### ISSUE TITLE
Design deposit validation

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3174]

**Comment by golmek** [comment]
@kamirr - to update document, as solution is decided

**Comment by kamirr** [comment]
https://www.notion.so/golemnetwork/Specifications-f664c647d3d541b1aa2ad0fa98624ed9?p=f1ad6c3a02cc44e5a61da927cff7e78c

**Comment by golmek** [comment]
review by @nieznanysprawiciel

**Comment by golmek** [comment]
@kamirr TODO corrections after review

**Comment by golmek** [comment]
TODO: Requc review

**Comment by golmek** [comment]
To be done today - 13.05

**Comment by kamirr** [comment]
approvied by @nieznanysprawiciel
