### ISSUE TITLE
Negotiation phase - sending proposal - validation error

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#318]
#### Pre-conditions
- _Requestor_ received single _Proposal_

##### _Requestor_ Scenario
* _Requestor_ sends _counter_proposal_
    * [x] Market can't send _Proposal_ to Provider due to reason:
        * [x] Proposal Demand doesn't match with Provider's Offer
        * [x] Offer expired
        * [x] Offer was unsubscribed
    * [x] Requestor gets error from _counter_proposal_ endpoint

##### _Provider_ Scenario
* _Provider_ sends _counter_proposal_
    * [x] Market can't send _Proposal_ to _Requestor_ due to reason:
        * [x] Proposal Offer doesn't match with _Requestor_'s Demand
        * [x] Demand was unsubscribed
        * ~Demand expired~ (edit 2021-07-21 @tworec: It is not possible to check if Demand expired on Provider side bc Requestor node do not share/broadcast Demands to other nodes; only Offers are circulating through the Market network)  
    * [x] _Provider_ gets error from _counter_proposal_ endpoint

**Comment by tworec** [comment]
I've checked in the code if the missing checks are implemented. The one which was possible (Offer expiration checked on Requestor side) is there, and second one is not possible (see my comment above within the issue description).
