### ISSUE TITLE
Improvement when getting balance

### ISSUE THREAD

**Issue by scx1332** [golemfactory/yagna#3210]
Use multi call contract for getting balance and checking RPC correctness

Using proper contract we should be able to check in one call balance, token balance and also the block timestamp that we are on. That will greatly improve response time and fix some issues when calling multiple rpc endpoints consecutively.

**Comment by golmek** [comment]
2-3 MD

**Comment by golmek** [comment]
- Should be done EoW
- Monday: after daily presentation

**Comment by golmek** [comment]
@scx1332 Presentation for a team - Wednesday 29.05

**Comment by golmek** [comment]
@scx1332 - please add PR's and change status to the actual one

**Comment by golmek** [comment]
@scx1332  TODO: Check on different RPC endpoints that a feature works with zero balances. 
to be considered: fallback to old getting balance method?

**Comment by scx1332** [comment]
List of tested polygon nodes
        "https://polygon-pokt.nodies.app",
        "https://polygon-mainnet.public.blastapi.io",
        "https://polygon-pokt.nodies.app",
        "https://1rpc.io/matic",
        "https://polygon-rpc.com",

List of tested holesky nodes
        "https://holesky.drpc.org",
        "https://ethereum-holesky.blockpi.network/v1/rpc/public",
        "https://ethereum-holesky-rpc.publicnode.com"

Other nodes where also tested but lot of them are unstable

**Comment by scx1332** [comment]
holesky.drpc.org sometimes returned:

insufficient funds for gas * price + value
