### ISSUE TITLE
Yagna 0.16 Release

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3261]

**Comment by RoyKas** [comment]
Would be nice to see a target defined for this release ;-)

**Comment by golmek** [comment]
> Would be nice to see a target defined for this release ;-)

Hi! We usually keep ETA of Releases in our internal document as those dates can vary a lot due to tests and other things in our processes.

However, I can say that at this moment we aim with this release at end of July / beginning of August.

**Comment by RoyKas** [comment]
Thanks for the prompt response. I was not intending the target date, but the targeted changes, improvements and fixes. I'm likely not the only one interested in what is upcoming, and which issues will be addressed (and which are not).

**Comment by golmek** [comment]
> Thanks for the prompt response. I was not intending the target date, but the targeted changes, improvements and fixes. I'm likely not the only one interested in what is upcoming, and which issues will be addressed (and which are not).

Hi again :)

This release will be focused around introducing new method of Payments on Golem: Deposit Payments.
It will make possible to pay Providers via funds stored on Deposit Contract. As a result person who is paying for Golem services might be separated from the person who is running Yagna. What is more we also introduced new cashflow from End User (person who puts glm on Contract to pay for Services on top of Golem) to Service Owner (person who runs Yagna and act as a gateway to Golem ecosystem).

You can read more about it here:
https://github.com/golemfactory/golem-architecture/blob/scx1332/deposits/specs/deposits.md

BR!

**Comment by golmek** [comment]
duplicate of: https://github.com/golemfactory/golem-internal/issues/699
