### ISSUE TITLE
Add building of ExeUnit supervisor to Provider instruction

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#355]
Supervisor isn't built because no create in yagna references it.

**Comment by tworec** [comment]
This is not about crate reference, because `exe-unit` is a binary.

It needs to be explicitly listed under `[[bin]]` within top-level `Cargo.toml` to be build by default.

Or maybe better it can be market as `default-members = ["exe-unit"]`. But I'm not sure it is what we want

**Comment by nieznanysprawiciel** [comment]
Actually it is implicit dependency of ya-provider. Can we force build of supervisor while building provider?

**Comment by tworec** [comment]
good idea
should be doable
