### ISSUE TITLE
ExeUnit: streaming command output

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#409]
# ExeUnit: streaming command output

- [ExeUnit: streaming command output](#exeunit-streaming-command-output)
  - [Prerequisites](#prerequisites)
  - [Supervisor](#supervisor)
    - [Current implementation](#current-implementation)
    - [Event model](#event-model)
    - [Proposed changes](#proposed-changes)
  - [Daemon](#daemon)
    - [GSB endpoint](#gsb-endpoint)
    - [API endpoint](#api-endpoint)
  - [Additional changes](#additional-changes)
    - [Supervisor: command output storage](#supervisor-command-output-storage)
    - [Daemon: command output storage](#daemon-command-output-storage)
    - [`ExeScriptCommandResult`](#exescriptcommandresult)

## Prerequisites

- ExeUnit Runtime server support [#389](https://github.com/golemfactory/yagna/pull/389)

### Current implementation

Currently, `RuntimeProcess::handle_service_command` concatenates each `stdout` and `stderr` output chunk emitted by the blocking runtime. This behavior should be changed, so that each output chunk is:

- stored locally by the Supervisor

  Requestors should be able to retrieve (partial or full) command output at any point in time.

- streamed directly to the Requestor

  If enabled, the output should sent via GSB (and network) directly to the requestor.

### Event model

The proposed model (**TBD**) includes details of the currently running command, which allows to reconstruct the whole execution flow of a batch.

Model should be placed in the `ya-client-model` crate.

```rust
struct RuntimeEvent {
    batch_id: String,
    index: usize,
    kind: RuntimeEventKind,
    timestamp: u64,
}

enum RuntimeEventKind {
    Started {
        command: ExeScriptCommand
    },
    Finished {
        return_code: i32,
        message: Option<String>,
    },
    StdOut(String),
    StdErr(String),
}
```

### Proposed changes

1. `RuntimeProcess::handle_process_command`

    Child process output is buffered and read when the process terminates. Output should be collected in chunks, stored locally and streamed to the requestor with each chunk.

2. `RuntimeProcess::handle_service_command`

    Instead of concatenating chunks of `stdout` and `stderr` output, the output should be stored with each chunk and streamed.

3. Streaming output switch

    Streaming may be on by default or disabled explicitly (**TBD**).

    The requestor's node identifier could be set as either:

    a. Supervisor CLI argument

      Provided by the yagna daemon. **Requires an additional flag during activity creation.**

    + node id is known globally (can be used for other streaming purposes)
    - node id cannot be changed while running
    - requires additional changes to existing models

    b. `STREAM` command (**TBD**)

      Provided by the requestor in a command batch.

    e.g. `STREAM enable <node_id>`
    e.g. `STREAM disable <node_id>`

    + flexibility in receiving outputs of chosen commands
    + flexibility in setting the destination node id
    - `node_id` might need to be sanitized (ACL)

## Daemon

  Proposed changes apply only to the `requestor_state` part of the yagna daemon.

### GSB endpoint

  This GSB endpoint should store `RuntimeEvent`s emitted by the Supervisor.

### API endpoint
  **TBD**

  ```yaml
  /activity/{activityId}/exec/{batchId}:
    get:
      tags:
        - requestor_state
      parameters:
        - $ref: '#/components/parameters/laterThan'
  ```

- streaming response of `RuntimeEvent` JSON objects with [server sent events](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events)
- filtered by time (`laterThan` param)

### Supervisor: command output storage

Command outputs are currently stored in memory. It might be viable to switch to a persistent form of storage (db, file) due to potentially large size of the output.

### Daemon: command output storage

Command output should be flushed from the database on demand (via `requestor_state` API)

### `ExeScriptCommandResult`

Split the aggregate `message` into `stdout` and `stderr` so that the outputs are stored and sent separately to the requestor.

**Comment by Doc-Saintly** [comment]
This may be included in some of the content above, but I don't fully understand all of the structure being proposed.

The streaming output is nice, but it would also be nice for the requester to be able to use a class to define the data they want to receive from the ExeUnit as it progresses or when they check on the status.
