### ISSUE TITLE
DataDir issues

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#451]
1) There are 2 very similar `DataDir` implementations, that could be unified:
- `utils/path/src/data_dir.rs`
- `core/serv/src/data_dir.rs`
2) The default path created by `DataDir` from `utils` is `${HOME}/.local/share` despite `Default` implementation. (It is used by provider agent to store `hardware.json` and `presets.json`)

**Comment by mfranciszkiewicz** [comment]
Resolved in https://github.com/golemfactory/yagna/pull/454
