### ISSUE TITLE
Yagna id drop fails

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#455]
When trying to delete an id i get the following. error:
```
Error: bad request: No service registered under given address
```

Steps taken:
```
$ yagna id list
┌───────────┬──────────┬─────────┬──────────────────────────────────────────────┐
│  default  │  locked  │  alias  │  address                                     │
├───────────┼──────────┼─────────┼──────────────────────────────────────────────┤
│  X        │          │         │  0x17ec8597ff92c3f44523bdc65bf0f1be632917ff  │
│           │          │         │  0x00ab0d402d3d5ebdef4b405a8f6b62d66946db24  │
└───────────┴──────────┴─────────┴──────────────────────────────────────────────┘
```
```
$ yagna id drop --help
yagna-id-drop 0.2.0
Drop given identity

USAGE:
    yagna id drop [FLAGS] [OPTIONS] <node-or-alias>

FLAGS:
        --json       Return results in JSON format
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -d, --datadir <data-dir>    Service data dir [env: YAGNA_DATADIR]  [default: "/Users/mwu-gol/Library/Application
                                Support/GolemFactory.yagna"]

ARGS:
    <node-or-alias>    Identity alias to drop
```
```
$ yagna id drop 0x00ab0d402d3d5ebdef4b405a8f6b62d66946db24
Error: bad request: No service registered under given address
```
```
$ yagna id list
┌───────────┬──────────┬─────────┬──────────────────────────────────────────────┐
│  default  │  locked  │  alias  │  address                                     │
├───────────┼──────────┼─────────┼──────────────────────────────────────────────┤
│  X        │          │         │  0x17ec8597ff92c3f44523bdc65bf0f1be632917ff  │
│           │          │         │  0x00ab0d402d3d5ebdef4b405a8f6b62d66946db24  │
└───────────┴──────────┴─────────┴──────────────────────────────────────────────┘
```

**Comment by mateuszsrebrny** [comment]
Previous attempt to implement drop: https://github.com/golemfactory/yagna/pull/1537

**Comment by grisha87** [comment]
I would like to upvote this issue, as I would like to clean-up redundant IDs on my machine using the CLI and not hack the database.

**Comment by prekucki** [comment]
Test scenarios:

## TC1: Deleting the Only Identity

1. Start the server in a clean environment.
2. List `yagna id list` and observe that only one identity is listed.
3. Execute `yagna id drop <id>` on this single identity.
4. Result: Receive an error message stating that you cannot delete the default identity.

Oto tłumaczenie scanariuszy testowych UC2, UC3 i UC4 na angielski:

## UC2: Deleting the Default Identity

1. Start the server.
2. Create several (>3) identities.
3. Switch the default identity to one of the newly added ones.
4. Perform a restart.
5. After startup, check `yagna id list` to verify if the new identity is now the default.
6. Execute `yagna id drop <id>` on this identity.
7. Result: Receive an error message stating that you cannot delete the default identity.

## UC3: Deleting a Locked Identity

1. Start the server.
2. Create a new identity with a non-empty password.
3. Result: The new identity has `isDefault: false` and `isLocked: true`.
4. Call `yagna id drop <id>` on this identity.
5. Receive a message: "By deleting this identity, you will also delete the internal key to your payment wallet. If you have any funds on it and haven't backed up the key, you won't be able to recover them. If you have any open contracts or pending payments on this identity, you won't be able to close or settle them. Are you sure?"
6. After confirmation, check `yagna id list` to see if the identity still exists.

## UC4: Deleting an Unlocked Identity

1. Start the server.
2. Create a new identity with a non-empty password.
3. Result: The new identity has `isDefault: false` and `isLocked: true`.
4. Call `yagna id drop <id>` on this identity.
5. Receive a message: "The identity is currently in use. After its deletion, a server restart will be necessary for the changes to take effect. By deleting this identity, you will also delete the internal key to your payment wallet. If you have any funds on it and haven't backed up the key, you won't be able to recover them. If you have any open contracts or pending payments on this identity, you won't be able to close or settle them. Are you sure?"
6. Confirm and receive a message to restart the server.
7. Check `yagna id list` to verify if the identity still exists.
8. Perform a restart and check `yagna id list` again to confirm the identity has been deleted.

Here's the translation of UC5 into English:

## UC5: Importing a Previously Deleted Identity

1. Create an identity and export it to JSON using `yagna id export <id>`.
2. Delete it according to the UC4 scenario.
3. Reimport it using `yagna id create --from-keystore <file.json>`.
4. Verify its proper functionality by running any sample from `yapapi` on the newly imported identity.
