### ISSUE TITLE
deploy decentralized market devnet

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#507]
Side-goal is to introduce another person into process of setting up yagna-net's

- [x] repository with all scripts
- [x] command for updating scripts on network nodes
- [x] one command for running devnet
- [x] graceful killing of providers and daemons (don't kill all networks)
- [x] in main directory are only logs from last execution. Previous logs are moved to archive
- [x] instruction on Notion or in repository
To consider:
- [ ] easy downloading of .deb packages
- [ ] check if scripts are flexible enough to run testnet

**Comment by nieznanysprawiciel** [comment]
Closed in:
https://github.com/golemfactory/yagna-testnet-scripts/commit/27c3bed007d1d553f57a0c84bc90c41d540b42e8
