### ISSUE TITLE
(cron) job to check if the `testnet` works

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#597]
- [x] it should run every 15/30 mins
- [x] report status somewhere or alert if `testnet` is not operable (mail or im)
- [x] be easily extensible to support more `devnet`s in the near future
- [x] uses `yapapi` `v0.1.5`
- [x] store logs for failures in user home subdir
- [x] store logs for all script invocations in `/tmp`
- [x] simplistic logrotation policy

**Comment by etam** [comment]
https://github.com/golemfactory/yagna-testnet-scripts/pull/3

**Comment by etam** [comment]
It's currently running every 1h. I wouldn't go lower than every 30 minutes. If something fails in task, the timeout is 15 minutes.
