### ISSUE TITLE
[CLI] Add generic mechanism for user-friendly error handling

### ISSUE THREAD

**Issue by stranger80** [golemfactory/yagna#624]
Yagna CLI calls are forwarded to Daemon's GSB endpoint and Daemon responses are displayed to user console. 
However low-level errors tend to be returned as serialized error message which can be eg. an Actix error (totally unreadable to user). 

It should be possible to "wrap" the errors with more descriptive (and helpful) messages. Eg. When a GSB remote router fails to connect to Daemon GSB Endpoint, the message returned is a generic "Mailbox has closed". CLI should respond with stg like "Unable to connect - is the Daemon running?".

**Comment by jalas167** [comment]
to be handled in ux improvement project
