### ISSUE TITLE
Jacek needs changes in AR --> @etam

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#664]
- [ ] yagna deamon must run permanently (not to be killed after AR finishes)
- [ ] ability to run multiple ARs simultaneously on the same machine 

Requested by @jamuszyn for Community Alpha.dwa reveal
Target solution date: 14 Oct 2020

**Comment by jamuszyn** [comment]
+ adjust the price for the task

**Comment by tworec** [comment]
@jamuszyn this one-time adjustment or you will be experimenting/changing more frequently?

**Comment by jamuszyn** [comment]
> @jamuszyn this is a one-time adjustment or you will be experimenting/changing more frequently?

@tworec it can be hardcoded for now

**Comment by etam** [comment]
budget: 3 ngnt
