### ISSUE TITLE
stopped connection to gsb

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#752]
Yagna version: 0.4.1

This sometimes happen on our providers: [manchester.zip](https://github.com/golemfactory/yagna/files/5474658/manchester.zip)
Warning: this contains logs from both yagna and ya-provider in one file.
Also, some noisy lines containing "GET /market-api/v1/offers", "GET /activity-api/v1/events" and "GET /metrics-api/v1/expose" were filtered out.

It looks like during running a computation, the GSB is closed. After this happens, the provider is not computing anything.

**Comment by etam** [comment]
Version: pre-rel-v0.5.0-g3e2372e4

At some point, with no apparent reason, yagna just closed GSB.
```
[2020-11-18T23:40:29Z INFO  ya_service_bus::connection] stopped connection to gsb
```
logs: [eniac.3.zip](https://github.com/golemfactory/yagna/files/5565712/eniac.3.zip)

**Comment by tworec** [comment]
still happends.
today whole devnet-alpha.4 was affected

![image](https://user-images.githubusercontent.com/12720209/104744688-77445f80-574d-11eb-9fd8-c7a5177f5e86.png)

https://yastats.golem.network/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22devnet-alpha.4%5C%22%7D%20%7C%3D%20%5C%22stopped%20connection%5C%22%22%7D%5D

**Comment by tworec** [comment]
```
$ logcli query --since=$((7*24))h --limit=1000000 '{job="devnet-alpha.4"} |~ "protocol error|ya_service_bus::connection|broadcast"' | awk -v p=1 '/broadcast/ {last=$0; if (p) {print}; p=0}; !/broadcast/ {if (last) {print "..."; print last}; print; p=1; last=""}' > devnet-alpha.4.log
```

[devnet-alpha.4.log](https://github.com/golemfactory/yagna/files/5821824/devnet-alpha.4.log)
