### ISSUE TITLE
Connections to faucet are not closed. Out of file descriptors after long run.

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#760]
Yagna version: https://github.com/golemfactory/yagna/tree/pre-rel-v0.4.1-fix-738 (50eda9ec6e740ca6a42077b92658f82cda299c75). It's basically 0.4.1 with some unrelated changes.

Steps to reproduce:
- run yagna service
- every 5 minutes call `yagna payment init -r` and request some computation

Result:
`lsof -i -a -p <pid of yagna> -n -P | grep ":4000 (CLOSE_WAIT)" | wc -l` reports a number growing over time.

**Comment by etam** [comment]
related?
```
$ yagna payment status
Error: Service receiver was cancelled
```

**Comment by tworec** [comment]
I the past we've dealt with such errors by reusing awc.
