### ISSUE TITLE
remove ya-requestor

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#842]
- [x] confirm with payments team (@wiezzel @maaktweluit)
- [x] confirm with test harness team (@zakaprov)

**Comment by zakaprov** [comment]
@golemfactory/ya-payment Correct me if I'm wrong, but I believe the only dependency on `goth` front is having a test which includes payment platform negotiation (currently performed by `ya-requestor`). One way of enabling this that I'm aware of is to add support for `yapapi` in `goth` (https://github.com/golemfactory/yagna-integration/issues/240).

**Comment by tworec** [comment]
closed via #925
