### ISSUE TITLE
Unable to continue work - No Arm64 support

### ISSUE THREAD

**Issue by Childsp** [golemfactory/yagna#891]
Didn't realize this wouldn't be supported for the Raspberry Pi 4 ARM64 support. 
Kicking myself from the queue of work and giving my spot to someone else.

**Comment by cryptobench** [comment]
Hello! We currently don't officially support ARM processors on the network.

However we do have some community members trying to port Golem to ARM which they're very well on track to, so if you're interested in hearing more on that, you can contact Nebula#0166 or MSD#4683 on our [Discord](https://chat.golem.network)
