### ISSUE TITLE
Solve Agreement approve timeout problem

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#907]
- Requestor confirms `Agreement` and `waits_for_approval`
- Provider makes `Approve` and waits with timeout for response from GSB from Requestor
- It is possible, that Requestor will handle Approve and update it's state, but Provider will get timeout

**Comment by tworec** [comment]
loosly related to #921

**Comment by nieznanysprawiciel** [comment]
Probably properly handling of reverting state (like in #1015) should solve the problem. We should take a look if it will be correct after these changes

**Comment by nieznanysprawiciel** [comment]
This problem never appeared, so closing
