### ISSUE TITLE
wait for agreement approval (req) should return AFTER approve (prov)

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#921]
Now it is not guaranteed, which causes
```
[2021-01-13 16:26:59,512 ERROR yapapi.rest] Failed to create activity for agreement c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
```

because
```
[2021-01-13T15:26:59Z DEBUG actix_web::middleware::logger] Error in response: BadRequest("Agreement c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3 is not Approved. Current state: Pending")
```

Provider's approval event is emitted after Requestor's approval event

## Requestor
```
sqlite> select * from market_agreement_event where agreement_id like '%c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3';
          id = 3
agreement_id = R-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Approved
   timestamp = 2021-01-13 15:26:59.379966
      issuer = P
      reason = 
   signature = 

          id = 5
agreement_id = R-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Terminated
   timestamp = 2021-01-13 15:27:18.260629
      issuer = R
      reason = {"message":"Successfully finished all work","golem.requestor.code":"Success"}
   signature = 
```

## Provider
```
sqlite> select * from market_agreement_event where agreement_id like '%c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3';
          id = 134
agreement_id = P-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Approved
   timestamp = 2021-01-13 15:26:59.472703322
      issuer = P
      reason = 
   signature = 

          id = 135
agreement_id = P-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Terminated
   timestamp = 2021-01-13 15:27:18.200151809
      issuer = R
      reason = {"message":"Successfully finished all work","golem.requestor.code":"Success"}
   signature = 
```

This is minor, because `yapapi` is able to handle it correctly via retry

**Comment by tworec** [comment]
As discussed with @nieznanysprawiciel and @mfranciszkiewicz @ 2021-01-29 we will try to resolve it by changing `approve_agreement` algorithm to:
1. change local (Provider DB) agreement state to `Approved`
1. send approval to remote party (Requestor)
  a. if ok, we're done 
  b. if err, revert local (Provider DB) agreement state to `Pending` and return `500` with proper msg
    i. if err (updating DB) then we return `500` with proper msg. Now agreement state on both sides is inconsistent, but Provider Agent received `500` and should not accept `activity creation` nor _ring fence_ any hardware resources for this agreement yet. He can retry approving, and we should allow state (local) transition `Approved` --> `Approved`, to handle it properly.

**Comment by jiivan** [comment]
I think that locking/forcing `get_agreement` to wait till approval procedure is finished is the best solution, as it gives more benefits the potential inconveniences.

It will guarantee that once returned state is *APPROVED*, either side can act accordingly without requiring complicated agent logic with three signatures and proceeding with activity only when all three are present.

**Comment by tworec** [comment]
Video meet @ 2021-02-04 @nieznanysprawiciel @jiivan @mfranciszkiewicz @etam and me.

We've decided that we will introduce new GSB message from requestor to provider as pictured on below diagram.
This message is an ack for an ack ;) which ends agreement handshake and is described in Market Spec. 

![image](https://user-images.githubusercontent.com/12720209/106878026-c4c34500-66d9-11eb-8e34-7d50528a69af.png)

**Comment by tworec** [comment]
closing via #1015
